beetbox/beets

beetsplug/lastgenre/genres-tree.yaml
beetsplug/lastgenre/genres.txt

See discussion from https://botbot.me/freenode/beets/msg/28875043/

lastgenre: Add "comedy" to genre whitelist.

---

beetsplug/fetchart.py
test/test_fetchart.py

Code + test. Fixes issue #1177

Fetchart: check that the art found is a file

---

beetsplug/mpdstats.py

mpd responds twice to an 'idle' command upon a 'natural' song change
(i.e. not a skip). Checking the reason for mpd response avoids
registering twice the song change.
Fix issue #773

mpdstats: don't register a natural song change twice

---

beetsplug/convert.py
beetsplug/echonest.py
beetsplug/embedart.py
beetsplug/fetchart.py
beetsplug/fuzzy.py
beetsplug/importadded.py
beetsplug/importfeeds.py
beetsplug/lyrics.py
beetsplug/mpdstats.py
beetsplug/scrub.py

Replace with `self.config` where this is painless.
More plugins would benefit from this update but that requires turning more functions into methods.

Delete useless "config['mypluginname']" mentions

---

beets/autotag/mb.py
beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst

See conversation from https://botbot.me/freenode/beets/msg/29798853/

Move autotag.mb.SEARCH_LIMIT to configuration

---

beetsplug/embedart.py

Don't stop at the first item but try them all.
Fix #1261

embedart: try extracting from items until success

---

beetsplug/embedart.py
docs/changelog.rst
docs/plugins/embedart.rst

Added the feature requested with #1261.

Extractart for albums

---

beetsplug/info.py
docs/changelog.rst
docs/plugins/info.rst
test/helper.py
test/test_info.py

Info plugin can filter properties in output

---

beets/dbcore/__init__.py
beets/dbcore/query.py
beets/library.py
test/test_library.py
test/test_query.py

Change InvalidQueryError in the more specific InvalidQueryArgumentTypeError and use InvalidQueryError in new places.
This is related to #1290

Improve errors due to invalid queries

---

beetsplug/replaygain.py
docs/plugins/replaygain.rst
test/test_replaygain.py

first proposal for tests of the bs1770gain replaygain support

Bs1770gainsupport-tests

---

beets/ui/commands.py

Taking a stab at resolving #1401

Sorting printing of fields

---

beets/ui/commands.py

Fixed a variable referenced before assignment when beets cannot open the log file.

Fixed variable referenced before assignment.

---

beetsplug/embedart.py
docs/changelog.rst

Fix #1427: embedart plugin should observe write config

---

beets/autotag/match.py
beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/types.py
beets/importer.py
beets/library.py
beets/mediafile.py

Sorry for opening an issue without searching

Some typos fixes

---

docs/plugins/index.rst

Also edited the file a bit for consistency.

Added beets-noimport plugin to the plugins documentation page.

---

docs/changelog.rst

Updated changelog with information on fix #1487

---

docs/dev/plugins.rst

Fix capitalization of examples and add a comma

---

extra/_beet

This allows to complete albums, artists, etc… in the zsh command-line for users who did not define a specific library location.
Also removed some trailing whitespaces along the way.

Add default library location fallback for zsh completion

---

test/test_permissions.py

Convert paths to UTF-8. See #1557

Support paths with non ASCII characters

---

docs/guides/main.rst

Fix guide AUR link

---

beetsplug/play.py
docs/plugins/badfiles.rst
docs/plugins/play.rst

A new plugin by @fxthomas!
Before merging, I'd love to have input from @fxthomas about whether I messed anything up. I also have a short to-do list:

Badfiles plugin

---

beets/ui/__init__.py
beets/ui/commands.py

Hey,
by using beets on my computer I experienced the lack of some sample queries when doing beet ls. Especially the format option was difficult to me.
Maybe I can help others with this code.

Additional help text for commands

---

index.md

Not really a high priority issue but I thought it may as well be fixed :smiley:.

Fix link to pip on website

---

test/test_ui_commands.py

Just added my first test case. Please review and comment!

added test for beets.ui.commands

---

docs/plugins/index.rst

Since I haven't heard any complaints that it is not working, it could be worth mentioning :)

Add whatlastgenre to plugin index doc

---

test/test_logging.py

coverage of logging.py should be 100% now

added test for logging

---

beetsplug/importadded.py

Pull request as announced in #1628

removed deprecated checko for mtime!=None

---

beets/autotag/mb.py
beets/config_default.yaml
beets/importer.py
beetsplug/discogs.py
beetsplug/lastgenre/__init__.py
docs/changelog.rst
docs/plugins/discogs.rst
docs/reference/config.rst

More general approach to #1692

Made various artist title configurable

---

beetsplug/embyupdate.py
docs/changelog.rst
docs/plugins/embyupdate.rst
docs/plugins/index.rst
test/test_embyupdate.py

Its a simple plugin that triggers a library refresh after the library
got changed. It does the same thing like the plexupdate plugin.

Added embyupdate plugin

---

test/test_query.py

First approach to fix the tests under windows

Tried to fix test on windows

---

test/test_library.py

Hi,
thank you for merging #1743 but i would like to keep this branch open for a while to get the test results from appveyor as i don't have a windows machine to test my fixes.
I will give you a shout or merge this branch on my own when i finished my work

fix tests on windows

---

_layouts/main.html

yep. https://github.com/sampsyo/beets/issues/1765

whitespace

---

beets/library.py
beetsplug/acousticbrainz.py
docs/plugins/acousticbrainz.rst

To Do:
+ ~~auto mode~~
+ ~~request more tags~~
+ POST data
+ Write tests

AcousticBrainz: More features (autotag)

---

test/test_ftintitle.py
test/test_permissions.py
test/test_ui.py

No need to merge quite yet; I plan to add more. Just wanted to make the PR to get it out of the way.

More test improvements

---

test/test_art.py
test/test_convert.py
test/test_dbcore.py
test/test_edit.py
test/test_importer.py
test/test_logging.py
test/test_ui.py

(I would have pushed this branch to the main repo, but I don't seem to have access there yet.)

Add & modify tests

---

test/test_ui.py

Hi,
i just cherry picked the commits from #1838 which only apply to coverage.
I will hit the merge button if the tests succeed and the coverage is ok

Extend test for modify

---

docs/plugins/lastgenre.rst

The internal whitelist is already linked, this one should be, too!

Link to nested genre names

---

docs/guides/advanced.rst
docs/reference/cli.rst

@sampsyo is this documentation what you requested in #1843?

Documentation for changes by #1843

---

beetsplug/lastimport.py
docs/changelog.rst

#1859 
Hi, just found this project and was poking around. Figured this was a pretty easy fix to get started.
This worked in my testing and I hope it solves the issue. Please let me know if there is something I should be doing differently in regards to branching and pull requests. I'm pretty new to this.

Use beets API key for lastimport plugin.

---

docs/plugins/lastgenre.rst

It really didn't make sense to me before I did some further research. You shouldn't have to do further research to understand this apart form reading the docs.

Add some more docs to canonicalization with example

---

beets/ui/__init__.py
beetsplug/mbsync.py

treewide: add `u` to instances of 'singleton:true'

---

beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst
test/test_art.py

First steps in implementing #1944.
Missing:

Allowing slightly non-square images in fetchart (#1944)

---

README.rst

Reorder shields and add weekly PyPI downloads, GitHub issues and GitHub license shields.

Reorder shields and add new shields

---

beetsplug/lyrics.py

Could someone verify the logic for disabling sources/translation?
Should there be a changelog entry? AFAIK, the offending changes have not been in a release.

lyrics: clean up import handling and source removal (Fixes #1963)

---

beetsplug/convert.py

convert.py: Fix error message

---

docs/changelog.rst

Followup to #1982, I hope rst works like that.

Document convert plugin ogg quality change

---

beetsplug/hook.py

Hopefully this is a fix for #1979 as well as a fix for the bug mentioned below by @sampsyo.

Fix command formatting for hook plugin

---

docs/plugins/index.rst

Update location of noimport plugin in docs

---

.travis.yml

See discussion in: https://github.com/beetbox/beets/pull/1987

Cache tox and pip directories for travis

---

beetsplug/convert.py
docs/changelog.rst
docs/plugins/convert.rst

This PR makes the extension optional for the convert plugin.

Make convert extension optional

---

beetsplug/replaygain.py
docs/changelog.rst

make bs1770gain calculate sample peak instead of true peak

---

beets/autotag/hooks.py

I'm not actually sure if this is enough or if we want to use total_ordering vs implement
the rest of the comparison operators.
Let me know your thoughts!

Replace __cmp__ with rich comparisons for Distance

---

beets/importer.py
beets/library.py
test/helper.py
test/test_art.py
test/test_convert.py
test/test_embedart.py
test/test_filefilter.py
test/test_files.py
test/test_importadded.py
test/test_importer.py
test/test_ipfs.py
test/test_library.py
test/test_mediafile.py
test/test_mediafile_edge.py
test/test_play.py
test/test_plugins.py
test/test_query.py
test/test_smartplaylist.py
test/test_thumbnails.py
test/test_ui.py
test/test_ui_commands.py

Make sure many/most strings that touch the filesystem are
converted explicitly to bytestrings rather than implictly.
Definitely review to make sure I used the right constructs/functions

bytestring normalization

---

beets/config_default.yaml
beets/importer.py
docs/changelog.rst
docs/reference/config.rst

Another attempt to fix issue #185

Fix issue #185

---

.gitignore

Simple change to .gitignore, to fix #2129

Ignore PyDev and Eclipse project settings.

---

test/test_ui.py

Fix patcher to always be correctly cleaned up

---

docs/plugins/index.rst

docs: add instructions to install plugin dependencies, fixes #2136

---

beetsplug/edit.py

I've detached this from #2151 to see how it goes separately.

Read and write edit plugin yaml as utf-8

---

.travis.yml

Add gstreamer deps to travis config

---

beets/library.py

Create a custom `bytelower` sqlite function so we can compare bytestrings in a semi
case insensitive fashion.  This is to work around sqlite builds are that compiled
with `-DSQLITE_LIKE_DOESNT_MATCH_BLOBS`.
See https://github.com/beetbox/beets/issues/2172 for details.

Compare case insensitive paths with SUBSTR and BYTELOWER

---

beetsplug/duplicates.py
docs/changelog.rst
docs/plugins/duplicates.rst

This was extracted from the click branch. I'm not sure how we could make this BC, but if you have any ideas, then let me know.
Also, please suggest any wording changes.

Use -k for each arg in duplicates plugin

---

docs/guides/main.rst

Addresses the SIP issue, and incorporates edits suggested by @sampsyo to https://github.com/beetbox/beets/pull/1742

Add workaround for SIP

---

beetsplug/missing.py
docs/changelog.rst

making it of type INTEGER. also changelog for above.

missing plugin, modify "missing" attribute by modifying album_types

---

beetsplug/convert.py
docs/changelog.rst
test/test_convert.py

Maybe one test coming tomorrow.
This should fix #2260

Convert: Don't prompt for confirmation if query result is empty

---

beets/autotag/hooks.py
beets/autotag/match.py
beets/plugins.py

The easy parts.
So far it is relatively straight forward and it is easy to see that the code is improved as a consequence, but my end goal would be to propagate the changes upwards to `tag_album` in `beets/match.py` and refactor/simplify along the way

[WIP]Use generators and decorators to match items:

---

docs/faq.rst
docs/reference/cli.rst

Here you can find some extra documentation for use of selective modify.
Please check (especially spell and grammar) and merge if it is ok
(addition for #1843)

Extra documentation for #1843

---

.travis.yml

Use released version of Python 3.6 for travis

---

beetsplug/discogs.py
docs/changelog.rst
test/test_discogs.py

An attempt at #2318, by trying to make use of the subtrack positions (which in turn is based on the standard discogs positions at [guideline 12.2.9](https://www.discogs.com/help/doc/submission-guidelines-release-trk)) to identify in which cases subtracks should be merged into a single one, and in which cases should be kept as individual tracks.
As mentioned on https://github.com/beetbox/beets/issues/2318#issuecomment-269357217, after another look at the discogs guidelines and at a number of API responses, I can't seem to find another, more robust way of trying to guess which case should be applied for an individual release. While I believe this fix works properly on the examples mentioned on the issue (both the two release that have subtracks that should be kept as individual tracks, and …

discogs: revise subtrack merging based on subindex

---

docs/plugins/absubmit.rst

Add notes about AcousticBrainz requirements

---

beetsplug/mbcollection.py

In response to a request to change the license on a plugin. I've also updated my email address.

Change license and email address in mbcollection plugin.

---

beets/importer.py

Decode bytes to str before call to path_test

---

docs/guides/main.rst

Modified "Seeing your Music" section to add explanation of the ``-f`` param of the list command. I strongly believe that first time users would very much like to start by overriding the default format of displaying results.

Updated main.rst - Updates to seeing your music

---

docs/reference/cli.rst

Issue #2475
Hi here is the change paragraph in the reference guide.

change modify paragraph

---

beets/autotag/mb.py
docs/changelog.rst

Use preferred countries when selecting a release event

---

beetsplug/convert.py

On Python 3, this tries to pass through the Unicode filename representation for paths to the Windows API. If I'm lucky, this fixes #2515.

Attempted fix for #2515 (convert on Windows)

---

beets/dbcore/query.py

As discussed in pull request #2517, here is a separate pull request for a refactoring of the method by which date queries are validated. This is in anticipation of adding three more datetime formats and precisions for hour, minute, and second, in new feature #2506.

Date value field validation method

---

beetsplug/lastgenre/__init__.py
test/test_lastgenre.py

...occuring with `prefer_specific:yes` and `canonical:yes`.
fixes #2459

Fix a lastgenre crash

---

beetsplug/importfeeds.py

Submitted as a pull request to run the tests because I can't get `tox` to work correctly.

Fix importfeeds plugin on Python 3.

---

beetsplug/embedart.py
docs/plugins/embedart.rst
test/test_embedart.py

Clearart asks for permission before deleting embedded albumart 

---

beetsplug/lyrics.py

Addresses issues #2545 #2246.
Not sure about legal aspects though.

Fetch lyrics from Genius through scraper

---

beetsplug/web/__init__.py
docs/changelog.rst

Added Exception and unidecode to web plugin. Added Description to Changelog

Fix unicode bug in web plugin

---

README.rst

- Add repository title
- Add `Features` header
- Move installation instructions to dedicated `Install` header
- Add wiki link to `Contributing` section

Edit README.rst structure

---

docs/plugins/index.rst

Sort plugins documentation within each section. Section "other plugins" kept as is.

Plugins doc update

---

beetsplug/sonosupdate.py
docs/changelog.rst
docs/plugins/index.rst
docs/plugins/sonosupdate.rst

This will trigger a sonos controller on the network to update its music library.

Add sonos updater plugin.

---

beetsplug/lyrics.py
docs/changelog.rst

fix list item remove error on lyric plugin

---

beetsplug/lyrics.py
docs/changelog.rst

Make lyrics plugin group songs by 'albumartist' rather than 'artist'

---

test/test_art.py

Added unit tests for the iTunes source of the fetchart plugin.

Unit tests for fetchart plugin iTunes source

---

beets/art.py
beets/library.py
beetsplug/convert.py
docs/changelog.rst
docs/plugins/convert.rst

Add id3v23 option to convert plugin

---

docs/plugins/index.rst

Functional plugin following the discussion on #2913

added beets-ydl plugin

---

setup.py

Fixes #3168—hopefully once and for all. :smiley:

More complex version dependencies for munkres

---

beetsplug/lastgenre/__init__.py
docs/changelog.rst

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Fix PyYAML yaml.load(input) Deprecation

---

beetsplug/lastgenre/__init__.py

WIP: Remove `default` arg for `lastgenre --force` flag

---

README.rst
README_kr.rst
beets/autotag/mb.py
beetsplug/beatport.py
beetsplug/discogs.py
docs/changelog.rst
docs/dev/library.rst
docs/guides/advanced.rst
docs/guides/main.rst
docs/index.rst
extra/_beet
setup.py

See https://github.com/beetbox/beets/pull/3297.

beets.io now supports HTTPS :tada:

---

beetsplug/importadded.py
docs/changelog.rst

beetsplug/importadded: Add missing path kwarg to update_after_write_time()

---

beetsplug/replaygain.py
docs/plugins/playlist.rst

I found these using the wonderful [misspell](https://github.com/client9/misspell) tool.

Fix various typos

---

beetsplug/unimported.py
docs/changelog.rst
docs/plugins/index.rst
docs/plugins/unimported.rst

Plugin to list all files in the library which are not imported.
Settings:
```
unimported:
ignore_extensions: [jpg,png] # default []
```

unimported files plugin

---

README.rst
docs/index.rst
test/rsrc/lyrics/examplecom/beetssong.txt
test/rsrc/lyricstext.yaml

This is a follow-up on that conversation on gitter:
https://gitter.im/beetbox/beets?at=5d75ac34b3e2fc579379fe25

Replace the clinical "obsessive-compulsive" term

---

docs/plugins/playlist.rst

Fix simple typo: speicifying -> specifying

---

beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst

Implementing fetching of high-res iTunes artwork, as discussed in #3391.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/beetbox/beets/3463)

fetchart: New high_resolution config option (#3391)

---

beetsplug/fetchart.py
docs/changelog.rst

Added merge_environment_settings call in fetchart plugin. 
_EDIT by @wisp3rwind:_
Closes #3450

added merge_environment_settings call 

---

docs/plugins/index.rst

Whilst I am at it, shall I order the plugins in the 'other plugins' section alphabetically?

Added beets-goingrunning to the list of 'other plugins'

---

docs/plugins/chroma.rst

Document running chroma plugin in verbose mode

---

docs/plugins/index.rst

added all my plugins + corrected 1 typo

docs: plugin index update

---

beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst

fetchart: Add Last.fm artwork source

---

beetsplug/fetchart.py
docs/plugins/fetchart.rst

"shows only quiet art" just seems a bit opaque to me.

fetchart: improve description of -q flag

---

beetsplug/subsonicplaylist.py
docs/changelog.rst
docs/plugins/index.rst
docs/plugins/subsonicplaylist.rst

Plugin to import playlists from subsonic servers.

Subsonic Playlist Plugin

---

docs/plugins/index.rst

Hello,
This is one more bullet in the list ; I hope the presentation says it all.
Thanks for beets !

add drop2beets to community plugins

---

beetsplug/lyrics.py
docs/changelog.rst
test/test_lyrics.py

Fix genius lyrics backend artist matching with hyphens 

---

beets/library.py

I figure, let someone change the docstring again if the function gets a special case besides artist / album artist.

Clarify getitem docstring. Log when falling back.

---

CONTRIBUTING.md

Wording seems a little off. I don't think "By following" should be repeated twice in a row

Adjust wording of CONTRIBUTING.md

---

CONTRIBUTING.rst

Advises contributors about the potential issues running the latest versions of tox on Windows
https://github.com/tox-dev/tox/issues/1550

Add tox windows issue to CONTRIBUTING.rst

---

beetsplug/the.py
docs/changelog.rst
test/test_the.py

fix 'the' plugin regex

---

.github/workflows/integration_test.yaml
CONTRIBUTING.rst
docs/changelog.rst
docs/conf.py
docs/dev/index.rst
docs/dev/library.rst
docs/dev/plugins.rst
docs/faq.rst
docs/guides/main.rst
docs/plugins/absubmit.rst
docs/plugins/beatport.rst
docs/plugins/bpd.rst
docs/plugins/convert.rst
docs/plugins/embyupdate.rst
docs/plugins/keyfinder.rst
docs/plugins/kodiupdate.rst
docs/plugins/lastgenre.rst
docs/plugins/lyrics.rst
docs/plugins/plexupdate.rst
docs/plugins/subsonicupdate.rst
docs/plugins/web.rst
docs/reference/config.rst
tox.ini

Fixes broken links throughout the docs and adds an external link checker to the weekly integration test
Fixes #3699

Link check

---

beetsplug/web/__init__.py
docs/changelog.rst
docs/plugins/web.rst

This MR adds limited edit functionality to the REST API exposed by the `web` plugin.
It allows `DELETE`ing items and albums, by ID or query, and `PATCH`ing items.

Web plugin: support limited editing of items and albums

---

docs/plugins/index.rst

See also https://discourse.beets.io/t/1526

Add beats-ibroadcast to list of external plugins

---

beets/util/__init__.py
docs/changelog.rst

In verbose mode, log when files are ignored

---

test/test_lyrics.py

This PR changes the lyrics integration tests to also skip AZLyrics on GitHub actions (they return a 403, failing the test).

Skip AZLyrics on GitHub actions

---

beets/ui/commands.py
docs/changelog.rst

"Issue #3569 changed the the text from Keep both to keep all"
Changed "Keep both" to "Keep all"

Changed the phrasing asked in Issue 3569

---

beetsplug/lyrics.py

lyrics: Strip \u2005 (four-per-em space) in lyrics (Issue 3789)

---

beetsplug/replaygain.py

Fixes #3815.
Apparently I forgot to actually check with the configuration when handling import tasks.

Fix logic for replaygain auto-compute on import 

---

beetsplug/parentwork.py
test/test_parentwork.py

first try at mocking get_work_by_id

---

beetsplug/subsonicupdate.py
docs/changelog.rst
docs/plugins/subsonicupdate.rst
test/test_subsonicupdate.py

this modification will permit that subsonicupdate works with subsonic fork like https://github.com/spl0k/supysonic

add plugin subsonicupdate auth parameter

---

docs/plugins/lyrics.rst

https://github.com/beetbox/beets/pull/3766 missed removing this

remove LyricsWiki from default sources in docs

---

beets/dbcore/db.py
beets/importer.py
beets/ui/__init__.py
beetsplug/bpd/__init__.py
beetsplug/export.py
beetsplug/fetchart.py
beetsplug/fish.py
beetsplug/importadded.py
beetsplug/info.py
beetsplug/mbsync.py
beetsplug/missing.py
beetsplug/replaygain.py
beetsplug/subsonicplaylist.py

Hi, I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some [interesting code quality and performance issues](https://deepsource.io/gh/akshgpt7/beets/) that can improve the general code quality and performance here.
This PR fixes a few of the issues detected.
- Use literals instead of `dict()` calls to improve performance.
- Use safer `sys.exit()` instead of bare `exit()`.
- Merge `isinstance` calls.
- Simplify `if` statement.
- Refactor unneeded list comprehension.

Refactor code quality issues

---

beetsplug/replaygain.py

replaygain: remove debugging leftovers

---

beetsplug/replaygain.py

Part of a larger effort to reduce the nesting level of the replaygain plugin.

replaygain: don't nest functions when there's no need to

---

beetsplug/replaygain.py

Fixes https://github.com/beetbox/beets/issues/3872

replaygain: fix write/force flags on import

---

setup.py

Luckily, we _do_ support Python 3.9 :)

setup.py: add 3.9 classifier, add note about ffmpeg dep for replaygain

---

beets/plugins.py

As https://github.com/beetbox/beets/pull/3896 uncovers, there is indeed some breakage on Python alpha. See the commit message:
```
In
766c8b190bb782a5ef7bafbfa657007d4f158872 from [1]
a slight hack was introduced that allowed to add new arguments to
plugin events without breaking legacy plugins that did not feature
those arguments in the signature of their handler functions.
When improving logging management for plugins in
327b62b6103771bd19465f10a6d4f0412c2b9f1c from [2]
this hack was removed, to be restored with
7f34c101d70126497afbf448c9d7ffb6faf6655a from [3]
Now in addition to inspecting the function signature, an assumption is
made about the string message of the TypeError that occurs for legacy
handler functions (namely, that it start with func.__name__).
In Python 3.10, the …
```

plugins: Python 3.10 compatibility

---

beetsplug/lyrics.py
docs/changelog.rst

As witnessed by #3970, failure to retrieve the lyrics websites wasn't handled consistently. For review, best look at each commit in isolation.
Fixes #3970

Always handle errors in the lyrics plugin

---

beetsplug/subsonicupdate.py
docs/changelog.rst
docs/plugins/subsonicupdate.rst

Fixes #4002.
Tested locally on my Subsonic setup.

Fix for #4002: subsonicupdate plugin broken

---

beetsplug/lyrics.py
docs/changelog.rst

lyrics: fix crash when beautifulsoup4 is not installed

---

setup.py

A trivial changes which is adds missed dependency

Add missed `py7zr` dependency

---

beets/library.py

- Updates existing docstrings to more closely follow google's docstring format (for consistency). 
- Adds a docstring to the Items class.
- Fixes a few typos in comments/docstrings.
- Updates some block comments to follow the PEP 8 style guide.
All of these changes are in library.py.
Does this kind of change require a changelog entry? I am happy to add one if needed. Otherwise, please let me know what you think!

Updates docstrings and some comments in library.py

---

beets/library.py
docs/changelog.rst
docs/reference/pathformat.rst
setup.py

See beetbox/mediafile#58
See #3094

Add the item fields bitrate_mode, encoder_info and encoder_settings

---

beetsplug/deezer.py
docs/changelog.rst

fix deezer pagination

---

beetsplug/replaygain.py
test/helper.py
test/test_importer.py
test/test_logging.py
test/test_spotify.py

Really remove six

---

beets/util/confit.py
test/test_util.py

Show the actual origin of the import statement, cf. #4024.

confit: Improve deprecation warning

---

beetsplug/spotify.py
docs/changelog.rst

Handle audio features are not available Spotify API error 

---

beets/__init__.py

Match setup.py (package) version
- [NA] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [NA] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)
- [NA] Tests. (Encouraged but not strictly required.)

Version bump to 1.6.1

---

beetsplug/spotify.py

Fix spotify_updated bug so that the date is not "null"

---

docs/plugins/index.rst

Corrects popularity service from spotify to deezer to match plugin

Corrects popularity service from spotify to deezer to match plugin

---

docs/reference/config.rst

The from_scratch flag is called --from-scratch on the command line

---

docs/plugins/playlist.rst
docs/reference/query.rst

Improve documentation around the playlist plugin. Clarify what it does and what it does not.

Improve playlist plugin docs

---

docs/plugins/plexupdate.rst

This PR tries to improve formatting on the `plugins/plexupdate` documentation page.
_None of the checkboxes seems applicable to this pull request._

Improve formatting in the `plugins/plexupdate` documentation page

---

docs/plugins/discogs.rst

This PR tries to improve formatting on the `plugins/discogs` documentation page.
_None of the checkboxes seems applicable to this pull request._

Improve formatting in the `plugins/discogs` documentation page

---

beetsplug/permissions.py

The permissions plugin itself walks up the library from the directory we created to the root by default. Therefore it's possible we come across parent directories that weren't created by beets during import and aren't therefore owned by us. Calling os.chmod on a directory not owned by us causes an exception in python; even if the permissions on the parent directory were already correct.

Avoid calling chmod in some scenarios.

---

beets/autotag/hooks.py
beets/autotag/match.py
beets/autotag/mb.py

typing: fixes according to mypy for autotag.*

---

beetsplug/spotify.py
docs/changelog.rst

Fix Spotify error - added exception for TypeError [small PR]

---

docs/plugins/index.rst

Added the `plexsync` plugin to interact with Plex (sync, playlist editing, etc.).

Add plexsync to the community plugins list

---

beetsplug/deezer.py

Fix typo in beetsplug/deezer.py

---

docs/plugins/index.rst

Added JioSaavn.com as a tag source.
I used Deezer and Beatport as the base for this plugin. It works well for me. I am happy to create a PR if we want to have this as part of beets.

Add JioSaavn to the community plugins list

---

beetsplug/web/__init__.py

Fix the CI failure showing up in https://github.com/beetbox/beets/pull/4771

web: fix for breaking werkzeug change

---

docs/plugins/index.rst

Added Youtube as a tag source.
It works well for me. I am happy to create a PR if we want to have this as part of beets.

Add Youtube to the community plugins list

---

beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/dbcore/types.py
beets/util/__init__.py
setup.py

This is part of  #4484, adding typings to the `dbcore` submodule. It's very much still a work in progress. I've made a couple of `# TYPING ERROR` comments where there are obvious things that don't match up with what the typings would seem to suggest. MyPy gives a *lot* more errors than my IDE though so there's clearly some work to be done.

Add typing to dbcore types modules

---

docs/changelog.rst
docs/conf.py
docs/faq.rst

Elaborated multidisc FAQ

---

beetsplug/convert.py

Fix ValueError in convert plugin auto_convert_keep

---

beets/dbcore/__init__.py
beets/dbcore/query.py
beets/dbcore/queryparse.py
beetsplug/playlist.py
test/test_dbcore.py

Some improvements to dbcore typings, see the commit messages for details and rationale.

typings: corrections for dbcore/queryparse

---

beets/importer.py

Update comment explaining how to extend import fields to update fields

---

README.rst

Fix issue with link in readme.

Fix link format in README

---

beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/queryparse.py

Finally, mypy is happy about dbcore :tada:

typing: Wrap up dbcore

---

docs/changelog.rst

Fixes minor typos as noted in https://github.com/beetbox/beets/pull/4778/files#r1219518277

Fix minor "cover_art_arl" typos in changelog

---

.readthedocs.yaml

Fixes #4912. I'm not sure if there's a way to test this before merging into the main branch, but I'm opening this PR just to show what's happening and then immediately merging…

Try adding a ReadTheDocs config

---

docs/index.rst
docs/team.rst

Finally get the ball rolling with our internally discussed introducing "Knowledge Owners" project.

New main docs chapter "Team"

---

.github/workflows/ci.yaml
test/plugins/test_thumbnails.py
test/test_plugins.py

Attempt to fix some recent CI failures that are cropping up in the Windows build. (Although I can't yet see why these problems are Windows-specific.)

Some CI fixes

---

beets/library.py

PathQuery: improve __repr__

---

beets/importer.py
beetsplug/edit.py

Remove a few missed gendered pronouns from code comments.

Use gender-neutral language

---

beetsplug/discogs.py
docs/changelog.rst

Fixes #4973.  
This seemed obvious. I haven't run the test suit locally.

Fixes #4973

---

beets/dbcore/__init__.py
beets/library.py
beets/ui/__init__.py
beets/util/__init__.py
beetsplug/replaygain.py

I've had these lying around already for a while; now rebased on master.

replaygain: add typings

---

docs/plugins/advancedrewrite.rst

Ran into this earlier and decided to add a note to the docs about this.

advancedrewrite: Add note about quoting issues to docs

---

beetsplug/advancedrewrite.py

Felt a bit inconsistent as is, so the same rewrites are now applied to the simple and advanced rules, and more rules were added.

advancedrewrite: Apply same rewrite to more corresponding album fields

---

docs/guides/main.rst

Add Alpine installation instructions.

Add alpine instructions

---

beetsplug/lyrics.py

lyrics: remove version switch that became obsolete when we dropped Python 3.5

---

docs/changelog.rst

Fix what the automated release didn't do right

Fix changelog version

---

beets/__init__.py

Quick merge of this so that the CI doesn't trigger on new PRs.

Fix formatting of version to please the formatting CI

---

docs/guides/advanced.rst

Just some little grammar adjusts.

small grammar corrections

---

.github/workflows/ci.yaml

Apparently the `!` operator does not exist in GitHub Actions.

Fix running tests with/without coverage

---

docs/team.rst

Thanks for adding me as a contributor, @snejus!

Add @bal-e to `docs/team.rst`

---

docs/changelog.rst

- is the language too eager?
- do `:bug:` links work for gh discussions?

bitesize to good first issue: Update changelog.rst

---

.github/workflows/ci.yaml

The fix is based on the following comment:
https://github.com/codecov/codecov-action/issues/1594#issuecomment-2394913029

Fix coverage upload from forks: Attempt #2

---

docs/plugins/index.rst

Add link to community plugin beets-id3extract

Add beets-id3extract to community plugins

---

CONTRIBUTING.rst

remove outdated advice from Python 2 times in CONTRIBUTING.rst

---

beets/plugins.py
docs/changelog.rst
docs/dev/plugins.rst
pyproject.toml

Added some typehints to the `plugins.py` file. There are some typehints missing but I think this is a good first step to get a better DevEx.

Added typehints to the plugins file.

---

beets/util/__init__.py
beets/util/artresizer.py

A rebased & amended version of https://github.com/beetbox/beets/pull/4649.
I left a FIXME note regarding a cleanup that I feel should be done at some point, but that is out-of-scope here when just adding initial typings.

Art resizer typings v2

---

beets/dbcore/db.py
beets/metadata_plugins.py
beets/plugins.py
beets/util/pipeline.py
beetsplug/aura.py
docs/changelog.rst
poetry.lock
pyproject.toml

Removes  the python version dependency for typing_extensions, for more information see #5869

Remove version dependency for typing_extensions
