beets/ui/__init__.py

Check that there is a sub-argument before getting the first one. Fixes issue #1205

Don't crash when no argument is given

---

beets/importer.py
beets/logging.py
beets/ui/commands.py
test/_common.py
test/helper.py
test/test_importer.py
test/test_ui_importer.py

The import log relies on a standard logger, named 'beets.importer' and configured upon initialization of the import session.
Small improvement to the related unit tests.
Related to #1044.

 Use a standard logger for the import log

---

beets/plugins.py
beetsplug/mpdupdate.py
beetsplug/plexupdate.py
beetsplug/smartplaylist.py
docs/plugins/smartplaylist.rst
test/test_plugins.py

Those commits clean `smartplaylist`, `plexupdate` and `mpdupdate`: they use their logger, and they don't rely on a `global` variable any more.
That last point is thanks to an update of `BeetsPlugin.register_listener` which now checks that the target function of a listener is not already registered.

Clean plugins: no global, no print

---

beetsplug/smartplaylist.py
test/test_template.py

- Fix smartplaylist logging string
- Fix smartplaylist unicode playlist names management: don't use an utf8-encoded string as Template
- Add a test to Template: crash on utf8 string (enforce existing behaviour)

Update smartplaylist logging & unicode management

---

beets/dbcore/query.py
beets/ui/__init__.py
docs/changelog.rst
test/test_query.py

So far an invalid query won't be applied:
`    $ beet ls The Beatles year:196a`
will be treaded as
`    $ beet ls The Beatles`
With this commit it stops beets, returns 1 and produces
`    $ invalid query: u'196a' is not an int or a float`
This applies to any querying and therefore on many command, plugins and
some configuration options.
Invalid queries exist on numeric fields and on regular expression usage.
Compile regular expression queries upon instantiation instead of upon
each match test.
The reporting can be improved (give more context). Fix #1219.

Stop on invalid queries instead of ignoring them

---

beetsplug/lastgenre/genres-tree.yaml
beetsplug/lastgenre/genres.txt

Pullrequest for this issue: https://github.com/sampsyo/beets/issues/1239

lastgenre: adding classical music

---

beetsplug/mbsync.py
docs/changelog.rst
docs/plugins/mbsync.rst
test/test_mbsync.py

The mbsync plugin doesn't have the most user-friendly output when dealing with unknown album releases. It only spits out beets' internal IDs or what seems to be a discogs(?) ID.
$ beet mbsync -p
Skipping album 410: has no mb_albumid
Skipping album 333: has no mb_albumid
Skipping album 1668: has no mb_albumid
Skipping album 739: has no mb_albumid
Skipping album 975: has no mb_albumid
Skipping album 1189: has no mb_albumid
Release ID not found: 6225814
Release ID not found: 379309
Skipping album 1669: has no mb_albumid
Skipping album 198: has no mb_albumid
If we want to see what album this really is, another query is required:
$ beet ls album_id:410
This commit adds a `-f/--format` option to allow custom output formats:
$ beet mbsync -p -f '$album'
Skipping album with no mb_albumid: …

mbsync: Support custom output format

---

beetsplug/web/__init__.py

Just a small cleanup - replacing print with _log.info() which now also shows the configured origin.

Replace print with _log.info() in CORS support

---

beetsplug/importfeeds.py
beetsplug/smartplaylist.py
test/test_importfeeds.py

This PR fixes a minor bug where beets would crash if a playlist name contained a path separator and any parent directories didn't already exist. As far as I can see the only plugins affected are importfeeds and smartplaylists.
It may make more sense to eventually abstract the creation of new files and directories into a utility function so this type of bug isn't introduced again later (or maybe this already exists and I just missed it).
(Now if only mpd [supported playlists in subdirs](http://bugs.musicpd.org/view.php?id=311) I'd be all set!)

Fix bug where playlists were not created in subdirs.

---

beetsplug/fetchart.py
docs/plugins/fetchart.rst

Query DBpedia using SPARQL to obtain the filename of the album's cover, as it is used on the relevant Wikipedia article. The direct image url is then obtained using Wikipedia's API.

Fetchart: add fetching artwork from Wikipedia

---

beets/library.py
beetsplug/missing.py
docs/changelog.rst

This fixes tracktotal being stored incorrectly for multi-disc releases
where the individual discs have a different number of tracks and
per_disc_numbering is enabled.

Make tracktotal an item-level field.

---

beets/library.py
beets/ui/__init__.py
beets/ui/commands.py
beetsplug/convert.py
beetsplug/duplicates.py
beetsplug/echonest.py
beetsplug/embedart.py
beetsplug/fetchart.py
beetsplug/lastgenre/__init__.py
beetsplug/lyrics.py
beetsplug/mbsync.py
beetsplug/missing.py
beetsplug/random.py
beetsplug/replaygain.py
test/test_library.py
test/test_ui.py

Cut the need to format manually (and often incorrectly) when logging by implementing the `__format__` magic method.
In `beets.ui`,
* delete `_pick_format`
* update `print_obj`
* improve `print_`
* add `format_` (like `format` but the format spec can be `None`)
Next steps are:
* adapt print & logging in plugins: if there's no real intent for a special formatting, just use the template configured (future commits in this PR)
* make `-p` (path) and `-f` (format) top-level options that can be used in all situations (future PR, raises option name conflicts problems)
* rename options `list_format_{item,album}` to `format_{item,album}`? (can be this PR, + we should keep the current names for retro-compatibility in any case)
This started by a discussion on PR #1262.

Automatic formatting for Album & Item

---

beets/autotag/mb.py

E.g.:  `Error: MusicBrainz not reachable in get release by ID with query etc etc ...`
Catch musicbrainzngs.WebServiceError before the general musicbrainzngs.MusicBrainzError
Fix #1190

Display clear error message when MusicBrainz is unreachable

---

beets/config_default.yaml
beets/ui/__init__.py
beets/ui/commands.py
beetsplug/fetchart.py
beetsplug/play.py
docs/changelog.rst
docs/reference/config.rst
test/helper.py
test/test_ui.py

- Add `colors` option under `ui` option to allow users to choose their own color scheme
- Config option `color` is now nested under `ui` (moved from top-level). A deprecation warning is shown if top-level `color` configuration is used (but it will be respected)
- Documentation has been updated *(not sure if its clear enough though?)*
- The method `colorize` is to be called with an abstract color_name, e.g., `colorize('text_success', 'hello world')`. It can still take an actual color (e.g., 'red'), just in case there are some 3rd party plugins counting on this (no idea if this is the case).
These are all the abstract color names (and their defaults) that a user can configure:
```yaml
ui:
color: yes
colors:
text_success: green
text_warning: yellow
text_error: red
text_highlight: red …
```

Colors are user configurable

---

beetsplug/ftintitle.py
test/test_ftintitle.py

Refactor the `ftintitle` plugin to move the extraction of the featured artist from the artist string into it's own function so that it can be tested.
This also fixes a bug that was in the original code that extracted the featured artist that would cause it to fail if the album artist was on the right side and the featured artist on the left side in the artist field. Also adds test cases to avoid this bug resurfacing.

Refactor ftintitle

---

beets/library.py
beetsplug/embedart.py
test/test_library.py

Fixes #1241 and geigerzaehler/beets-check#14
Before, `embed_item` would add the images to the item and then call `item.write()` to write the item data, including the image, to the file. This would trigger `item.store()` in the `after_write` hook of the check plugin. This would in turn try to persist the temporary `images` attribute of the item, resulting in an SQL error.

Extend item.write() to embed images without changing item

---

beets/importer.py
beetsplug/filefilter.py
docs/changelog.rst
docs/dev/plugins.rst
test/test_plugins.py

This is a new approach to get #1167 done. With the things done with #1186, this is a very simple process :smile:.
At all places where `emit_created` is called, I made sure that the returned list of tasks is used instead of the original task.

Allow plugins to change the created import tasks

---

beets/library.py
beets/ui/__init__.py
test/helper.py
test/test_query.py

Related to #1307 
- PathQueryTest now also tests Album queries (`lib.albums(query)`) instead of just Item queries. *Not sure if this was the proper way to do it, so please correct me!*
- Added `path` to `_types` of Album to ensure that path queries get constructed as they should (fixing the relative path issue)
-  The `_types` member now gets updated from other sources, instead of assigning it (which would override the previous point)

Album path queries

---

beets/library.py
beets/ui/commands.py
beetsplug/convert.py
beetsplug/the.py
test/test_the.py

Also cleanup the 'the' plugin a bit: delete unused variables.
Relates to #1300.

Delete 'format' variables that shadow the built-in

---

beets/autotag/__init__.py
beets/autotag/hooks.py
beets/autotag/mb.py
beets/library.py
docs/changelog.rst
docs/reference/pathformat.rst
test/test_autotag.py
test/test_importer.py
test/test_mb.py

`TrackInfo` and `AlbumInfo` already were already keeping track of this (although in the former it wasn't being set consistently), so just needed to add it as a field to `Item` and `Album`.
See #1311

Set importer metadata source as field

---

beetsplug/permissions.py
docs/changelog.rst
docs/plugins/permissions.rst
test/test_permissions.py

tried to implement feature request #1308. whats your opinion about it? i added my own way to find the folders to run chmod on. like this it only changes artist and album folders in the beets directory and not on full ancestors.

Updated permissions plugin to change directory permissions too.

---

beetsplug/replaygain.py
docs/changelog.rst
docs/plugins/replaygain.rst

Update docs to remove non-existent `apply` option.

Stop applying mp3gain directly to files. Fixes #1316

---

beets/config_default.yaml
beets/plugins.py
beets/ui/__init__.py
beetsplug/chroma.py
beetsplug/discogs.py
beetsplug/fromfilename.py
beetsplug/permissions.py
docs/changelog.rst
docs/dev/plugins.rst
docs/reference/cli.rst
test/helper.py
test/test_logging.py
test/test_plugins.py
test/test_spotify.py

Improve logging verbosity with the new infrastructure. This mostly respects the tables of #1244, where discussion and planning took place.
I had to make unplanned cuts (e.g. deleting `BeetsPlugin.listen` decorator). All those are extensively described in the commit messages.
Commits 1 and 3 are clean, commit 2 is the hacks I had to do to get commit 1 to work, and commit 4 is the docs update (and is pretty bad).

Multiple logging levels

---

beetsplug/embedart.py
docs/changelog.rst
test/test_embedart.py

The crash happened when the album path contains non ascii characters (like äöü). I'm not sure if the solution I implemented is the best way to get around this...

Fix a crash when extracting album art

---

beets/mediafile.py
test/test_embedart.py
test/test_mediafile.py

Filter images on their type, looking for `ImageType.front` ones.
Fix #1332.

Improve art detection

---

beets/dbcore/query.py
beets/library.py
docs/changelog.rst
docs/reference/query.rst
test/test_library.py
test/test_query.py

PathQuery uses LIKE on Windows and instr() = 1 on UNIX.
Fix #1165.

Fix path query case sensitivity

---

beets/config_default.yaml
beets/library.py
beets/ui/__init__.py
beets/ui/commands.py
beetsplug/convert.py
beetsplug/duplicates.py
beetsplug/echonest.py
beetsplug/mbsync.py
beetsplug/missing.py
beetsplug/play.py
beetsplug/random.py
beetsplug/replaygain.py
docs/changelog.rst
docs/dev/plugins.rst
docs/plugins/duplicates.rst
docs/plugins/mbsync.rst
docs/plugins/missing.rst
docs/reference/config.rst
test/test_library.py
test/test_mbsync.py
test/test_ui.py

This PR improves `--format`, `--path` and `--album` options, which are provided by easy-to-use methods of the new default option parser, `CommonOptionsParser`. It reduces the redundancy of options specification for many commands, while offering the same interface: there is no difference for the user. `--format-item` and `--format-album` are also new top-level options.
The `list_format_{item,album}` have turned into `format_{item,album}` and using the former in the configuration sends a warning.
Some incorrect help strings have been fixed as well, such as `--format` for the convert plugin (sets the target format of the music).
This fixes #1271.

Generalize --path, --format and --album options

---

beets/ui/__init__.py

I needed this info when creating a plugin.
By the way, do you prefer small PRs like this one? Or more consequent ones (e.g. some more debug logs could be added, maybe better if I propose a bigger PR?)

Add debug log for plugin paths

---

beets/ui/commands.py
test/test_ui.py

Make `summarize_items()` correctly handle empty item lists, which happen on empty albums.
I also added some tests: `test.test_ui.SummarizeItemsTest`.
This fixes #1357.

ui.commands.summarize_items(): don't crash when there is no item

---

beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/library.py
beets/plugins.py
beetsplug/mpdupdate.py
beetsplug/plexupdate.py
beetsplug/smartplaylist.py
docs/changelog.rst
docs/conf.py
docs/dev/plugins.rst
docs/plugins/smartplaylist.rst
test/test_dbcore.py
test/test_plugins.py
test/test_query.py
test/test_smartplaylist.py

`database_changed` sends the model that changed (stored/deleted/updated) and the `smartplaylist` plugin uses that information to detect which playlists it should regenerate.
Query usage has also been improved: the plugin uses `OrQuery`, which is way faster that merging individual queries.
This is a work in progress:
edit: motivation for that change: playlist building can be really slow (1min+), even if I barely did anything. This solves it.

Smartplaylist only updates playlists that may have changed

---

beets/ui/commands.py
beets/util/confit.py
beetsplug/discogs.py
beetsplug/echonest.py
beetsplug/lyrics.py
docs/changelog.rst
docs/dev/plugins.rst
docs/reference/cli.rst
test/test_config_command.py

I think this was brought up in some issues before, as it makes it easier for people to blanket copy/paste their configuration when posting issues, without worrying about spilling their keys.
This PR introduces the `config -r` ( `config --redacted`) flag, which does the same as `config`, with the fields redacted, e.g.,
```
$ ./beet config -r
lyrics:
sources: [lyricwiki, lyrics.com, musixmatch]
google_API_key: REDACTED
force: no
auto: yes
google_engine_ID: REDACTED
fallback:
[...]
```
- Hard-coded a bunch of typical field names that need to be redacted (`['password', 'username', 'userid', 'apikey', apisecret', 'email']`).
- Plugins can register their own fields to be redacted, e.g.,:
`self.config.add_redacted_fields(['google_API_key', 'google_engine_ID'])`
I was considering working with …

Config: new option -r redacts sensitive fields

---

beetsplug/convert.py
docs/plugins/convert.rst

Closes sampsyo/beets#1382
Allows the user to specify the location where beet places temporary files during import conversion.  This allows beet to use a move operation to place the file into the beet library, as opposed to the copy/delete required when transferring into the library when it is located on an external filesystem (eg. RAID array).

convert: Add 'tmpdir' option

---

beetsplug/ftintitle.py
docs/plugins/ftintitle.rst
test/test_ftintitle.py

(Apologies for the duplicate request, but I referenced the incorrect branch. Thanks.)
I have updated the ftintitle plugin to allow a custom format to be defined. The default format is that which was previously hardcoded.
This pull request allows formats like the list below to be defined:
* feat. ...
* (Feat. ...)
* ft. ...
* featuring ...
This is my first commit to an open source project, so I'm still working my way around the beets project. Any feedback would be great.
Thanks

ftintitle plugin now allows a custom format to be defined (Correct Branch)

---

beets/library.py
docs/changelog.rst
docs/reference/query.rst
test/test_query.py

Detect path parts of a query with `PathQuery.is_path_query()` which tests for `os.sep` presence AND query part existence.
Also fix a bug where "my_path/" would not get detected: colon absence would make search for `os.sep` only happen in "my_path".
Fix #1385.

Improve path query: autodetect only if the target exists

---

beets/logging.py
beets/plugins.py
beets/ui/__init__.py
docs/changelog.rst
docs/dev/plugins.rst
docs/guides/main.rst
setup.py
test/test_logging.py
tox.ini

This is another approach to the remaining logging issues (see #1320 and #1244). This supersedes PR #1366, **however this drops Python 2.6 support**. Indeed:
- it relies on `logging.Logger.level` being a property to a thread-local attribute
- properties do not work on python 2.6
- `logging.Logger` is an old-style class in python 2.6
- it cannot be made a new-style class because we dynamically patch the type of loggers to replace the logging manager (non-existent on python2.6)
Solutions include:
- dropping python 2.6 support (modification of tox.ini required)
- (just thought of it) override setLevel() instead of setting the level.

  Thread safe logging level adjustment, revisited

---

beets/autotag/hooks.py
beets/util/__init__.py
setup.py
tox.ini

I've created a small benchmark where I generated 10 misspellings (using a probabilistic approach) for all the artists / albums / songs in my library (about ~5600 items).
These are the results comparing 3 popular C packages, with our current one
```
python-Levenshtein
elapsed time: 0.0654819011688
jellyfish
elapsed time: 0.0748250484467
editdistance
elapsed time: 0.19926404953
current one: handrolled (from Wikibooks) 
elapsed time: 12.266146183
```
Despite being pretty informal benchmarks, they do show the two orders of magnitude difference.
I've decided to go with `jellyfish` over python-Levenshtein because:
- python-Levenshtein is no longer actively mainted
- python-Levenshtein crashes if two strings are different types (e.g., str and unicode)
- the performance difference between the two …

Use Levenshtein distance from Jellyfish library

---

beetsplug/fetchart.py
docs/plugins/fetchart.rst
test/test_art.py

Been wanting to get this done since quite a while now. So: 
- Minimum image width can be specified via `minwidth` (default `0`)
- The image ratio can be enforced to 1:1 using `enforce_ratio` (default `no`)
See #1058. 
----
I haven't added changelog entry in case you wanna wait for 1.3.12.
Also: not sure how to start with tests for this. Any ideas?

Fetchart: minwidth and enforce_ratio options

---

beets/dbcore/queryparse.py
docs/changelog.rst
docs/reference/query.rst
test/test_dbcore.py

Scan the query parts for commas (`u','`) and treat these as (sub) `AndQuery`s
that need to be wrapped in an `OrQuery` (if there are more than one).
Supports `foo, bar` and `foo , bar`. 
See #976

Use comma as "or" operator for queries

---

beets/config_default.yaml
beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/library.py
docs/changelog.rst
docs/reference/config.rst
docs/reference/query.rst
test/test_sort.py

The problem surfaced after the "OR"-operator introduction: I noticed that *alt-J* was getting ordered below artists with capital letters, which I found annoying.
With `sort_ignore_case: no` (default):
```
$ ./beet --format-item='$artist' ls alt-j, absynthe minded, arcade fire, warpaint artist+ | uniq
Absynthe Minded
Arcade Fire
Warpaint
alt-J
```
With `sort_ignore_case: yes`:
```
$ ./beet --format-item='$artist' ls alt-j, absynthe minded, arcade fire, warpaint artist+ | uniq
Absynthe Minded
alt-J
Arcade Fire
Warpaint
```
I've left the default behavior as is (respecting case), but it could be argued that ignoring it might be more sensible. Or that it needn't even be configurable, and just always ignore case. Thoughts?

Sort can ignore case if configured to do so

---

beetsplug/mpdstats.py
setup.py
test/test_mpdstats.py
tox.ini

I had a small issue where I would play a song with MPD that wasn't imported by beets. So, when mpdstats tried to update the rating it would throw up an AttributeError that looks like:
```
mpdstats: skipped /media/music/tagged/Z-RO/Relvis Presley/09 One More Time.mp3
File "/usr/bin/beet", line 9, in <module>
load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
File "/home/cody/src/beets/beets/ui/__init__.py", line 1104, in main
File "/home/cody/src/beets/beets/ui/__init__.py", line 1094, in _raw_main
File "/home/cody/src/beets/beetsplug/mpdstats.py", line 360, in func
MPDStats(lib, self._log).run()
File "/home/cody/src/beets/beetsplug/mpdstats.py", line 306, in run
handler(status)
File …
```

MPDStats Plugin: handle update_rating when item is None / start tests for mpdstats

---

beets/dbcore/query.py
docs/changelog.rst
test/test_sort.py

Because path is stored as a blob, COLLATE NOCASE doesn't work, lowercase entries come after uppercase ones.
ORDER BY LOWER(path) does work though.

Sort by Path

---

beetsplug/metasync/__init__.py
beetsplug/metasync/amarok.py
beetsplug/metasync/itunes.py
docs/changelog.rst
docs/plugins/metasync.rst
test/rsrc/itunes_library.xml
test/rsrc/itunes_library_unix.xml
test/rsrc/itunes_library_windows.xml
test/test_metasync.py

Adds support for syncing iTunes metadata: *rating, play count, skip count, last played, last skipped*
It uses `plistlib`, which is available for all platforms (since py26), but the behavior is completely untested on Windows system (only tested on my OS X system). The iTunes library is copied to a temporary file before reading it, to avoid corrupting it.
Want to do a few more things, but figured I'd get it up here already (since it technically works).

MetaSync: more OO structure +  iTunes support 

---

docs/reference/cli.rst

I couldn't get beet update to read metadata changes - turns out that puddletag
doesn't touch the file modification time by default. It's a perfectly sensible
behaviour but I thought I'd add a note in the `beet update` section in case
anyone else has this problem.

File modification note in docs

---

docs/plugins/mpdstats.rst
setup.py
tox.ini

note: `python-mpd2` uses the same library name used for `import`, it doesn't need to be changed.
Read #1472 for rationale.
In addition, there's [a strange segfault that pops up with this change](https://gist.github.com/Somasis/370b2166d377e255dbd7). I don't really do much python stuff, I just maintain `beets` for Exherbo Linux, so if anyone has an idea... not a very helpful error, though. I suspect it has something to do `mpdupdate`, since it only occurs at the end.

Use python-mpd2 instead of python-mpd. Fixes #1472.

---

beetsplug/importfeeds.py
docs/changelog.rst

importfeeds: fix #1490 don't overwrite basename argument

---

beets/autotag/__init__.py
beets/autotag/mb.py
docs/changelog.rst
docs/reference/config.rst

This pull request adds support for pregap tracks in imports from Musicbrainz. This will only work after Musicbrainzngs releases a new version and beets starts using it, but everything should work as normal until then.
Two things to note:
* I opted to leave `track_info.index` starting at 1 even in the presence of pregap tracks, which means that users with `per_disc_numbering` deactivated will see the pregap track as track 1 and every other track as its "original" album track number plus one. In albums with a single disc that felt strange to me, but then I thought about albums with multiple discs and multiple pregap tracks - I could set the index of the pregap in the first disc as 0, but then I would have to go sequential from there, including other pregap tracks in the same release. As I …

Add support for pregap tracks

---

beetsplug/plexupdate.py
docs/changelog.rst
docs/plugins/plexupdate.rst
test/test_plexupdate.py

Updated the PlexUpdate plugin to allow Plex Tokens to be provided with the
server details so that beets can update a Plex library that requires
authentication.

PlexUpdate plugin updated for Plex Home

---

beetsplug/fetchart.py

This changes the 'has album art' message to use the green color used for success. I just think it makes it easier on the eyes.

fetchart: Use success coloring if album art is found

---

beets/library.py
beets/util/__init__.py
docs/reference/config.rst
test/test_library.py

Added loop to iterate over sanitize/truncate until stable. Enabled test_truncation_does_not_conflict_with_replacement test. See discussion in #496.

Fixed issue #496 - sanitize/truncate bug

---

beets/importer.py
docs/changelog.rst

The auto-grouper only worked if the filenames in the directory happened to already be in order by artist & album.  Now, the code will first sort by artist & album, then group them.

fix auto-grouping

---

beetsplug/ipfs.py
docs/plugins/index.rst
docs/plugins/ipfs.rst
test/test_ipfs.py

http://ipfs.io or https://github.com/ipfs/go-ipfs is a global, versioned, peer-to-peer filesystem.
This plugin is so far extremely rough, but it adds the option to add or get albums from ipfs.
So if i have an album in my library I can do
```beets ipfs -a [query]```
This will return individual hashes for all the albums files as well as a hash for the whole album.
I can then, in another library without this album, run
```beets ipfs -g [hash]```
and the album will be downloaded from ipfs and imported to the library.
Again, this is a very rough demo, so it's not merge:able yet. But i'd be interesting to hear what you think.

Ipfs plugin

---

beetsplug/lastgenre/__init__.py

Items had not been filtered. Converting the tags' weight into an integer solves it.

Bugfix: Minimum popularity factor had been ignored

---

beets/ui/__init__.py
docs/changelog.rst
docs/reference/config.rst

Fixes #1548.
Signed-off-by: Ben Boeckel <mathstuf@gmail.com>

colors: support standard terminal colors

---

beets/art.py
docs/changelog.rst

Currently, `beet clearart` doesn't notify plugins that some files are modified. This can be a problem when for example using the beets-check plugin because checksums aren't recomputed and the modified files are then detected as not intact during subsequent operations.
I finally settled on fixing this by using the try_write method which allows to simplify the code and centralizes the event sending so that this functionality isn't left out in the future. However, by doing that, `beet clearart` doesn't delete the image tag, but just erases its value. I don't know if this could be an issue.
The beets-check plugin is the only one I know which needs to be aware of a `beet clearart` operation so I don't know if I can write tests for this. Can external plugins be called in the test suite?

Rewrite the clearart method in order to send write events to the plugins.

---

beets/ui/__init__.py

Hi,
if the extra method introduced with 7a8765a would keep the object-oriented interface. But as it was removed, the extra variable can also be removed

removed obsolet variable from PR #1582

---

beets/ui/commands.py
beets/util/__init__.py
beetsplug/play.py
docs/plugins/play.rst
test/test_util.py

I slightly rewrote the play plugin in order to improve the readability and to introduce the "raw" play config option which makes beet simply pass a list of paths to the play command rather than a playlist.
This possibility is useful because [vlc doesn't automatically expand (m3u) playlist files added to the (vlc) playlist](https://forum.videolan.org/viewtopic.php?f=7&t=92840) ([other topics about this issue](https://forum.videolan.org/search.php?keywords=expand+playlist)). Which means that if you intend to use `beet play` several times in a row, either you have to use the `--no-playlist-enqueue` vlc option which means that playback will be interrupted, either the temporary playlist created by beets will probably never be read and expanded.
This PR bypasses this issue by simply giving the …

beets-play: Add the option to pass the "raw" queried pathes to the player command

---

beets/mediafile.py

Hi,
This should fix bug #1303. Basically, this patch sorts the name of all metadata tags in (a somewhat tweaked) lexicographic order when they are processed by the `MediaFile.update()` method.
Only instances of `DateItemField` get sorted in the year < month < day order, so that updates to the corresponding `DateField` object are done in the proper order. It does so by replacing the substrings `year`, `month`, and `day` by `date0`, `date1`, and `date2`, respectively, in the field name of `DateItemField` objects, so that this new string can be used as a key for the sorting algorithm.
There are several other ways to do that, but I think that's the more robust. I'm of course open to discussion. :smiley:
Cheers,
Jérémie.

Fix #1303: process `DateItemField` tags in YMD order

---

beetsplug/embedart.py
docs/plugins/embedart.rst

Adds a configuration property for automatically removing album art files after embedding them.
```yaml
embedart:
remove_art_file: yes|no
```

Add `remove_art_file` configuration property to EmbedArt plugin

---

beetsplug/play.py
docs/plugins/play.rst

The warning_treshold key in the play configuration defines the
minimum number of file before a warning is issued (default 100).
A zero value means no warning is ever issued.
Tests are coming. Could you just confirm this is an OK-to-have feature?

play: make the many files warning configurable

---

beetsplug/plexupdate.py
docs/changelog.rst
docs/plugins/plexupdate.rst
test/test_plexupdate.py

Adds a configuration property to allow the use of libraries that are not named `Music`. This fixes #1572.
```yaml
plexupdate:
library_name: Music (new)
```

Add `library_name` configuration property to PlexUpdate plugin (fixes #1572)

---

test/test_plexupdate.py

Adds a test for a custom PlexUpdate library name (test uses `My Music Library` instead of `Music` for the library name). See #1595 for the actual change being tested.

Add a test for PlexUpdate custom library name

---

test/test_embedart.py

Adds a test for a EmbedArt removing art files (test copies the default art file as provided by `_setup_data` to a temporary location before running). See #1591 for the actual change being tested.

Add a test for EmbedArt removing art files

---

beets/library.py
docs/changelog.rst

This will fix #1587 by using the case-lowering of the database instead of Python and SQLite.

Bugfix for cas insensitive searches for a file path

---

extra/_beet

- Filter out any lines that don't resemble a command in the help text.
- Fixes #1525.

Make command filtering in zsh completion more robust.

---

docs/guides/main.rst

Hi sampsyo,
beets is available as a package on openbsd since nearly 3 releases now, so we can safely strip the -current-tag. Here's my old pull request which kind of announces this pr ;) https://github.com/sampsyo/beets/pull/794
Thanks for this great program. It's a joy to use.

beets is available as a package for openbsd releases since ~1 year now.

---

beetsplug/lastgenre/genres-tree.yaml

Just cleaning up this yaml a bit. I tried to parse it with a Ruby YAML parser and it choked on these keys.

Remove yaml keys without sublists

---

beets/library.py
beets/util/__init__.py
docs/changelog.rst
docs/reference/query.rst
test/test_query.py

This is a little improvement to find out if the file system is case sensitive or not. Until now, beets uses the operating system to determine this: On Windows, beets detected a case insensitive file system, on all other systems it is detected as case sensitive. At least this might be wrong: MacOS' HFS+ might be case sensitive or not. And what if the library is located on a FAT formated file system under Linux?
(In fact, the wrong detection was the reason I opened #1496.)

A robust way to check for a case sensitive file system

---

beetsplug/zero.py
docs/plugins/zero.rst

Hi, I added new behavior to `zero` plugin as requested in #1621.
It works as expected and with no errors (for me :smile:).
Now, `zero` has new option `keep_fields` which contains fields that user want to preserve. Everything else is cleared.

Add whitelist feature to zero plugin

---

beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst

Makes use of the Genius API and genius-api.com, a separate resource that
provides readable lyrics.
Fixes #1626.
This is my first contribution to beets so please let me know if anything is amiss.  I'd like to wrap some testing around this but I'm not particularly familiar with python testing frameworks, so that may take a little while longer.
Requires a new config option ```genius_API_key```, and ```requests[security]``` to quell InsecureResponseWarnings.

Add Genius as a lyric source

---

docs/plugins/types.rst

There's a little mistake in the Types plugin documentation: on the album example, the querying is done with `modify` instead of `ls`.

Fix example of Types plugin documentation

---

beetsplug/fetchart.py
docs/changelog.rst
test/test_art.py

Part of #1679 by @reiv.
> This can be reproduced by simply deleting `cover.jpg` (or equivalent album art file) and then running `beet fetchart`. With this change, when invoking `fetchart` as a command, it will also check if the actual file given by `artpath`  exists in that directory.

Fix #1126: Check if album art file actually exists

---

beetsplug/embedart.py

Should fix #1662.
I think the fix is easy. Don't know if it's clean though. Did some tests (+/- 10 albums), all successful. This is the first time I'm using python so please let me know what I should improve:)

Embedart: remove_art_file on import

---

beetsplug/fetchart.py
docs/changelog.rst
test/test_art.py

Part of #1679 by @reiv.
> I believe this is caused by the fact that if a local `cover.jpg` exists, the `fetchart` plugin would then "discover" this during the import and reuse it. Furthermore, if the `maxwidth` setting is used, `fetchart` will always resize it, creating `cover.1.jpg` in the process. I've rewritten it slightly so that it will only resize if the image is actually wider than `maxwidth`, making `import -L` an idempotent operation.

Fix #1264: Avoid unnecessary art resizes

---

beets/importer.py
beetsplug/fetchart.py
docs/changelog.rst
test/test_importer.py

Part of #1679 by @reiv.
> With a few changes to `importer.py`, the re-import workflow deletes orphaned album art by keeping track of which files aren't reused by `fetchart` during the import process.

Fix #314: Delete old album art during re-import

---

beetsplug/discogs.py
docs/changelog.rst
docs/plugins/discogs.rst

Just a simple config option to change 'various' album artist to the one that MusicBrainz uses: Various Artists. For the purpose of having one V.A. album artist in your library.

Discogs: change album artist to musicbrainz naming

---

beets/autotag/hooks.py
beets/autotag/match.py
docs/changelog.rst
docs/dev/plugins.rst

This PR adds the new hooks `albuminfo_received` and `trackinfo_received` for developers who would like to intercept fetched meta data, before they are applied in tag manipulation operations. See #872

#872: Tag change hooks

---

beetsplug/edit.py
docs/plugins/edit.rst
test/test_edit.py

First batch of commits for the `edit` plugin:
* Add unit tests (focused on black box testing), covering three already implemented scenarios (edit yaml, apply changes - edit yaml, discard changes - do not edit yaml), plus two cases that still need to be handled properly.
* Very minor fix on docs.
* Add proper deleting of `NamedTemporaryFiles` where needed.

editor: add unit tests, minor changes

---

beetsplug/edit.py

changed opts.extra so that is a type: choice
This will give error reporting if false userinput and list correct alternatives.
simplify input a bit
```python
beet edit -e album -e artist
```
instead of 
```python
beet edit -e '$album $artist'
```
but maybe not really beet-style. It does make for better autocompletion in fish:)

change opts.extra to type choice

---

docs/plugins/embedart.rst
docs/plugins/fetchart.rst
docs/plugins/thumbnails.rst

fix #1709
Decided to link directly to their Github instead of github.io

Replace PIL with Pillow

---

beetsplug/edit.py
test/test_edit.py

As per the latest comments on the main Editor pull request, a couple of commits that:
* fix the "*extra fields inserted by user during yaml editing*" test so the changes are applied to the items. It has been renamed to `test_single_edit_add_field`, and an assertion has been added to test that the extra fields are indeed written to the database.
* revise `save_write`, so only items that are `._dirty` are saved.
I'm issuing it as a pull request instead of pushing directly to the main repository branch as I'm not 100% sure if the check on `._dirty` is 100% solid - I'm not so familiar with the library yet.

Editor: update extra fields test, save only dirty items

---

beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/library.py
docs/changelog.rst
docs/reference/query.rst
test/test_dbcore.py
test/test_query.py

A tentative effort for tackling #819, which hopefully will be welcome by users such as myself whose brain decides to forget regular expression syntax more often than not.
It started as a small test on my end (basically, wrap the existing SQL queries with `NOT ()`) and might have turned into a rough but working prototype for several scenarios, and even though the formal tests are far for complete, user should be able to do things like:
```
beets ls Dylan title:¬"tired horses" year:¬1980..1990
```
I'll add some line comments and clarifications within a day, but the main points are:
* Is this the right direction (prepending SQL with (`NOT`), negating the `match()` of the subquery)? I was a bit hesitant at first, but kept adding tests and glancing at [the sqlite SQL …

Add boolean "not" query operator

---

beets/dbcore/query.py
docs/changelog.rst
test/test_sort.py

Fix for #1734 as suggested on the discussion (by simply replacing the line on `dbcore.query.sort()`). Also added a handful of test for making sure it works as expected.

Fix for crash when sorting by nonexistent field (#1734)

---

docs/plugins/inline.rst
docs/reference/query.rst

* Add note about ordering when sorting by custom-fields on query.rst (as per https://github.com/sampsyo/beets/pull/1736#discussion_r45827719)
* Fix typo on inline.rst.
Again, I'm issuing it as a pull request, in the hopes of having it double checked while my *beets-documentation-style* skills are not fully developed!

Documentation update: followup to #1736, fix typo on inline.rst

---

beetsplug/info.py
docs/changelog.rst
docs/plugins/info.rst
test/test_info.py

Work in progress for implementing the feature discussed on #1689, as the workflow proposed by @awesomer would be pretty much aligned with one of my long-term wishlist for my library (ie. a neat way to assist in adding obscure/missing albums to MusicBrainz without the need for extra tools), and hopefully encourage others contributing back to MusicBrainz.
These commits intend to implement the suggested initial changes on the `info` plugin:
> A good first step, should anyone choose to accept it, would be to extend the info plugin so it can be configured to output using formatting, like the list command.
The command now accepts the standard formatting argument (via `cmd.parser.add_format_option`), relying on the `Item.__format__` machinery for formatting. Modifications have been made so an …

info plugin: Allow custom formatting and human-readable lengths 

---

beets/config_default.yaml
beets/dbcore/query.py
beets/library.py
beets/ui/__init__.py
beets/util/__init__.py
docs/changelog.rst
test/test_info.py
test/test_library.py

As a followup to #1689 and #1737, here is a work-in-progress for trying to make the track lengths be displayed as `M:SS` instead of the raw number of seconds (and miliseconds).
I'm assuming the intent is that the change is solely a visual one - database should still store the value as a float. To accomplish this, I have followed your suggestion and set `Item.length` as a custom `DurationType(types.Float)` with `format()` and `parse()` methods that handle the conversion between H:MM and float formats (which has been added to `ui` to avoid some duplication). Additionally, I have added a `DurationQuery(NumericQuery)` in order to be able to perform queries using both formats, ie:
```
$ beet ls length:1:00..2:00
$ beet ls length:60..120
```
I'd welcome some pointers about potential …

Format length as M:SS by default

---

beetsplug/fetchart.py
docs/plugins/fetchart.rst
test/test_art.py

This restores the fetchart plugin’s google backend (see #1760) using the google custom search API.
Configuration options are identical to the lyrics plugin.

Fetchart plugin: new google custom search engine backend

---

beetsplug/play.py

A try at fixing #1600 .
I would argue that for the moment, this is where the fix should stop. Until new user feedback comes, I think the (potential) disadvantages of trying to delete the temporary playlists as we go do outweigh the advantages.
Advantages:
* Privacy: do not leak playlists in `/tmp/`, which is accessible by anyone.
* Storage: do not load `/tmp/` with useless playlists.
However those two seem pretty thin (especially the second one these days). (Self-advertisement: if those constraints are really problematic, the `raw` option of `beets-play` turns out to be a good solution!)
Disadvantages:
* As the playlist consumer is a completely arbitrary choice from the user, it is impossible to know from which point on the playlist can be safely deleted.
This one seems pretty big to me. …

play: remove dead code, fix error catching

---

beets/util/__init__.py
beetsplug/play.py

Fix default command in interactive_open

---

test/test_play.py

Currently, this just runs it, and does not checking for expected values. It's still useful, as it will catch runtime exceptions in the code.

Add tests for play plugin

---

beetsplug/lastimport.py
docs/changelog.rst
docs/plugins/lastimport.rst

Fixes #1574 by changing the API method from library.getTracks to user.getTopTracks, which returns similar information (mbid, artist, title, playcount).
Also, I've replaced the custom HTTP request (using requests) with the pylast library, which is already a dependency of lastgenre.

Fix lastimport #1574 (LastFM API change)

---

beetsplug/info.py
docs/plugins/info.rst

Tries to solve one part of #544: list attributes of the items from the query.
Not sure how to better the help message, needs documentation too.

Info plugin: add option to print only keys

---

test/test_mbsubmit.py
test/test_plugins.py

An attempt to fix #1827, by appending the missing `self.matcher.restore()` calls to the `tearDown()` of `test_mbsubmit.MBSubmitPluginTest` and `test_plugins.PromptChoicesTest`.
I have also double-checked the rest of the tests that use `AutotagStub`, and all seems to be in good order. I'll make sure to triple-check in the future should I need to use `AutotagStub` again!

Fix unrestored AutotagStub on two TestCases

---

beetsplug/replaygain.py
test/test_replaygain.py

* Add a check to ReplayGainGstCliTest that ensures that the required
initial gstreamer plugins can be loaded, skipping the test if it is not
the case instead of running it.
* Add a check to ReplayGainGstCliTest.test_cli_saves_track_gain for
checking if item.rg_track_peak and item.rg_track_gain is not None. If
they are None, it is assumed that the decoder plugins could not be
found, and the tests is skipped, as discussed on #1830.

Skip GStreamer tests if plugins are missing

---

test/test_ui.py

Happens when invoking `tox -e py27 test.test_ui` directly.
`os.environ.get('HOME')` seems to return None and raises an Exception
in tearDown of class
Before merge: Why isn't ConfigTest derived from _common.TestCase as it would automatically set up Home environment?

Fixed bug when running subset of testcases

---

beets/ui/__init__.py
beets/ui/commands.py
docs/changelog.rst
test/test_ui.py
test/test_ui_init.py

as suggested in #1838 i implemented a more generic way to let the user select a list of items to apply an action for
@sampsyo implementation for modify and move command will follow if this approach meets your requirements

Selective apply of functions to items

---

beets/importer.py
beets/ui/commands.py
beetsplug/edit.py
docs/dev/plugins.rst
docs/plugins/edit.rst
test/test_edit.py

As a follow up to #396, an attempt to allow the user to launch the edit plugin during an interactive import session.
At the moment the code is still not complete and rather unpolished and full of TODOs and other comments - but hopefully it will serve as a way to discussing some issues that are not as straight-forward as I'd hoped:
* during an interactive import, the `Items` do not have a valid `id` field, as they are not on the database - and the `edit` plugin relied on it for reconciling back the user changes and other internal functionality. I have resorted to using the `path` field instead of `id` when the plugin is invoked on interactive mode, as it seems to satisfy the requirements for a "reference/mapping" field (unique for each item, non-editable by the user). This is done mainly …

edit: allow interactive editing during the importer

---

beetsplug/lyrics.py

LyricsWiki now escapes song lyrics using HTML entities (presumably to prevent scraping), so we now unescape these before parsing.
LyricsWiki has also added a script tag inside the div we are scraping, so we have to remove this using `scrape_lyrics_from_html`.

Fix LyricsWiki scraping code

---

beetsplug/lyrics.py
docs/changelog.rst

This PR fixes #1880, as well as an unreported issue where lyrics can never be retrieved from MusixMatch due to changes in their website.
On a semi-related note, the capitalisation of the `MusiXmatch` class seems to be incorrect (and is incorrect throughout the codebase); I believe it should be `MusixMatch`. Should I open another PR to fix this?

Fix MusixMatch issues

---

beetsplug/importadded.py
docs/changelog.rst
docs/plugins/importadded.rst

First thanks for beets, it's an incredible tool!
In my setup, I need to preserve mtime at all time, even after import so that my library is still correctly ordered by my streaming software. I added a hook in importadded plugin to do that. There is new option for this module as well to enable this option.
It relies on item.added attribute that should be quite stable if I understand correctly.

importadded: preserve mtime after any write

---

tox.ini

I found this useful to check whether all tests related to the code I changed were actually run. At least to me this was non-obvious as there are unimplemented tests on master (so there's always a number of skipped tests, which may even differ from system to system, depending for example on image-resize backends installed on my box but not on travis).
The travis output of `py27cov` should show what this looks like in a few minutes.

list skipped tests when running nosetests

---

beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst

:globe_with_meridians: Adiou,  
Dunno if it should be merged or if I should maintain it separately in my fork : scratching my own hitch here, and the result of translation can be *suboptimal*.
---
lyrics: fetched lyrics: João Gilberto - Amoroso/Brasil - Aquarela do Brasil (Watercolour Painting of Brazil)
Brasil! / Brazil! 
Meu Brasil Brasileiro /  My Brazilian Brazil 
Meu mulato inzoneiro /  My creamy inzoneiro 
Vou cantar-te nos meus versos /  I will sing you my verses 
Brasil, samba que dá /  Brazil, samba gives 
Bamboleio, que faz gingar /  Wiggle, which makes waddle 
O Brasil do meu amor /  The Brazil of my love 
Terra de Nosso Senhor... /  Land of our Lord ... 
[...]

Add lyrics translation using Microsoft Bing API

---

beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst
test/test_art.py

This has evolved to be my favourite art source due to high quality, hence the PR. There is a nice API, it requires a project API key though.
How has this been handled for other webservices; is there some project(beets.io/beetbox?) mailbox that is usually used for registering keys? This is done on the same website as for personal keys:
[Get an API key](https://fanart.tv/get-an-api-key/)
Using a key registered with a private mail, the code works just fine (for existing as for non-existing art).
Missing:

Fetchart: add fanart.tv source

---

beetsplug/fetchart.py
docs/plugins/fetchart.rst
test/test_art.py

As suggested by @sampsyo in #1917, this is my Fetchart refactoring in a separate PR. It adds no functionality, but may come in handy if I actually get around implementing said PR.
Opened for now to run the tests.

Fetchart: unify source handling, split out of #1917

---

beet
beets/art.py
beetsplug/cue.py
beetsplug/filefilter.py
beetsplug/ipfs.py
beetsplug/metasync/__init__.py
beetsplug/metasync/amarok.py
beetsplug/metasync/itunes.py
docs/conf.py
docs/serve.py
setup.cfg
test/__init__.py
test/test_filefilter.py
test/test_ipfs.py
test/test_metasync.py
test/test_ui_commands.py
test/test_ui_init.py
tox.ini

This adds the [flake8-future-import][f] plugin for flake8, which enforces the standard set of `__future__` imports at the top of all Python files. This revealed a fair number of files that need to be fixed.
To be revisited after #1887 is merged.
[f]: https://github.com/xZise/flake8-future-import

Add __future__ import style checker

---

beetsplug/export.py
docs/changelog.rst
docs/plugins/export.rst
docs/plugins/index.rst

This plugin uses the `info` plugin as basis.
Options:
- You can use `-i artist,title artist: Ladytron`, for example, to produce something like
```json
[{
"artist": "Ladytron",
"title": "Ace of Hz"
},{
"artist": "Ladytron",
"title": "All the Way…"
}]
```
- `-p/--path` for output / dump to console
I did use this to play with some nosql. This may be cool to use with js libraries for data visualizations.

Export plugin: dump item data to a json file / console

---

beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst

This is probably rather niche. I care about high-quality artwork, so occasionally, I might download some images manually in difficult cases and place them in the filesystem to import. Consequently, I don't want them to be replaced by a `beet fetchart -f` which will not consider local art. Even if it did, I don't see a way for it to decide whether the local image is to be kept. This PR would enable me to prevent this by a query like so:
`beet fetchart -f ^artorigin:filesystem`
and even speed it up if I consider a remote source to always provide sufficient quality:
`beet fetchart -f ^artorigin:filesystem ^artorigin:fanart`
Now this does add a config option that I'm not sure of anybody but me would use, therefore I'd like to hear some opinions on whether this should go into master, or rather …

Fetchart store artwork origin in a flexible field

---

beets/library.py
docs/changelog.rst
docs/reference/pathformat.rst
test/test_library.py

The `%first{}` function is inspired by the MediaMonkey `$First(Field, count, skip)`. By default, returns the first element, separated by `; `.
The `%ifdef{field, trueval, falseval}` , for now, returns the field from the item, but wouldn't work with albums. How to resolve this?
1, Have 2 commands, like `%ifdef_item{}/%ifdef_album{}`
2. try to get the album's field, and if can't get, return the item's field or vice-versa (may be a problem with duplicated fields)?

new template path functions: %first{} and %ifdef{}

---

beetsplug/lyrics.py

Use `_scrape_strip_cruft` instead of `scrape_lyrics_from_html` so that LyricsWiki does not depend on Beautiful Soup.
Also removes the unneeded call to `unescape`, as `_scrape_strip_cruft` does that for us too.

Use different method to remove junk from LyricsWiki output

---

beets/autotag/hooks.py
beets/dbcore/db.py
beets/dbcore/query.py
beets/logging.py
beets/util/artresizer.py
beets/util/confit.py
beetsplug/bucket.py
beetsplug/export.py
beetsplug/fuzzy.py
beetsplug/thumbnails.py
test/_common.py
test/test_art.py
test/test_autotag.py
test/test_convert.py
test/test_datequery.py
test/test_edit.py
test/test_importadded.py
test/test_importer.py
test/test_lastgenre.py
test/test_lyrics.py
test/test_mediafile.py
test/test_mpdstats.py
test/test_permissions.py
test/test_query.py
test/test_smartplaylist.py
test/test_thumbnails.py
test/test_ui.py
tox.ini

Add flake8 check for pep8 naming using [pep8-naming](https://github.com/PyCQA/pep8-naming).
In it's current state (as of 698203eb847020194987eef63ad7da052eb86ab0), this check is not passed by beets.
Here are the offending files and line numbers:
```
beets/logging.py:129:5: N802 function name should be lowercase
beets/dbcore/db.py:212:9: N804 first argument of a classmethod should be named 'cls'
beets/dbcore/db.py:277:9: N804 first argument of a classmethod should be named 'cls'
beets/dbcore/query.py:149:9: N804 first argument of a classmethod should be named 'cls'
beets/dbcore/query.py:844:9: N805 first argument of a method should be named 'self'
beets/autotag/hooks.py:300:9: N805 first argument of a method should be named 'self'
beets/util/artresizer.py:152:9: N805 first argument of a …
```

Add flake8 check for pep8 naming

---

beets/config_default.yaml
beets/ui/__init__.py
docs/changelog.rst
docs/reference/config.rst

The problem with the windows "unicode" code page was that they returned the right code page, but python doesn't know how to "use".
The solutions were:
1. monkey-patch a new encoding which returns 'utf-8'
2. let the user override, that basically the same thing as 1, but more clean.
3. use something like
```py
try:
myfunc(get_encoding())
except LookupError:
myfunc('utf-8')
```
One thing to consider, is if `terminal_decoding` should be used to override `_arg_encoding()`

add a 'terminal_decoding' option

---

beetsplug/hook.py

Use unicode for command formatting

---

beetsplug/convert.py

According to the `oggenc(1)` man page (in vorbis-tools), the default quality is 3, not 2. So we should use that.

convert plugin: Change the default ogg quality

---

beets/config_default.yaml
beets/importer.py
beets/util/__init__.py
beets/util/hidden.py
docs/changelog.rst
docs/reference/config.rst
test/test_hidden.py

This fixes #110 by adding a top-level `ignore_hidden` option to the configuration.

Add option to ignore hidden files on import

---

beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst

This directory is often found at the root of various Linux filesystems

add lost+found directory to default ignore list

---

beetsplug/acousticbrainz.py
docs/changelog.rst

AcousticBrainz is going HTTPS-only soon: https://blog.musicbrainz.org/2016/05/19/were-actually-really-going-to-take-the-https-plunge/
This may cause the plugin to [not work with Python <2.7.9](https://tickets.musicbrainz.org/browse/MBH-363?focusedCommentId=39500&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#action_39500) though, hence the PR instead of just pushing it into the tree. OTOH, I don't think the AcousticBrainz people are going to wait around for Debian/Ubuntu to update their packages to move along.
Also not sure about the changelog entry.
Also also: not actually tested yet.

acousticbrainz plugin: Access acousticbrainz.org over HTTPS.

---

beetsplug/web/__init__.py

This patch ensures to return a 404 if the requested album art is not available.
Right now an exception is thrown instead.

web: handle missing art gracefully

---

beets/mediafile.py
docs/changelog.rst
test/test_mediafile_edge.py

Now input like `.` and `1.0.0` are handled

Cover more float types in safe_cast

---

beets/autotag/match.py
beets/dbcore/query.py
beetsplug/acousticbrainz.py

It's no longer a global function in py3

use reduce() from functools

---

beetsplug/web/__init__.py

the following API paths are added:
* /item/unique/FIELD
* /album/unique/FIELD
Both paths will deliver a json dictionary with the key 'values' containing a
list of unique values belonging to the requested table and field.
This feature is useful for categorization by remote clients, e.g. Mopidy-Beets:
* track genres: /item/unique/genre
* track languages: /album/unique/language
* album artists: /album/unique/albumartist
* album years: /album/unique/year
Notes for the reviewer: please take a look at my usage of the half-private attributes "_table" and "_fields". I thought I could use "all_keys()" for the latter, but this attribute was not accessible. I do not know of an alternative for "_table".
Is this attribute access acceptable for you?

web: add API functions for retrieving unique values of specific keys

---

.gitignore

The gitignore is located here: https://www.gitignore.io/api/python
I kept our settings at the top

Rebase our .gitignore on top of gitignore.io

---

beets/__init__.py

I'm not sure why this is here.  It passed the tests and ran without it.

Remove library import from __init__.py

---

.travis.yml
appveyor.yml
setup.cfg
tox.ini

- Add support for Python 3 testing.
- Add Python 3.3, 3.4 and 3.5 tests to Travis and AppVeyor.
- Allow arguments to be passed to tox from test matrix.
- Simplify tox configuration so that we now only have `test`, `flake8` and `docs` tasks.
This is a squashed version of #2029.

Update tox configuration

---

beets/ui/commands.py

[bash-completion2][1] is installed at a different path. This will stop the warning about being unable to find bash-completion.
[1]: https://github.com/Homebrew/homebrew-versions/blob/master/bash-completion2.rb

Support Homebrew's bash-completion2

---

beets/ui/commands.py
docs/changelog.rst
docs/reference/cli.rst
test/test_ui.py

This fixes #2042 by adding a `--force` (or `-f` for short) option to `beet remove`, allowing the deletion prompt to be disabled.

Add --force option to remove.

---

docs/reference/query.rst

As discussed on IRC the current documentation is not clear on which fields are searched in a default query. This change addresses this issue.

Clarify which fields are searched by default

---

beetsplug/bpd/__init__.py
beetsplug/bpd/gstplayer.py
docs/changelog.rst
docs/plugins/bpd.rst

Updated GStreamer from 0.10 to 1.0, as mentioned in #2057.

bpd: Updated to GStreamer 1.0

---

beetsplug/beatport.py
docs/plugins/beatport.rst
docs/plugins/index.rst
setup.py

This restores the previously removed Beatport plugin, this time around with support for their API version 3, which requires OAuth authentication with all endpoints.
The process of obtaining the authentication token and secret is modeled after the way the `discogs` plugin handles this, i.e. the user is asked to visit a website, enter her credentials and then paste the displayed string into the terminal. The plugin then extracts the token/secret and stores it in a file in the configuration directory.
I have not yet tested the integration with beets, so I would welcome any curious testers to try it out.

Revive Beatport plugin with support for OAuth API (#1989)

---

beetsplug/fetchart.py
docs/changelog.rst
test/test_art.py

When downloading files from any source, fetchart used to hardcode the extension to `jpg` but also support `png` images. As there are misnamed (i.e. with a `jpg` extension) files in the wild with a correct `Content-Type` set, use that to determine the extension.
Missing
EDIT: doesn't fix #2053, see there. This PR fixes our part of the issue, the image header based correction to work around the server-side problem is split out into a new PR as its fate is not as clear: #2072.

Fix fetchart hardcoding the image extension

---

beetsplug/beatport.py

As mentioned in the last PR, I had not tested the integration with beets.
Turns out there were two bugs lurking, one due to a naming confusion and another due to incompatibility with the API of the previous plugin version.
Both are fixed and according to my superficial test the plugin should now work as expected.

Fix bugs in beatport plugin

---

beetsplug/fetchart.py
docs/changelog.rst
test/test_art.py

Work-around for #2053, see also #2068. I reported the server-side issue (incorrect `Content-Type` and incorrect file extension) upstream (https://forum.fanart.tv/viewtopic.php?f=4&t=6011), if it gets fixed there, this PR may probably be dropped.
As of now, it not only applies to the problematic fanart.tv source, but unconditionally checks every image (also those found in the filesystem) that is moved/copied into the library, and it is not clear whether this might be overkill (https://github.com/beetbox/beets/pull/2068#issuecomment-227492147).
On the other hand, `imghdr` will only read the first 32 bytes of a file, so this may be pretty irrelevant compared to the amount of filesystem-iteraction for metadata etc.
Uses [imghdr](https://docs.python.org/2/library/imghdr.html) for type …

Rectify artwork extension via imghdr

---

beetsplug/web/__init__.py
docs/changelog.rst
docs/plugins/web.rst

Hello,
I'm currently developing an android app to synchronize your beets library with your android phone. This addition helps me to implement the query and simply some stuff.
There are some screenshots of my app attached.

Add 'expand' flag to the web plugin

---

test/test_hidden.py

test_hidden was missing suite() which made testall.suite() fail

tests: Fix setup.py test

---

beets/util/pipeline.py
test/test_pipeline.py

See Issue #2078. 
**EDIT**: Seems to run fine on all py3 versions in Travis.

Workaround for a race condition on queue invalidation

---

beetsplug/beatport.py
docs/changelog.rst

Previously the track number was determined by the order of tracks as received from the API (via enumerate). However, the API actually returns a canonical track number in the data for a track, so this PR modifies the code to use this instead.
It also sets the `medium_index` to the same value. As far as I can tell Beatport does not have a concept of multi-"disk" releases, so it's probably safe to do it this way.

beatport: Use track numbers from API (#2085)

---

.travis.yml
appveyor.yml
tox.ini

It doesn't seem like Python 3.3 is worth supporting anymore. I'm not
sure if any popular(ish) distro supports Python 3.3, only 3.2 or >=3.4

Remove support for Python 3.3

---

appveyor.yml

Strangely while both "ci skip" and "skip ci" are supported (with brackets)
only "skip appveyor" is supported by default

Add appveyor skip as an alias for skip appveyor

---

.travis.yml

We definitely want py34-flake8 to succeed, so we don't end up with
`unicode` and other py27 specific stuff. With that in mind, we don't need
py27-flake8 anymore either.

replace py27-flake8 with py34-flake8

---

beetsplug/embyupdate.py
docs/changelog.rst
docs/plugins/embyupdate.rst

Add the option to read an API Key from the config file and submit that
instead of needing a password. Doesn't remove the use of password so is
backwards compatible with users current config file

Emby API Key

---

test/test_edit.py
test/test_importer.py
test/test_ipfs.py
test/test_keyfinder.py
test/test_play.py

This removes most of the uses of `mock.patch.start()` from the tests. It is good to remove these, because unlike the other two forms of `mock.patch` (annotation and context manager) the `start()` method requires explicit cleanup.
It is probably possible to remove it from the two remaining files (`test_plugins.py` and `test_query.py`) but it's trickier, and I thought it worth applying these changes in the meantime.
Even though this only touches test code, I'd appreciate someone else hitting the Merge button.

(Mostly) remove patch dot start

---

beetsplug/play.py
docs/changelog.rst
test/test_play.py

if $args was set in config but -A or --args was left off the beet play command, $args would appear in the command. Fixed and test included thanks to Wise Tutelage of jrobeson

fix bug where $args would be included in the command output

---

beetsplug/acousticbrainz.py
docs/changelog.rst
docs/plugins/acousticbrainz.rst

The bpm plugin is a very slow way to add bpm data to songs, using the acousticbrainz plugin is much faster and can doesn't need a new plugin.

Add BPM data with acousticbrainz

---

beets/ui/__init__.py
beets/util/__init__.py
beetsplug/convert.py
beetsplug/hook.py
test/helper.py
test/test_convert.py
test/test_ui.py

We use `_arg_encoding()` for more than UI concerns, so I think it
should go there.
The method is now marked public (the underscore prefix was removed)

Move ui._arg_encoding to util.arg_encoding

---

setup.cfg
tox.ini

Now we can enforce that all py files have the coding magic comment with
utf-8.
https://pypi.python.org/pypi/flake8-coding

add flake8-coding to our tox config

---

beetsplug/edit.py

Yaml doesn't return a true unicode string even with `allow_unicode`
passed to `safe_dump_all`.

decode yaml dumped data as utf-8 in edit plugin for PY2

---

MANIFEST.in

We got [a request](https://bugs.debian.org/775811) to include the zsh completion, in our Debian beets package. To do this, it needs to be shipped in the source tarball.

Include extra bits in the source distribution

---

beetsplug/mpdupdate.py
docs/plugins/mpdupdate.rst

This variable is not standardized, but is already used by the mpc which is the official command-line client. It would be nice if beets read it too, to avoid duplicate configuration for mpc users.

mpdupdate: Use `$MPD_HOST` environment variable.

---

docs/reference/config.rst

Spotted by [lintian](https://lintian.debian.org/full/python-apps-team@lists.alioth.debian.org.html#beets_1.3.19-1) which runs spellchecks on man pages.

Correct a typo

---

beets/util/functemplate.py

Highlights:
* Conditional Python 3 compatble `ast.FunctionDef` and `ast.Call` calls
* Python 2 and 3 compatible string types for `ex_rvalue`
* Only encode strings to `utf-8` on Python2, as they are `unicode` type there. 
* Enable template compilation on Python 3

PY3 compatibility for the functemplate AST compiler

---

beetsplug/fromfilename.py

dict.values() returns a view rather than a list in python3

fromfilename: fix dict view conversion for python3 (fix #2195)

---

.travis.yml

This may or may not be available in the installed pyenv yet.

Add python 3.6-dev to Travis

---

.travis.yml

Now we can test any plugin that depends on Gstreamer. It was previously impossible to do so, since `pygobject` (a gstreamer dep) is not installable via pip. 
I discovered (after totally missing it it in the quodlibet `.travis.yml` for months)  that travis offers `with_site_package` variants of the 2 pythons (one 2.7, one 3.x) that come with the distribution.

add site-packages tests to the travis build matrix

---

beets/ui/__init__.py
docs/changelog.rst

It was deprecated in https://github.com/beetbox/beets/commit/d3fce35481f09f28561dc2438baa7ec5245b7870 on 2015-01-26.

Remove deprecated top level colors config option

---

beetsplug/lastgenre/__init__.py
docs/plugins/lastgenre.rst

(Apologies in advance for my terrible, terrible python. I really wanted this feature, so I hacked my way through it. Please provide guidance on the better ways to do things!)
I love the lastgenre plugin, but after running it on my library, I found myself wishing that it would prefer the _most specific_ tag available instead of simply defaulting to the _most popular_ tag, which is often the most generic. 
Here's an example. I have both "folk" and "americana" on my whitelist and in my canonicalization tree, where "americana" is a leaf within "folk." 
If I run lastgenre for the artist "The Be Good Tanyas", the genres that last.fm returns are: 
```
[u'folk', u'albums i own', u'female vocalists', u'alt-country', u'country', u'singer-songwriter', u'americana', u'canadian', u'2003', u'00s']
``` …

Proposal: Add specificity option to lastgenre plugin

---

beets/dbcore/query.py
docs/changelog.rst
test/test_types_plugin.py

On a attempt to fix #1938, it seems that the problem is actually caused by `DateQuery.match` being reached for an item that does not have a value set for the `field` to be compared? I could reproduced it by using just the `types` plugin:
```
...
types:
foo=date
```
and simply:
```
$ beet ls foo:2000
```
I have added a check that returns `False` (basically copying the one in `NumericQuery.match`), and adjusted some unit tests to catch the situation. I still have not tested specifically with `mpdstats`, as I'm not really an user of that particular plugin, but it seems it would fix the problem?

Do not attempt matching unset fields on DateQuery

---

beets/util/functemplate.py
docs/changelog.rst
docs/reference/pathformat.rst
test/test_template.py

A first take for treating commas (`ARG_SEP`) as a regular character during the template parsing, except when it is used inside a function's argument (ie. `%foo{bar,baz}`), as discussed on #2166.
I have added a couple of tests checking for the usage of commas *before* other elements, as it seems that the problem was that the parser stopped processing the rest of the string whenever an unescaped comma was found. The test suite already includes other tests that deal with separators, (`a $, b`, `a , b`, `%foo{bar,baz}`, `%foo{bar$,baz}`, ...) but I'd be happy to add more if needed.
The solution basically splits the handling of the special characters (`special_chars,` `special_char_re`, and the newly promoted `escapable_chars` and `terminator_chars`) in two cases: one for regular parsing that …

Revise comma handling on templates

---

docs/plugins/play.rst

`{}` is not used any more to determine the location of parameters passed with `--args`.
Fix two sentences for clarity/fluidity. Display the plugin's abilities in the intro.
[Just waiting for the checks to complete.]

doc-play: Fix an error and clarity:

---

beetsplug/discogs.py
docs/changelog.rst
test/test_discogs.py

This pull requests mean to carry on the job by @kooimens at the open pull request #1691, adding some tests and an updated changelog. I cherry-picked the commit from kooimens in order to preserve credit.
As hinted on #2222, the problem was that `medium_count` was correctly increased whenever a new medium was detected on the main loop, but for albums with only one medium that increase did not take place, ending up with a `track.medium = 0`.

discogs: set `track.medium` correctly for single medium albums

---

beets/autotag/match.py

Avoid using `reduce` when it can be elegantly avoided.
`ag '[^\.]reduce\(' -C 5`
````
beets/autotag/match.py
267-        log.debug(u'No album IDs found.')
268-        return None
269-
270-    # If all album IDs are equal, look up the album.
271:    if bool(reduce(lambda x, y: x if x == y else (), albumids)):
272-        albumid = albumids[0]
273-        log.debug(u'Searching for discovered album ID: {0}', albumid)
274-        return hooks.album_for_mbid(albumid)
275-    else:
beets/dbcore/query.py
380-    def __hash__(self):
381-        """Since subqueries are mutable, this object should not be hashable.
382-        However and for conveniences purposes, it can be hashed.
383-        """
384:        return reduce(mul, map(hash, self.subqueries), 1)
385-
386-
387-class …
```

Drop `reduce` imports

---

beets/dbcore/db.py
beets/library.py
beets/ui/commands.py
docs/reference/cli.rst
test/test_ui.py

PR to fix https://github.com/beetbox/beets/issues/2229

Selective field updates

---

beetsplug/smartplaylist.py
docs/changelog.rst
test/test_smartplaylist.py

Make e. g.
- name: $albumartist/$year-$album.m3u'
work when album data includes non fs-friendly characters

sanitize playlist names

---

beets/ui/commands.py

I think this is because of the switch to python3. Fixes printing of flexible attributes, which threw an exception previously.

Removed call to  .decode('utf-8') when printing flexible attributes

---

beets/mediafile.py
test/test_mediafile_edge.py

iTunes has problems with everything but latin-1
Try to use latin-1 if possible and fall back to utf-16.

mediafile: prefer latin-1 encoding for ID3 APIC descriptions. Fixes #899

---

beetsplug/convert.py

Previously "pretend" mode (a.k.a. dry run mode) passed the command to be
printed directly to `_log.info`, whose first argument is technically a
format string. Thus the command string was parsed for replacement fields, such
as `{foo}`, which could cause the format evaluation to fail if the filenames
contained in the command contained valid (or partially valid) replacement fields.
This fix simply inserts an argument `'{0}'` to the call to `_log.info`, which is a
format string that simply evaluates to the second argument to `_log.info` (the
command string). By doing this, the command string is not parsed for replacement
fields.

convert plugin: fix braces in filenames causing tracebacks in "pretend" mode

---

beetsplug/zero.py
test/test_zero.py

The testing is proving to be a real PITA.
I expected to have to rewrite it since it was originally written based on the internals rather than the interface so the cleanup would have consequences. However, what I did not expect is that for some reason there seem to be some state carried from test to test despite `setUp` and `tearDown`. Here are my current thoughts:
* Minor gripe, but `add_item_fixture()` is not *that* practical, because you have to call `item.write()` immediately after if you want the tags to be written to the mediafile fixture. This is a bit annoying, especially when you are trying to test a plugin which is triggered by a write event.
* It seems to me that despite `unload_plugins()`, plugins which did register a listener do not get nuked because they remain registered. …

Cleanup zero plugin

---

beetsplug/random.py
docs/plugins/random.rst

random: add --time option, update docs

---

beetsplug/zero.py
docs/changelog.rst
docs/plugins/zero.rst
test/test_zero.py

I'm fairly new to the process so I hope I've done this correctly. Please let me know if I need to make any changes to get this merged up.
This is for Issue #2274

Add manually triggered mode for zero plugin

---

beetsplug/acousticbrainz.py
docs/plugins/acousticbrainz.rst

Improve the speed of fetching acousticbrainz data. Ignore already existing data.

#2347: First hack of ignoring already tagged items

---

beetsplug/web/__init__.py

This PR fixes the following bug in the web interface
When downloading a file the the following error occurs:
```
[2016-12-29 11:11:07,039] ERROR in app: Exception on /item/10652/file [GET]
File "/home/mrl/projects/beets/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/home/mrl/projects/beets/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/mrl/projects/beets/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/mrl/projects/beets/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
raise value
File …
```

Web attachment filenames must be passed as a string for Python 3

---

appveyor.yml

Obviously it'd be best if we didn't have to do it, but I doubt we can
wait forever for the packagers to add it.

Temporarily allow empty checksum for unrar on appveyor

---

beetsplug/absubmit.py
docs/plugins/absubmit.rst
docs/plugins/index.rst
setup.py

This is a new upload for #2340 as that had some strange problems with the pull request and trying to fix it closed the pull request.
Copy of the last comment in that pull request:
> Thanks for all the advice! I updated the pull request to hopefully fix the strange problem with authorization/ect. I'll also look into the comments, documentation and tests.
Some things I'm wondering:
>
> - Do we want to raise an error if analysis or submitting a file fails?
> - Do we want to save that a file has been analyzed and submitted? The analysis takes a long time and should not change if done multiple times and as far as I can see the the server code ignores any upload that is exactly the same as one already in the system.

Implement the basic AcousticBrainz Submit plugin

---

beetsplug/bpm.py
docs/changelog.rst
docs/plugins/bpm.rst
docs/reference/config.rst

Add write option to `bpm` plugin and tidy up command function.
It looks like a write option was going to be implemented but never ended up being added? The reason I think this is that there's an unused `write` argument for `get_bpm` that writes the item after the BPM is updated.
See #1991 and [#1991 (comment)](https://github.com/beetbox/beets/issues/1991#issuecomment-217119879) for more information.

Add write option to bpm plugin

---

docs/plugins/absubmit.rst

Add a section to the absubmit plugin documentation about files that are skipped by this plugin. As mentioned by @tux-00 in pull request #2342.

Absubmit add section in the documentation on skipped file by the plugin

---

beets/dbcore/query.py

This also works around a bug in Python 3.6.0 on Windows: see #2358.

Use a new stdlib method for dbcore.query._to_epoch_time on Python 3

---

appveyor.yml

Python 3.4 is quite old and offers little value on Windows.
Closes #2344

Replace Python 3.4 with 3.6 on Appveyor

---

docs/reference/config.rst

Just a small change for what looks like a typo in the docs.

Change "items" to "albums" in config docs for sort_album

---

beetsplug/play.py
docs/plugins/play.rst

This is for #2008.
I hope my refactoring isn't way out of line.

play: Add prompt choice to importer

---

beets/dbcore/db.py
beets/library.py

Fixes the issue with multithreading I found when working on #2389.

beets.library.Library adds custom bytelower function to all connections, not just one

---

beets/library.py
docs/changelog.rst
docs/reference/pathformat.rst
test/test_library.py

A little background as to why I felt this was needed:
If I have two albums that are disambiguated by `albumdisambig`, and one album has that field empty, then it would have an empty `[]`. In this case, I would only want the brackets gone.
Also, if I do something like `[$year%aunique{}]`, then I would have two sets of brackets, with the inner set possibly empty.  Plus, in this case, if the inner brackets are removed, then there is still a white space after the year and before the closing bracket.
So this change does a few things:
- It adds a third argument to %aunique{} that should be two characters to be used as brackets.
- It removes the blank space along with any brackets created from an empty disambiguator.
- It adds brackets when the fallback `album_id` is used as the disambiguator (I …

Add bracket argument to aunique

---

beetsplug/mpdstats.py
docs/changelog.rst

This change is related to #773. On my machine, with mpd 20.2 and beets 1.4.4, redundant second on_play call with same song playing, happens only on start of playing queue. Afterwards, this event is triggering only once per song change, no matter if previous song was skipped or naturally finished. And current version of on_play in my case resulted in broken state transition and ruined rating and play counts 
So, I've made minor changes, which in my believe respects both cases.

mpdstats: More general approach to multiple on_play calls for the same song

---

test/rsrc/convert_stub.py

See https://github.com/beetbox/beets/pull/2403#issuecomment-274358494. This makes `convert_stub.py` work on any Python at all, 2.x or 3.x, whether the beets dependencies are installed or not.

Remove dependencies from convert_stub.py

---

docs/reference/config.rst

`When a match is above the *medium* recommendation threshold`
->
`When a match is below the *medium* recommendation threshold`
As discussed in issue #2410, which is fixed by this edit.

Update config.rst: see issue #2410

---

beetsplug/fetchart.py
test/test_art.py

When I restructured some of fetchart some time ago, I introduced the `extra` dictionary to pass around settings. In hindsight, this appears rather ugly and unnecessary, since it only duplicates attributes of the plugin object without any further processing. The `paths` that were included in this dictionary are the only exception. A separation between global settings and album-specific data seems sensible, though.
At least I couldn't remember any valid reason for the dictionary approach when looking at the code a few day ago..

fetchart: Clean-up data structures

---

beets/ui/commands.py
docs/changelog.rst
docs/guides/tagger.rst
docs/reference/cli.rst

Adding a 'move' option to the importer's CLI.

---

beetsplug/badfiles.py
docs/changelog.rst
docs/plugins/badfiles.rst

Per request from #1654.
As a continuation to the discussion on the change: I think it would make sense to have a separate option for displaying all checker results (including the positive ones) with only bad files being displayed by default. The reason for having that, instead of logging the results for the uncorrupted files at the debug level, is that using this option the user would be able to see the results for all of the files without seeing a bunch of other debug messages, making the output less messy. The option could be named --all or --show-all, in order to be distinguished from the global --verbose.
This is just a suggestion, though. Let me know if you'd rather have the positive checker results be logged on the debug level, instead of introducing this new option.

badfiles: displaying results only for corrupted files by default

---

beetsplug/badfiles.py
docs/changelog.rst

badfiles: continue execution to other files instead of stopping after a checker error

---

beets/config_default.yaml
beets/importer.py
beets/library.py
beets/util/__init__.py
beetsplug/importadded.py
docs/dev/plugins.rst
docs/reference/config.rst
test/_common.py
test/test_files.py
test/test_importadded.py
test/test_importer.py
test/test_mediafile_edge.py

This PR adds an option to hardlink files when importing, similar to the existing `link` option that enables symlinks.  Tests in the same style as the symlink tests are included.
```yaml
import:
write: no
hardlink: yes
```

Add option to hardlink when importing

---

beetsplug/discogs.py
docs/plugins/discogs.rst

The official OAuth authentication seems to have broken, so allow usage
of simple configuration instead.
See-Also: https://github.com/discogs/discogs_client/issues/78
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

discogs: support simple auth.

---

beets/__main__.py
beets/ui/__init__.py
docs/changelog.rst

add main file for module. with this program can be run from module. e.g. `python -m beets`. but this require fix on `SubcommandOption`, because it will print `__main__.py` instead of program name. so i add another method to inherit parent class and add exception for that word.
i don't know how to test this with unittest, but if threre is introduction for testing this program, that would be helpful and i will add another commit for test.
python version: Python 3.5.2+ 
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety

chg: dev: add main module.

---

beetsplug/mbsubmit.py

As it says on the tin, single line change to mbsync so that tracklists end up sorted. This is important because track order is different from track number in musicbrainz, so an incorrectly sorted list is semantically meaningful to the musicbrainz track parser.
Before, running on https://musicbrainz.org/release/3b4a35f9-6a8d-4715-a8bf-f30e8e2b0f0a :
```
16. True to Yourself - John Barera (6:44)
02. Triple Treat - Brame & Hamo (5:33)
10. Inch of Light - Downtown Party Network (7:05)
05. That Same Thing - Loz Goddard (6:02)
01. The Schrew - Laurence Guy & Harry Wolfman (7:56)
06. Pleister - Homework (5:07)
09. Dizzy Talks - Kito Jempere (5:52)
11. Tieflicht - Kyodai (8:16)
14. Maybe One Day We Can Be Friends - Edit Murphy (5:00)
08. Let Me Show You the City - Ponty Mython (5:46)
03. Catch Up …
```

mbsubmit plugin : numeric sort in print_tracks (for >=10 track releases)

---

beetsplug/kodiupdate.py
docs/plugins/index.rst
docs/plugins/kodiupdate.rst

I created one for an older version before, but it didn't work since the change to Python 3. So I created a new one that works.

Add a plugin to update a Kodi music library

---

beets/ui/__init__.py
docs/changelog.rst

As explained in #2393, the last big issue in Python 3 is that `print` or `sys.stdout.write` can crash depending on the system's locale configuration. This change restores the Python 2 behavior, which avoids potential crashes by (a) using the `replace` error handler and (b) allowing the user to override the stdout encoding in the configuration.
Unfortunately, this breaks out test harnesses that capture stdout. One way to work around this might be to detect when we're in a test harness and just record the text strings directly.

On Python 3, use more flexible encoding to send bytes to stdout

---

beetsplug/smartplaylist.py

The idea is to let different smart playlist definitions add songs to the same concrete playlist. See http://discourse.beets.io/t/beets-path-handling-for-delimited-fields/44 for discussion.

smartplaylist: Support overlapping playlist defs

---

beetsplug/missing.py
docs/plugins/missing.rst

Passing the `-a` flag shows, for each artist in the library, the albums by that artist which are not in the library.
Also includes a minor enhancement to allow `beets.ui.print_` to print to `stderr`.
Example output (truncated):
```
(venv) user@host ~/d/p/beets> beet missing -a
Theorem - Fallout
Theorem - Shift
Theorem - Day From Hell
Theorem - Mantra One
Theorem - Embed
Theorem - Cinder
Theorem - [untitled]
Theorem - Nano
Theorem - Recoil
Theorem - Break in at Apartment 205
Theorem - Intervals
Theorem - THX: Experiments in Synchronicity
Tinariwen - Amassakoul
Tinariwen - Aman Iman : L'eau c'est la vie
Tinariwen - Aman Iman: Water Is Life
Tinariwen - The Radio Tisdas Sessions
Tinariwen - Imidiwan: Companions
Tinariwen - Tassili
[!] No musicbrainz ID for artist she, skipping.
Carbon Based …
```

Add ability for 'missing' plugin to show missing albums by library artists

---

beetsplug/web/__init__.py
beetsplug/web/static/beets.js
beetsplug/web/templates/index.html
docs/changelog.rst
docs/plugins/web.rst

Support for reverse-proxying the web plugin under a given directory was requested  a few times like in #282 and  #755 and #2287 but was never actually fixed. I built upon  @WyseNynja PR #2287 and well... here it is.

Reverse proxy support

---

beetsplug/convert.py

FFmpeg's native aac encoder was declared stable in 3.0 (Feb 15. 2016).
Support for libfaac was removed some time later:
http://git.videolan.org/?p=ffmpeg.git;a=commit;h=dc0f711459e0c682bf9f94ba38d26736e90cff45

Change default aac encoder to FFmpeg's native one

---

beets/importer.py
docs/changelog.rst

Don't stop collapsing paths when iterating over subdirectories of
already collapsed paths.
Fixes #2493

Fix import of multidisc releases with subdirectories

---

beets/config_default.yaml
beets/ui/commands.py
docs/changelog.rst
docs/reference/config.rst

Added a terminal bell if interaction from the user is required, according to this issue: https://github.com/beetbox/beets/issues/2366

---

beets/ui/__init__.py

Pointed out in #2490, this is a regression introduced by #2398. We need to flush the buffer to faithfully emulate the "real" print() function.

Flush the stdout buffer after printing a line

---

test/test_convert.py

On a system with dependencies installed for python3 but not for python2,
we have to make sure python3 is used everywhere since 'python' might be running
the python2 interpreter.
This helps with some problems in #2400, but doesn't fix the issue completely.

Run python2 or python3 depending on what's being used

---

beetsplug/beatport.py

The 4th argument of `re.sub()` is maximum number of substitutions, not flags.
Found using [pydiatra](https://github.com/jwilk/pydiatra).

Fix misuse of flags in re.sub() calls

---

beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst

Also updated changelog and docs.
Resolves: #549

Add default replace for - to _

---

beets/dbcore/db.py
beets/ui/__init__.py
docs/changelog.rst

OperationalError from SQlite that indicates a permissions problem.

---

beets/dbcore/query.py
test/test_datequery.py
test/test_query.py

This pull request is for issue #2513 (Date-valued field queries allow non-date values).
`Period.parse()` now raises a `InvalidQueryArgumentTypeError` when the string does not parse to a date - although I do wonder whether this is the correct error to raise, as I'm not comparing types here. I wonder whether a `ValueError`, or perhaps creating a new `InvalidQueryArgumentValueError` is more appropriate?
I have changed the way `Period.parse()` works - it used to first count the number of hyphens in the date to determine the precision (day, month, or year) and then try to parse the string against the appropriate date format. This did work fine. However, in anticipation of new feature #2506 (Extend the query date parser with (optional) times), where we will have '-', ':', and possibly ' ' or …

Date value field validation

---

beetsplug/absubmit.py

The value of `ENOENT` is architecture-dependent, so don't assume it's always 2.
Found using [pydiatra](https://github.com/jwilk/pydiatra).

Don't hardcode errno constant

---

beets/util/__init__.py
docs/changelog.rst

This should fix #2488 where some commands, mainly `beet convert` would prevent further inputs.
I've been running with the solution proposed by @sampsyo for some time now and I believe it does indeed suppress this behaviour.
@jansol, could you confirm this fixes problems on your end as well?
I don't know how to test for this however.

Close stdin when performing `command_output()`

---

beetsplug/lyrics.py
test/rsrc/lyricstext.yaml
test/test_lyrics.py

This PR goal is to check that the different backends (and every site registered as source for the Google backend) work as expected.
[Some old code](https://github.com/beetbox/beets/blob/master/test/test_lyrics.py#L197) was supposed to do that in the tests but was never executed as it required some files on the filesystem that were never there.
Because these tests don't mock the fetching part, they are more integration tests than unit tests and should not be executed by default. A `skipUnless` decorator is applied requiring an environment variable to be set explicitely for the tests to be executed.
Here are the results (we should take some actions concerning the state of the default backends) :
**Default plugin backends :** 
Only LyricsWiki and musixmatch pass the tests. 
**Google backend …

Tests to track whether lyrics websites are correctly fetched

---

docs/changelog.rst
docs/plugins/fetchart.rst

The package is inactive and has been broken for months: https://github.com/beetbox/beets/issues/2371
Fixes https://github.com/beetbox/beets/issues/1610
Alternatively, could be rephrased to say it doesn't work with py3 (if that's the only condition), but I think that would cause even more confusion if there isn't a workaround

Remove mention of python-itunes

---

beetsplug/web/__init__.py

Looks to solve #2532 by decoding any bytes objects to strings.
I'm not as familiar with the iterable constructs in Python, but I think that I came up with a reasonable solution. I'm open to learning a better way to do this if there is one.

web: #2532 - Decode bytes values to strings

---

beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst
test/test_lyrics.py

Address #2548 by dropping the backend as I see no solution to get from (artist, title) to the magic number used in the url.

Drop lyrics.com backend

---

beets/util/confit.py
docs/changelog.rst

This lets the YAML library itself deal with the encoding (mostly), which should address issues having to do with `open` giving us a system-specific encoding by default on Python 3 on Windows when the files should have been written using UTF-8 per the YAML standard.
Fixes #2456; fixes #2565.

Load YAML as binary data

---

docs/plugins/convert.rst

Document gapless mp3 encoding.

---

beets/autotag/mb.py
beetsplug/mbcollection.py

Added functionality to retrieve secondary album tags from Musicbrainz and add all tags as a comma separated string (with primary tag as first value)
Also fixed a small typo.

Fixed #2200 and a small typo

---

beetsplug/gmusic.py
docs/plugins/gmusic.rst
docs/plugins/index.rst

Here is @owcz requested implementation of Google Music plugin (beetbox#2553). Plugin is able to search and upload tracks to GM library. Options and arguments are specified in the doc file.

Add Google Music plugin

---

beetsplug/metasync/amarok.py

This fixes issue #2595 by using quoteattr() instead of escape()

do not quote the value in xml, use quoteattr to add quotes as needed

---

beets/dbcore/db.py
beets/library.py
test/test_dbcore.py
test/test_ipfs.py
test/test_query.py

This came out of an attempt to address the mysterious testing problems from #2563 and turned into a big old debacle. As it turns out, the problem came from calling Item.from_path and getting None for fields that weren't filled out by the MediaFile data. Everywhere else, we fill out these fixed attributes with the special null value for the field's type, so it's actually pretty confusing that these could mysteriously become None. I think it will be saner all around if we enforce this universally.
There were two possible fixes: one in `__getitem__` to check for missing values and one that set all the missing values in the constructor. I opted for the former because it has a smaller footprint, but the latter might have slightly better performance (depending on the ratio of constructions to …

Always use specific null values for fixed fields

---

beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst

Here's another crazy idea: how about printing lyrics in a usable
format? Here, `lyrics -p` on the whole library just dumps a
concatenation of all lyrics, which is not very useful.
I was thinking of improving the output a little, maybe by adding HTML
tags or some form of markup. this pull request does exactly that,
although rather crudely: the resulting output is probably not valid
HTML (it's just snippets) and embeds the lyrics in `<pre>` tags (as
opposed to trying to format them correctly).
the output is, of course, not an ebook in any way, although it could
be used to construct an ebook or other things.
comments? other ideas? suggestions?
i figured it was better to implement this directly in beets instead of
hacking at the sqlite database on the side...

print lyrics as HTML

---

beetsplug/lyrics.py
test/test_lyrics.py

a few issues were discovered in https://github.com/beetbox/beets/pull/2628#issuecomment-315792892:
1. a newline is missing after the lyrics block, which generates a warning for every song (!!) when the resulting rst is built
2. the last commit, which aimed at fixing some :index: directive that were not rendered correctly, doesn't seem to be working here, and may introduce overwrite between differently named artists that end up with the same "slug"
this introduces a new local function named `slug` which overlaps with the already existing `slugify` function. the code was taken in part from [this stack overflow discussion](https://stackoverflow.com/a/8366771/1174784) which explains how the `NKFD` approach used by the `slugify` function is actually incorrect. For example, `NKFD` will do this: …

improvements and fixes to the lyrics RST rendering

---

beetsplug/lyrics.py
docs/changelog.rst

we just look for the bad string in the HTML. this has the downside
that we may consider songs that have those exact lyrics (you never
know, really) may trigger this warning as well and we would fail to
fetch those songs.
we also fail if lyrics contain another magic string that seems to come
up when you do fill in the CAPTCHA after being blocked.
for an example of error messages in songs, I suggest listening to the
excellent "Retry? Abort? Ignore?" from the band called "Martyr".
this is to fix #2632, obviously.

lyrics: detect MusixMatch blocking

---

beets/ui/__init__.py
docs/changelog.rst

For some reason Python always warns about a `BrokenPipeError` on
`stderr` even if it is caught.
This should fix #2622 and seems pretty harmless, since `stderr` is systematically flushed by other error messages.
@Azphreal , could we get some feedback from your end before merging?

Do not warn about a BrokenPipeError we do consider - Fix #2622

---

beetsplug/edit.py
docs/changelog.rst

There seems to be a bug in the edit plugin when re-importing (`beet import -L`) items that are in the library already:
As can be seen in the diff, the plugin assigns temporary `id`s to the items to be edited (presumably for applying the changes to the correct obejct in `EditPlugin.apply_data` or because some function deeper in the guts of beets requires a non-`None` id). This doesn't really cause any problems if none of the items is in the database: `EditPlugin.edit_objects` will create a `deepcopy` for any object with a false-y `Item._db` and hand that to `beets.ui.show_model_changes`.
If however `Item._db` is set, `EditPlugin.edit_objects` will provide `None` as the old object to `beets.ui.show_model_changes` which will in turn query the database with the (invalid temporary!) `id` of …

Fix the edit plugin displaying bogus data or even crashing on re-imports

---

beetsplug/kodiupdate.py
docs/changelog.rst

The most important aspect of this change is to correct the Kodi URL. The current URL, which has a trailing slash, produces a 404 error on my system (Kodi v17.1 on ArchLinux).
The existing error handling/logging missed this, so I added checks of the HTTP status code and the JSON response data for more detailed information.

Fix kodiupdate URL and add better error reporting

---

beets/dbcore/db.py
beets/library.py
docs/changelog.rst
test/_common.py
test/helper.py
test/test_edit.py

As per #2664, the `Item.mtime` is reset for any assignment to `MediaFile`-backed fields, even if the `Item`s fields and the file's tags do not go out of sync (i.e. if the previous value is reassigned). This happens frequently in the `edit` plugin. While the effects are not devastating, it's certainly not ideal when using the plugin with coarse queries and only changing few items in the editor.
In fact, `test.test_edit` already had a method to check that these superfluous tag writes didn't happen. It didn't really check this, though, since the `mtime` for test fixtures would always be 0 to begin with. An "`mtime` reset" would therefore not `_dirty` the `Item`, and the plugin would in turn not write the tags out: In a real-world setting with non-zero `mtime`, these writes did happen.
Some …

Mtime fixes

---

beets/dbcore/db.py
beetsplug/edit.py
test/test_edit.py

Contains two fixes:
- Turns out I introduced a regression in #2659 due to incorrectly assuming objects to have a valid `id` when `object._db` is set. Crashed beets when re-tagging albums (since the yaml file would contain `id: ''` which can obviously not be coerced to an integer)
- The plugin shows diffs against different initial states in first and subsequent edits, see the commit message for more detail.

Edit plugin logic: Regression from previous PR; incorrect diffs

---

beetsplug/mbcollection.py
docs/changelog.rst
docs/plugins/mbcollection.rst

For those of us who have multiple MusicBrainz collections I've added support for specifying which collection you'd like to use.
In the future I'd like to add support for multiple collections updated via queries (in the vein of the smartplaylist plugin).

mbcollection: Support specifiying collection ID.

---

beets/importer.py
beets/library.py
beets/ui/commands.py
beets/util/__init__.py
beetsplug/duplicates.py
docs/changelog.rst
setup.cfg
test/helper.py
test/test_files.py
test/test_ui.py

The move functions in library.py and manipule_files in importer.py where
changed to use a single parameter for the file operation instead of
multiple boolean flags.
A typo in the documentation of the Album.move and Item.move functions
confusing True and False when describing the store parameter was fixed
as well.

Refactored move functions for clarity according to #2682

---

beetsplug/mbcollection.py
docs/changelog.rst
docs/plugins/mbcollection.rst

Add a new ``mbcollection.remove`` configuration option (default: None) and a new ``-r`` (``--remove``) flag which removes albums from collections that are no longer present in the beets database.
The ``-r`` flag takes precedence over the ``remove`` configuration option.

mbcollection: Add support from removing albums.

---

beetsplug/duplicates.py
docs/changelog.rst

During a refactoring, the "dest='keys'" parameter was lost. This caused
the option to not have any effect.

Fix the --key option in the `duplicates` plugin.

---

docs/plugins/bpd.rst

The GStreamer base plugins are required to run bpd; if they are not installed, bpd quits with
> error: Could not create playbin
This commit also deletes an unused link from the documentation.

Update GStreamer installation instructions for Mac OS X.

---

beetsplug/play.py

Now relative_to setting in play plugin is respected when searching by albums.
Small tweak, but my mpd likes it a lot :)

[Play plugin]Respect relative paths when using albums

---

beetsplug/replaygain.py
docs/changelog.rst

Calling this WIP, as I'm not exactly sure what I'm doing.
We have an unlink here, so it makes sense that after we are done changing the location we link it back up.
The set_state I assume tell gstreamer that we are ready to continue. Setting PLAYING directly locks up the pipeline, so I assume it's not in READY state already at that point. So we set it to READY first, and then continue with PLAYING.
Modeled the solution after a stackoverflow post I found here https://stackoverflow.com/questions/4712266/gstreamer-pausing-resuming-video-in-rtp-streams/7771723#7771723
Fixes #2636

Fix album replaygain calculation with gstreamer backend

---

beetsplug/mpdstats.py
docs/changelog.rst

Fixes an issue where mpdstats won't update play/skip counts of a song when MPD switches from the song to an internet stream. Also updates play counts for a song being played consecutively.

mpdstats: update stats when switching from song to stream and when playing a song consecutively 

---

.travis.yml

`2.7_with_system_site_packages` uses a four-year-old Python 2.7.6.
This allows the latest version of pylast which supports Python 2.7.10+ as older versions don't have good HTTPS support.
Re: https://github.com/pylast/pylast/issues/201.

Use 2.7.13 instead of 2.7_with_system_site_packages

---

beetsplug/fetchart.py
docs/changelog.rst

This is a tentative fix for issue #2734 , based on the suggestion in https://github.com/beetbox/beets/issues/2734#issuecomment-341888432
I've tested it and it fixes the problem for me, but I'm not sure if other changes are required for a complete solution, since my knowledge of the code base is very limited. Please review!

Tentative fix for issue 2734: also check for RETAG

---

beets/importer.py
beets/ui/commands.py
docs/guides/tagger.rst
docs/reference/config.rst
test/helper.py
test/test_importer.py

Fixes #112
Would removing the album before running the merge task make sense? This code seems to work now
but I think it gives problems when reimporting library with existing duplicate albums. The tests don't fail though.

Implement album merging for duplicates

---

beets/mediafile.py
docs/changelog.rst
test/test_mediafile_edge.py

The regex «[\+-]?[0-9]*» possibly matches a single minus/plus, which was then
passed on to int, raising a ValueError from within _safe_cast. The test suite
covered this for float, but not for int.
We now make sure we actually have a number after the sign by using a Kleene
plus.

mediafile._safe_cast: be safer when converting to int

---

beetsplug/hook.py
docs/changelog.rst

This is a simple fix for #2740 that catches an AttributeError if the value returned by convert_field() doesn't have a decode() method.

Addresses hook.py ability to handle non-string item properties

---

docs/guides/main.rst

As an alternative to #2728, this mentions the need to back up your music before importing stuff. This wording fits better with the style of the rest of the guide. I'd be interested to hear feedback on how to word this.

Mention backups in the main guide

---

beetsplug/convert.py
docs/changelog.rst
docs/plugins/convert.rst

Addresses #2732. I changed the name from `noconvert` to a more intuitive `dont_convert` which I think falls better in-line with the other options of the convert plugin (i.e. `never_convert_lossy_files`).

Convert Plugin: Added dont_convert Option

---

beetsplug/acousticbrainz.py
docs/changelog.rst
docs/plugins/acousticbrainz.rst

The acousticbrainz plugin pulls a lot of information from the database.
However, some people (me) might want to only apply some of the tags from acousticbrainz to our files, either because we want to avoid conflicts with tags from other sources, or because we know we won't use them and like to keep things neat and tidy.
Add a new tags configuration option to the plugin, which allows you to specify a list of tags to write to your files. The default is still to apply all available tags.

Add tags configuration to acousticbrainz plugin

---

beetsplug/duplicates.py
docs/changelog.rst

At present, if tiebreak is specified to give keys for the order of priority in determining duplicates, it must be specified for both items and albums, or an error will be raised when the unspecified one is used.  This is particularly bad because the default order of priority appears to be impossible to specify in tiebreak, so if the user wants (as in my case) a tiebreak specification for items, and the default order for albums, this is impossible.
This small change makes it so that tiebreak is only used if it specifies keys for ordering the kind (track/album) being considered; otherwise, the default is used.

Duplicates plugin: tiebreak album vs items fix

---

beets/config_default.yaml
beets/importer.py
beets/library.py
beets/ui/commands.py
docs/reference/cli.rst
docs/reference/config.rst
test/test_importer.py

Okay well, I asked for advice in #934, but I accidentally implemented it before getting an answer. Whoops!
Feel free to criticize style, implementation details, naming, tests/lack thereof, etc.

Implement from_scratch option

---

beets/util/artresizer.py
docs/changelog.rst

Hello,
I'm looking to get started contributing to beets with this simple pull request :)
Regarding the Windows caret (`^`) escaping issue, it seems that this is only an issue if we launch ImageMagick by cmd.exe. We instead launch using `CreateProcess()` on Windows.
In calling `CreateProcess()`, Python takes no special actions for neither `^` nor `>`, as referenced [here](https://docs.python.org/2/library/subprocess.html#converting-argument-sequence)
Because Windows uses strings, not arrays, to pass argv to processes, further command line parsing still happens inside the called process (i.e. escapes are still parsed even when called using CreateProcess()) and this behaviour seems dependent entirely on the compiler used. However, it seems that the caret (`^`) is not one of those escapes …

Remove unnecessary escape caret in ImageMagick convert argument

---

beetsplug/fromfilename.py
docs/changelog.rst

Don't ignore anymore filenames such as "01.mp3", instead use the number
in the filename as track number.

First tentative fix for issue 2738.

---

beets/autotag/mb.py
docs/changelog.rst
test/test_mb.py

Some releases have non-audio media, such as CD+DVD or CD+DVD-Video. Skip
these media when fetching album info as they will never match audio
tracks and will always report missing tracks.
I took the naive approach of cherry-picking a list of media suspected to
not contain audio from the MusicBrainz formats list:
https://musicbrainz.org/doc/Release/Format

Fixes #2688: Skip non-audio media from MusicBrainz

---

beets/autotag/mb.py
beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst
test/test_mb.py

This ignores non-audio tracks during import:
- Data tracks, based on their title `[data track]` (which seems to be
the MusicBrainz convention, as there's no specific flag to indicate
that a track is a data one),
- Video tracks, based on the `video=true` attribute.
It's similar to the Picard changes mentioned in #1210, except it doesn't
deal with `[silence]` tracks: These ones will probably require a setting
to let the user control if they should be imported or not.

Fixes #1210: Skip non-audio tracks from MusicBrainz

---

beets/autotag/mb.py
beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst
test/test_mb.py

This is related to #2688 where a list of hard-coded non-audio formats to
ignore has been added. Some users may want to rip the audio portion of
video tracks (e.g. DVD-Video) so it would be beneficial to let them
control exactly which formats to ignore.
I added a `ignored_formats` setting for that purpose and moved the
hard-coded list into the config. Test and documentation have been
updated accordingly.
Aside: I also clarified the changelog a bit regarding this change and
the related one for #1210.

Added a setting to control which formats are ignored

---

beets/config_default.yaml
beets/importer.py
docs/changelog.rst
docs/reference/config.rst

This pull request implements the configuration option `incremental_skip_later`, which changes the skip behaviour to bypass recording skipped items to the incremental list, allowing them to be revisited later on.
The configuration option defaults to current behaviour.
Issue #2773

New importer option incremental_skip_later, fixes #2773

---

docs/guides/advanced.rst

Tomahawk is abandoned according to the GitHub README.md. Suggest removing the reference to using it with Beets library.

Remove reference to Tomahawk player in advanced.rst

---

beets/ui/commands.py

Should fix #2441.
The problem in that bug is that the `rec` and `candidates` produced by subsequent actions, like manual searching, were just kept in local variables instead of assigning them on the `ImportTask` object. That meant that plugins and such could not inspect these new candidates; they only saw the old ones (if they existed).
I'm not sure how wide-ranging the effects of this change will be, so some thorough testing here would be greatly appreciated!

Modify task recommendation and candidates

---

beetsplug/importadded.py

Change the registered listeners.

Fix #1918: ValueError on trying to import

---

beetsplug/plexupdate.py

Added Plex token redaction for plexupdate plugin.  For use with `beet config` sharing.

PlexUpdate: token redacted

---

beets/ui/commands.py

This is to address #2793, where, on Python 3 under a limited locale, the path arguments to the `import` command can have surrogate escapes in them. This converts these `str` arguments to the standard beets representation for paths, which is `bytes` values.
I wasn't able to reproduce the problem on my machine, but I'm pretty sure this is the right fix.

Use import argument paths as bytestrings on Python 3

---

beets/importer.py
beets/plugins.py
beetsplug/convert.py
docs/changelog.rst
docs/dev/plugins.rst

This is a bug report together with a PR because I like to scratch my own itch :)
Something has been bugging me for quite some time after switching to Opus - some of the albums I've imported didn't have replaygain calculated, even though the replaygain plugin did definitely run. After lots of debugging the issue seems to be as follows:
1. User tries to import a FLAC album
2. Since the plugins don't run in a deterministic order (as far as I've noticed), ReplayGain is sometimes calculated on the FLAC files
3. Files get converted to Opus
4. There are ReplayGain values calculated from FLAC but Opus only takes R128
5. The imported files need to have `replaygain` calculated again, manually
I've added a (quite ugly) hack to always convert the file first, which from my testing seems to reliably …

Early stage pipeline plugin functions

---

beets/autotag/mb.py
docs/changelog.rst

Previously, release events were selected based on the order that MusicBrainz listed them rather than the order defined in config.yaml.
Opening this as a pull request instead of pushing directly because this _may_* cause large metadata changes the next time someone runs `beet mbsync`. But it should _improve_ the metadata, making it align better with a user's preferred countries.
\* I ran this over my entire collection of around 4000 albums and it changed only eight.

Make sure release events are selected in preferred order.

---

beets/plugins.py
beets/util/confit.py
beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst

As per the discussion in #2733, this is my take on a revised fetchart configuration syntax. To give a few examples, all of the following are valid and should do the expected:
```yaml
fetchart:
sources:
- filesystem
- coverart:  release
- itunes
- amazon
- albumart
- coverart: releasegroup
```
```yaml
fetchart:
sources:
- filesystem
- coverart:  releasegroup
- itunes
- '*'
```
```yaml
fetchart:
sources:
- filesystem
- coverart:  releasegroup release
- itunes
- '*'
```
and also any old configuration in the following style
```yaml
fetchart:
sources: filesystem coverart itunes *
```
I'm not entirely satisfied with how to the parsing turned out, since it did require quite a bit of code. I think the whole thing should make for a pretty future-proof syntax at least.
@samuelnilsson: Would you …

Fetchart fine-grained source configuration (alternative to #2733)

---

beetsplug/web/static/beets.js
docs/changelog.rst

Round was used instead of floor, so the minute counter jumped after each 30 seconds

Fix jumping time in beets.js

---

beetsplug/web/__init__.py
docs/changelog.rst
docs/plugins/web.rst

If the web plugin is behind a credential based http server and is
accessed by another in-browser client in another domain, the
specification of CORS requires the server to indicate it supports
such credentials.

Add a support for supports_credentials

---

beetsplug/web/__init__.py
docs/changelog.rst

flask.send_file() expects a string, g.lib.get_album() returns bytes. Added decode() to album_art(). 
If g.lib.get_album() gets a non-existing id, it returns None. Python would throw an error in this case. Added check to prevent this.

Fix album_art() in __init__.py

---

beets/ui/commands.py
beets/ui/completion_base.sh

This patch avoids errors during completion when a plugin
uses names like "sub-command". It does not make completion
fully working for such commands though, thus no close.

Partial fix for cmd names with dashes (ref #2836)

---

beetsplug/replaygain.py
docs/changelog.rst

Really fix album replaygain calculation with gstreamer backend.

---

beetsplug/discogs.py
docs/changelog.rst
test/test_discogs.py

Fix incorrect split of a tracklist by medium for the case of
two-sided mediums (#2887).
Following the discussion in #2887, the 'medium_total' value should
contain the number of tracks on the medium to which each particular
track belongs, not the total number of different mediums present on
a release.
Fix unit tests accordingly.

Some fixes and updates for the Discogs plugin

---

beets/util/artresizer.py

Release v0.6.1 of `pep8-naming` now detects that `Shareable` in `beets/util/artresizer.py` is a metaclass. The first argument of each class method should then named be `cls` instead of `self`.

Fix coding style: `Shareable` is a metaclass.

---

beetsplug/mbsync.py
docs/changelog.rst
test/helper.py
test/test_mbsync.py

Hi! This fixes #1234, as it allows the `mbsync` plugin to follow recording MBID changes. It falls back to the old mechanism when items in the library do not yet have an `mb_releasetrackid` field.

mbsync: Map tracks using release track MBIDs instead of recording MBIDs

---

beets/autotag/hooks.py
docs/changelog.rst
test/test_mbsync.py

Fixes #2921, and adds a test case to hopefully help future refactors of autotag.hooks not break mbsync events.
I don't think completely removing `@plugins.notify_info_yielded` is the right thing here, it works really well for `album_candidates`/`item_candidates`.

Send albuminfo_received / trackinfo_received when running mbsync

---

beetsplug/mbsync.py
docs/changelog.rst

MBID of recording could become invalid after merging. The existing
code always copies metadata from first track after updating. But for
albums with invalid track MBID that happens to be the first track,
MusicBrainz changes won't be applied to whole album, only whose
tracks with valid MBID. This is particularly annoying since those
changes are actually displayed for every `beet mbsync` run, but never
get applied.
Fix this issue by finding any track that get MusicBrainz updates, and
apply it to whole album.
Some additional comments:
1. While #2917 seems being able to solve `beet mbsync` issues in long term. It still can't handle existing collection with invalid track MBID. Since those tracks won't receive any updates (including `mb_release_trackid`), and becomes "zombie". This pull request …

mbsync: fix updating album with invalid first track MBID

---

beets/ui/commands.py

As per suggestion from: <https://discourse.beets.io/t/created-plugin-find-release-from-barcode/366/8>

Add catalognumber to disambiguation string (when selecting candidates)

---

beetsplug/play.py
docs/changelog.rst
docs/plugins/play.rst

Closes #2944 
I've never written tests before, and I didn't want to break anything too bad.  
I'm now using the modified `play.py` on my local machine and it works well.
This is my first time contributing code as well, please tell me if I did anything wrong.

Add ability for play plugin to emit utf8 BOM

---

beets/util/confit.py

The test `test_ui.ConfigTest.test_command_line_option_relative_to_working_dir` was failing on my system but, for some odd reason, not on Travis nor AppVeyor. The test fails because it changes working directories before the relative lazy-loaded default configuration path is resolved, later causing a `beets.util.confit.NotFoundError: musicbrainz.host not found` error. Unfortunately, the pkgutil loader returns `../beets/__init__.py` as the path to the default configuration source and 99% of the time this resolves because the working directory doesn't change.
I made a small change to the `LazyConfig` class to pre-resolve this path so that it can be lazy-loaded after a working directory change.

pre-resolve package path for lazy-load configuration

---

beetsplug/lastgenre/__init__.py
docs/changelog.rst
test/test_lastgenre.py

```sh
$ beet lastgenre LITE Cubic
lastgenre: genre for album LITE - Cubic (None):
```
```sh
$ # without lastgenre.canonical
$ beet lastgenre LITE Cubic
lastgenre: genre for album LITE - Cubic (artist): Post-Rock, Math Rock
$ # compare: with lastgenre.canonical
$ beet lastgenre LITE Cubic
lastgenre: genre for album LITE - Cubic (artist): Post-Rock, Math Rock, Alternative Rock, Rock
```
I.e. it prefers the more specific genres using the canonicalization tree without actually canonicalizing the genres. That seems to fit what `prefer_specific: yes` `canonical: no` implies.
This should fix #2973 (with the alternative solution described there).
I have possibly violated every coding convention on earth, so please tell me what I should change.

lastgenre prefer specific without canonical (#2973)

---

beetsplug/web/__init__.py

Per the [Flask Documentation](http://flask.pocoo.org/docs/1.0/upgrading/#extension-imports):
> ## Extension imports
> 
> Extension imports of the form flask.ext.foo are deprecated, you should use flask_foo.
> 
> The old form still works, but Flask will issue a flask.exthook.ExtDeprecationWarning for each extension you import the old way. We also provide a migration utility called flask-ext-migrate that is supposed to automatically rewrite your imports for this.
This changes the CORS import from the deprecated form to the preferred form.
Issue #2979

changed flask cors import

---

docs/plugins/index.rst

I was going through my tickets and found one about adding mStream to the beets docs.  Figured I should finally follow up on that.  There was an old pull request that was mysteriously failing, so I decided to create a new one
https://github.com/beetbox/beets/pull/2788

Add mStream to the Docs

---

beetsplug/gmusic.py
docs/changelog.rst
docs/plugins/gmusic.rst

Implemented the import_stages def on gmusic and updated the docs
#2997

Adding gmusic ability to upload on import

---

beetsplug/gmusic.py
docs/changelog.rst
docs/plugins/gmusic.rst

`gmusicapi` auth uses the MAC address to "register" in Google's service. Running `beet gmusic-upload` will fail if you use beets on multiple machines because too many MAC addresses will be registered. The fix it to be able to use the same MAC address (and `device_id` for searching) for all of the machines.
Allow custom `uploader_id` to not reach maximum amount of registered devices. This field should be in the format of a MAC address.
From `gmusicapi` method docstring: [Link](https://github.com/simon-weber/gmusicapi/blob/1be1e0b461ae78ac5f1c504ab3387472e82e813e/gmusicapi/clients/musicmanager.py#L163)
```
There are hard limits on how many upload devices can be registered; refer to `Google's
docs <http://support.google.com/googleplay/bin/answer.py?hl=en&answer=1230356>`__. There
have been …
```

Add uploader_id, uploader_name, and device_id for gmusicapi auth in gmusic plugin

---

beetsplug/absubmit.py
docs/changelog.rst

Parallelize absubmit

---

beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst

This is a tentative at addressing #2551 . For the moment this is very much a work in progress, but I would like to discuss some points.
For the moment I took python-itunes from @ocelma, stripped it of some unnecessary stuff and fixed some stuff to make python3 compatible.
Open questions are:
* Place in the beetbox universe: I do not really see us maintaining this for anyone's else purpose than ours. I would like to strip the code down even more so that it is as as simple and minimalistic as required to fetch the images, nothing else. Keeping it inside beets gives us some more freedom in terms of interface.
* Licensing/recognition: python-itunes is GPL. I removed all the comments at the top of the file for the moment, but only to be able to remove clutter, for my own sanity when reading …

fetchart: Restore iTunes Store source

---

beetsplug/gmusic.py
docs/plugins/gmusic.rst

Currently, if the `gmusic` plugin is used, any command ran with beets will run the `gmusicapi` oauth authentication even if it has nothing related to `gmusic`.
**Example**, using command "ls" triggers the auth (every command does, including "web"):
**Fixed example**, "ls" command does not trigger auth, but using one of the gmusic commands does:

gmusic plugin fixes and additions

---

beets/ui/__init__.py
docs/changelog.rst

when beets is started and the database file is on e.g. a volume that is full beets quits with the message "database file could not be opened {path to file}". The original error message coming from sqlite is lost. the proposed patch attaches the original error as 'reason'. in the case of disk full it reads now "database file {path to file} could not be opened, reason: database or disk is full"
I have no idea how to create a test for it, because the test case either depends on a not-writeable database file or on a mock of sqlite

Improve error messages in case of sqlite errors

---

beetsplug/replaygain.py
docs/changelog.rst

this fixes  the first half of #3008 - the peak calculation, 
calculating the albumgain is still wrong

replaygain: albumpeak on large collections is calculated as average,not maximum (bug 3008)

---

beetsplug/chroma.py
docs/changelog.rst

Allow releases from Acoustid lookup to be sorted by date/country
#3017

chroma: Bias toward looking up more relevant releases using date/country

---

beets/autotag/mb.py
beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst
test/test_mb.py

https://github.com/beetbox/beets/pull/1638 by @jdetrey changed the importer to take data tracks into imports. This adds a configuration option to disable that feature.
I'm proposing adding this since it seems like video tracks still get included sometimes in `data-track-list`, such as in this release where there is a multimedia track: http://musicbrainz.org/ws/2/release/cbc97377-05f3-4011-a8fa-0aaa1ca9ffd1?inc=artists+artist-credits+recordings+aliases

Allow ignoring of audio data tracks on import

---

beets/config_default.yaml
beets/library.py
docs/changelog.rst
docs/reference/config.rst

I use the `%aunique` template function in a bunch of places and got tired of copy/pasting the same config over and over again so I made it configurable.
Comments? Questions? Bueller?

Allow setting default options for `%unique` in the configuration file.

---

beets/config_default.yaml
docs/reference/config.rst
test/test_mb.py

Follow up for https://github.com/beetbox/beets/pull/3021

Make `ignore_data_tracks` `yes` by default

---

beets/util/artresizer.py

This PR fixes #2504
PIL Image.save() requires a string parameter [1] while with python3 we call it with bytes.
This leads to wrong format detection (b'.png' isn't a key in supported formats list whereas '.png' is).
I haven't found a better existing function to do this (feel free to change patch) nor a unit test using PIL Image.save.
[1] https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.Image.save

Fixes #2504 in artresizer

---

tox.ini

Well, only flake8 was being run.
Before: https://travis-ci.org/beetbox/beets/jobs/426861476#L1143

Actually run tests on Python 3.7

---

beets/library.py
docs/changelog.rst

This should fix #3042. Let's see if Travis gives the thumbs up...

Make `%aunique` work with `-f/--format` options.

---

beetsplug/fetchart.py
beetsplug/smartplaylist.py
docs/changelog.rst
docs/plugins/replaygain.rst
test/test_autotag.py
test/test_library.py

I'll admit this is pretty nit-picky, but there seems to be a couple of typos across the codebase and documentation :grin: this PR fixes them up :+1:
I used [client9/misspell](https://github.com/client9/misspell) to find these.

Fix miscellaneous typos

---

beets/library.py
docs/changelog.rst

Prevents a fatal file system error on "beet update" if the album art file has been moved or renamed
and the beets library hasn't been updated with the new path.

move_art: Remove missing album art

---

beetsplug/subsonicupdate.py
docs/plugins/subsonicupdate.rst

This pull request suggests that solves the two following problems:
1. When specifying a port, the following error occurred:
`configuration error: subsonic.port: must be a string`
2. The subsonic configuration allows the user to specify a context path to append to the url, which is currently not supported by the plugin. This pull request contains a fix which suggests that an optional configuration `contextpath` is added.

Subsonicupdate plugin: Added context path and fixed bug in port configuration

---

docs/guides/main.rst

Hello! I was reading Beets' install guide when I saw that it suggested using ``sudo`` if ``pip install beets`` didn't work.
Using ``sudo`` to install Python packages using pip is [not a good practice security-wise](https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice). The proposed PR will suggest an alternative way using ``--user`` to make sure the package is installed locally.
Cheers!

docs: update the pip install instructions

---

beetsplug/convert.py
docs/changelog.rst

When the convert plugin is copying album arts, it logs
> Copying cover art to MY_SOURCE_FOLDER/cover.png
while it should say `from` (or `to` the source path). I first I thought my original covers were being overwritten. I fixed the <sup>critical</sup> issue.

Fixed typo in convert when copying cover art

---

beets/library.py
docs/changelog.rst
test/test_library.py

Fixes #3033
I would like to know if would be better if we had a "smart mode" which lower-case some prepositions, like [titlecase](https://pypi.org/project/titlecase/) does.

WIP: Enhance %title

---

beetsplug/info.py
docs/changelog.rst

Exports path (file path) if specified in fields to export (with -i parameter). Only when exporting library fields, because file tags don't contain path. Info works as before. Path won't be displayed in the list even if user provides it in parameters.

Export plugin can now export path from library.

---

beets/ui/__init__.py
docs/changelog.rst
docs/reference/cli.rst
test/test_ui_init.py

Fixes #3083.
I've updated the CLI documentation to mention the new `q` option, but I'm not exactly a wordsmith 😁 let me know if you can think of some better phrasing!

Allow exiting object selection early

---

beetsplug/embedart.py
beetsplug/fetchart.py
docs/changelog.rst
test/test_fetchart.py

See #1632.
Instead of iterating on all files in the directory, `sorted_walk()` is now being used so the files matching an ignore pattern and hidden files are skipped. The [importer](https://github.com/beetbox/beets/blob/master/beets/importer.py#L1611) does the same thing.
I wrote a few tests covering both the `ignore` and `ignore_hidden` settings. I have also moved things around a bit in `test_fetchart.py` in order to avoid duplicate code.
No changes.
Added an entry under current version in development / fixes.

Fetchart respect ignore settings

---

beetsplug/spotify.py
docs/plugins/spotify.rst
test/test_spotify.py

Addressing https://github.com/beetbox/beets/issues/2694, I've added OAuth support for the Spotify plugin using Client Credentials Flow. This requires a [registered application](https://developer.spotify.com/documentation/general/guides/app-settings/) and Client ID/Secret to be provided via `client_id` and `client_secret` under the `spotify` options in config.yaml.
I've also started working on adding Spotify support for the importer (incomplete `album_for_id` and `track_for_id` funcs included in this PR with some logic copied from the Discogs plugin), since I've come across more than a few releases that don't exist in MusicBrainz/Discogs/Beatport/Bandcamp but do in Spotify. However, I realize that the Spotify API doesn't provide certain fields like album `media`, `catalognum`, etc. like …

Add Spotify OAuth support and autotagger integration

---

beetsplug/spotify.py
test/test_spotify.py

I realized I'd forgotten to implement the `candidates` and `item_candidates` functions in https://github.com/beetbox/beets/pull/3123 for the Spotify plugin, which I assume are used by the importer to identify potential matches when not provided manually. I'm using the Spotify Search API to retrieve these candidates, and have modularized that logic to make this easier to implement.
I noticed that the Beatport and Discogs plugins don't use any of the passed `Item` attributes when determining potential matches. Is this recommended behavior if that data can't be meaningfully used to refine the API queries?

Add Spotify `candidates` and `item_candidates`

---

beets/autotag/hooks.py
beetsplug/spotify.py

Set `AlbumInfo.mediums` in the Spotify plugin's `candidates` function to address:
```
Correcting tags from:
Progressive Collection, Vol. 8
To:
Progressive Collection, Vol. 8
URL:
https://open.spotify.com/album/6IJPzMcrOsZfKGncwTKIKB
(Similarity: 83.4%) (tracks, source) (Spotify, 2016, Forward Music)
File "/usr/local/bin/beet", line 11, in <module>
load_entry_point('beets', 'console_scripts', 'beet')()
File "/Users/rahulahuja/git/beetbox/beets/beets/ui/__init__.py", line 1262, in main
File "/Users/rahulahuja/git/beetbox/beets/beets/ui/__init__.py", line 1249, in _raw_main
File "/Users/rahulahuja/git/beetbox/beets/beets/ui/commands.py", line 955, in import_func
import_files(lib, paths, query)
File …
```

Set Spotify AlbumInfo.mediums

---

beets/autotag/__init__.py
beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst

Add a new `no_clobber` config option that contains a list of "miscellaneous" metadata fields not to be overwritten by empty values.
I'm not entirely happy with the `no_clobber` name. Suggestions welcome.

First attempt at fixing #3132.

---

beets/art.py
beetsplug/discogs.py
beetsplug/filefilter.py
beetsplug/hook.py
beetsplug/replaygain.py
beetsplug/subsonicupdate.py
tox.ini

As it turns out, there _is_ a whole bunch of crazy indentation in our code! No idea how it got there and how it wasn't caught before, but I've fixed the few places where the indentation was wrong.
I also changed the `is` comparison to be a `==` check, as we shouldn't be using `is` to compare strings.
And finally, I've locked `pep8-naming` to `0.7.x` so we can avoid the weird bugs that are in that version.

Fix linter issues

---

beetsplug/ipfs.py
docs/changelog.rst
docs/plugins/ipfs.rst

This is a very minor change, but previously the ipfs plugin was making a separate copy of every file added. I left the default behaviour the same because using this requires setting an additional option in ipfs proper.

Support ipfs add --nocopy in ipfs plugin

---

beetsplug/discogs.py
docs/changelog.rst

this is should fix issue #3081.
since the discogs_client doesnt expose the rate limit headers (yet) (see https://github.com/discogs/discogs_client/issues/82), i added some code to keep the request rate below 60 requests per minute for logged-in users, or 25 for not logged-in users, as described here: https://www.discogs.com/developers/#page:home,header:home-rate-limiting

keep discogs requests below rate limit

---

setup.py

Even though munkres 1.1.2 fixed the issue with Python 3.5 (#3143), it had already dropped support for Python <3.5.x in [1.1.0](https://github.com/bmc/munkres/blob/5badef0ae62ed5a8d4164fd358dda96163295c8f/CHANGELOG.md) (which beets still supports).
We are going to have to lock our version of munkres to 1.0.x until we drop support for 3.5 ourselves.

Lock munkres to 1.0.x

---

docs/changelog.rst
setup.py

Jellyfish is no longer python 2 compatible as of release 0.7.0.
By pinning the previous release, beets is still able to be installed
and run on python 2 systems without issue.
I just found beets today in the comments of a Hacker News post, and ran into the following after installing locally:
```
eric@oudebier:~$ beet -p
File "/usr/local/bin/beet", line 11, in <module>
load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
return ep.load()
File …
```

Maintain python 2 compatibility

---

beetsplug/playlist.py
docs/changelog.rst
docs/plugins/index.rst
docs/plugins/playlist.rst
test/test_playlist.py

Adds M3U playlist support as a query to beets and thus partially
resolves issue #123. The implementation is heavily based on #2380 by
Robin McCorkell.
It supports referencing playlists by absolute path:
$ beet ls playlist:/path/to/someplaylist.m3u
It also supports referencing playlists by name. The playlist is then
seached in the `playlist_dir` and the `.m3u` extension is appended to the
name:
$ beet ls playlist:anotherplaylist
The configuration for the plugin looks like this:
playlist:
relative_to: library
playlist_dir: /path/to/playlists
The `relative_to` option specifies how relative paths in playlists are
handled. By default, paths are relative to the `library` directory. It
also possible to make them relative to the `playlist` or set the option
or set it to a fixed path.

Playlist plugin

---

beets/dbcore/db.py
beets/dbcore/queryparse.py
beets/plugins.py
beets/ui/__init__.py
beetsplug/playlist.py
docs/changelog.rst
docs/dev/plugins.rst
test/helper.py
test/test_dbcore.py

As discussed in https://github.com/beetbox/beets/pull/3145#pullrequestreview-204523870, this adds a generic facility for defining "named" queries that are *not* field queries. This way, a query part like `playlist:foo` need not rely on a declaration of a field called `playlist` despite the fact that no one is ever supposed to put data in the `playlist` field. Instead, the query parser can recognize these non-field queries and use them directly.
This also should obviate the need for #3149, which was another way to "force" field queries to be fast, even when the underlying field did not exist. @Holzhaus, can you please take a look and let me know if this suffices to get the behavior you want?
This should also make it possible to support random queries like `rand:5`, as discussed in …

Add support for "named queries" and use them in the playlist plugin

---

beetsplug/playlist.py
docs/plugins/playlist.rst
test/test_playlist.py

This is round two for the `playlist` plugin:
This improves the existing tests (and adds some more to ensure nothing breaks), and also adds the auto-update functionality that I described in issue #123:
If the `auto` is set, then whenever a database item is moved or removed, the playlists inside the `playlist_dir` are updated to reflect that change.

playlist: Add auto-update functionality and more tests

---

beets/util/__init__.py
beetsplug/absubmit.py

Following #3003 and #3006, and the now long-forgotten promises I made, here is the parallel_map function making it into utils! This way we can now very easily apply transforms to the library in a parallel way (in Py3) while remaining compatible with Py2.
This also converts `absubmit` to use the new util. Expect updates to #3006 as well!

Add parallel map utility

---

beetsplug/badfiles.py
docs/changelog.rst

Following my work on #3003 I figured I'd do the same thing for `beet bad`.

Parallelize the badfiles plugin

---

beetsplug/fetchart.py
docs/changelog.rst

Today I had some network problems regarding dbpedia.org, which made
beets crash because a `requests.exceptions.ConnectionError` was raised
(`[Errno 113] No route to host`). This commits adds some error handling
around network requests to prevent further crashes in the future.

fetchart: Add some error handling to prevent crashes

---

beetsplug/badfiles.py

Without this patch, the superclass `__init__` method is never called, thus the `early_import_stages` attribute does not exist and causes an `AttributeError`.

badfiles: Fix #3158 by calling superclass __init__ method

---

beetsplug/hook.py
docs/changelog.rst
test/test_hook.py

Fix hook byte string interpolation

---

docs/reference/config.rst

The setting is quite confusing. After having difficulty getting the autotagger to accept an id for a specific release that I knew was correct, I investigated and count [this closed issue][0] that totally explains the problem.
To clarify the issue, I quoted Adrian from the issue and elaborated a bit, providing the solution. Unfortunately, the solution is undocumented. I'd like to document it, but I am unsure what the actual weighting system in `distance_weights` is. Adrian says 0.9 to ignore missing_tracks, which implies it's similar to the distance weighting in the other settings, but other settings in the default config are set to multiples of 1, implying it is not.
[0]: https://github.com/beetbox/beets/issues/3064

Improve specifications in the matches.ignored setting

---

docs/reference/config.rst

Contrary to what the current docs say, `incremental_skip_later` should be set to `no` for beets  to revisit skipped directories: https://github.com/beetbox/beets/blob/3b78d933cf46d5cad8f90ea6cdf38ada9e10846f/beets/importer.py#L582-L586

Clarify description of incremental_skip_later

---

beets/dbcore/db.py

Fetch flexible attributes once for all relevant items instead of once per item.
For queries with larger result sets this drastically cuts down the number of issued sqlite queries.
In the end, this didn't quite give the performance boost I'd hoped it would, but it feels still slightly faster for larger queries.
Unfortunately the hot spot seems to be somewhere else though :-/
One thing to note, since the list of IDs used in the WHERE..IN clause can be quite large (and reach sqlite's query parameter limit), I resorted to not passing them as parameters.
This should be fine, since these are not values originating from input but coming from the database from a previous query. Not sure how big of an issue this is nonetheless.

Small performance optimization when fetching items from library.

---

.gitignore
beets/ui/commands.py
docs/changelog.rst
test/test_ui.py

In many cases https://github.com/beetbox/beets/issues/2419 was being hit not because users had moved the album art, but because:
* beets moves items in an album
* this moves the covert art since `with_album=True`, but doesn't update album.artpath in the DB because `store=False`
* beets moves the album itself
* this moves the cover art again from the old path, which no longer exists
https://github.com/beetbox/beets/pull/3030 hides this error in most cases, but without this fix beets will still lose track of your album art, even if it doesn't throw, as evidenced by the test.
note: to fail without the fix, the test needs to add a second item to the album. this is because only the *second* item move actually moves the album cover, because the album's path is guessed from its first item's …

beets update: dont move album art twice

---

test/_common.py
test/test_player.py

I'd like to work on updating the MPD server version supported by BPD (#800) so as a first step I'm adding some tests that exercise BPD. I found an existing file that was testing parts of the BPD plugin, though the name is a bit unexpected (`test_player.py` rather than, say, `test_bpd.py`) so perhaps this should be renamed.
The test code adds a simple TCP client that can speak to an MPD server. It provides a small number of convenience functions for building requests and interpreting responses but it intended to be pretty dumb. This way we can treat BPD as a black box and test how it responds over the protocol rather than unit testing the functions in the plugin's module. The real BPD server is started in a separate thread, and we have to wait a small amount of time for it to spin up …

Add tests for BPD

---

beetsplug/the.py

Previously the `the` plugin would log a debug message when the text _didn't_ get changed by the plugin, whereas I think what was intended was the opposite. With this change the logged messages show the actual transformations made by the plugin.

the: log a debug only when text is changed

---

beetsplug/bpd/__init__.py

There was a code comment indicating that there was a plan to use the plugin logger instead of the global one, so this PR makes that change. It means we drop the `--debug` flag from the `bpd` command since the logger is now controlled by the normal `beet -v` verbosity flag. Also fixes up a debug message that was previously `print`ed to stdout, and tweaks the format of the MPD protocol debug messages to make them a little easier to read/interpret. New look:
```
[...]
bpd: Building directory tree...
[...]
bpd: Finished building directory tree.
bpd: New client connected
bpd: server: OK MPD 0.13.0
bpd: client: command_list_ok_begin
bpd: client: status
bpd: client: currentsong
bpd: client: command_list_end
bpd: server: volume: 10
repeat: 0
random: 0
consume: 0
playlist: 0
playlistlength: 0 …
```

bpd: use plugin logger instead of global logger

---

beets/dbcore/db.py
beets/util/confit.py
beetsplug/discogs.py
beetsplug/lyrics.py
beetsplug/metasync/itunes.py

While running the test suite with pytest in Python 3.7, it flagged a few distinct deprecation warnings. I see that the YAML one is handled in another PR, but this one addresses:
* `log.warn()` [should be `log.warning`](https://bugs.python.org/issue13235)
* Abstract base classes from `collections` were moved to `collections.abc` in Python 3.3 and [will be unavailable](https://docs.python.org/3/library/collections.abc.html) from their original location in Python 3.8.
* Regex flags that aren't at the start of the pattern [have been deprecated](https://bugs.python.org/issue22493)
* The `plistlib` module has a [changed interface](https://docs.python.org/3.7/library/plistlib.html#plistlib.readPlist) since Python 3.4

Fix several deprecation warnings

---

test/test_ui.py

The test `CommonOptionsParserCliTest.test_version` was passing with nose but failing with pytest (see output below). The reason for the failure seemed to be that the `test` plugin was loaded when it wasn't expected to be loaded, changing the output of the `version` command. I'm not sure exactly why that was happening, but since that test already inherited from `TestHelper`, just invoking the plugin load/unload helper was enough to fix it. I also removed the line setting the `self.lib` variable since that's already done in the helper.
```
self = <test.test_ui.CommonOptionsParserCliTest testMethod=test_version>
def test_version(self):
l = self.run_with_output(u'version')
self.assertIn(u'Python version', l)
>       self.assertIn(u'no plugins loaded', l)
E       AssertionError: 'no plugins …
```

Fix test_ui:test_version under pytest

---

beets/dbcore/db.py
beets/importer.py

I analyzed where time is spent when querying the library and found that most of it is actually type casting properties after retrieving them from the database. However, this isn't really necessary. We hardly ever need access to all properties, so it makes much more sense to delay the actual casting until a property is accessed.
Taking my previous baseline of `3.66s` for master, doing the delayed type casting reduces this to `1.96s`, or down to `1.45s` when #2798 is also applied (a bit slower now than my first number with it now no longer being a poc).
Our of those remaining ~1.5s, about 0.5s is spent on the actual database queries, and the rest is object creation.
I'm open to ideas for further performance improvements here, but we get firmly into area of micro-optimizations (creating …

Performance improvement: Type cast properties on demand

---

.travis.yml
beets/util/functemplate.py
setup.py
tox.ini

This PR fixes support for Python 3.8 by conditionally providing a new second argument to `ast.Module`.
I have added a `py38-test` tox environment (and associated `-cov` and `-flake8` environments) and enabled this on Travis, however I couldn't even see Python 3.7 being tested on AppVeyor. Should both 3.7 and 3.8 be enabled on there?

Support Python 3.8 (fixes #3201)

---

docs/reference/config.rst

It's hard to impossible to figure out the correct syntax for non python users.

Provide an example for the languages list

---

beetsplug/mpdstats.py
docs/changelog.rst
test/test_mpdstats.py

This is a copy of #2754, rebased and with the additional small change required to the test. Ive also tested it using bpd (with the changes from my `bpd-idle` branch) and it appears to be working well.
Closes #2754, closes #2752

mpdstats: use currentsong instead of playlist

---

beetsplug/mpdstats.py

#3207 seemed to have deleted lines related to #2707 which allowed mpdstats to update songs ratings when playing the same song consecutively as well as when switching from a song to an internet stream.  Re-added the lines and it seems to be working fine with the new currentsong method.

mpdstats: Re-add fixes from #2707

---

beets/util/__init__.py
docs/changelog.rst

Since `fnmatch_all` can raise `OSError`s, and we were already silently giving up in `prune_dirs` on some of these exception, just do more of the same. Closes #1996.
It seems that this solution was agreed on in the issue but nobody went ahead and implemented it. I haven't made any attempt to test this but it looks sensible.
/cc @jackwilsdon

Catch OSError in prune_dirs helper

---

beetsplug/bpd/__init__.py
docs/changelog.rst
docs/plugins/bpd.rst
test/test_player.py

The `idle` command from a client signals that the connection should remain idle until an event occurs in the player, at which point the client should be notified. This PR adds support for the command by making the client's thread poll a list of events. The server can asynchronously populate the event list in response to requests from other clients.
This is the next step for #800 and gets us to MPD 0.14.
Details from the MPD protocol specification:
>Waits until there is a noteworthy change in one or more of MPD’s subsystems. As soon as there is one, it lists all changed systems in a line in the format `changed: SUBSYSTEM`.
>
>Change events accumulate, even while the connection is not in “idle” mode; no events gets lost while the client is doing something else with the connection. If an …

bpd: support idle command and with it MPD 0.14

---

beetsplug/edit.py
test/test_config_command.py

Disclaimer: I don't use beets. But these changes should be simple enough that they don't break anything.

Replace more instances of unsafe calls to yaml.load

---

beetsplug/mpdstats.py
beetsplug/mpdupdate.py
docs/changelog.rst
docs/plugins/mpdstats.rst
docs/plugins/mpdupdate.rst

Most MPD clients support the environment variables `MPD_HOST` and `MPD_PORT`. The two MPD client plugins in beets supported the former but not the latter. This change will allow the correct setting to be picked up automatically in more cases, while still allowing the port to be overridden in the config file.

mpdupdate, mpdstats: use MPD_PORT env variable

---

docs/dev/plugins.rst

This decorator was removed in 4578c4f0e1659daab8d25c79d1f466ae9838d8c7 and now `BeetsPlugin.register_listener` should be used instead. Fixes #2885.

docs: remove reference to BeetsPlugin.listen

---

beetsplug/bpd/__init__.py
beetsplug/bpd/gstplayer.py
docs/changelog.rst
test/test_player.py

This uses GStreamer APIs to extract a list of audio decoders and the relevant MIME types and file extensions. Some clients like ncmpcpp use this command to fetch a list of supported file extensions.
I'm by no means familiar with GStreamer, and I got some pointers about the relevant APIs from a similar effort in Mopidy: mopidy/mopidy#812. At least ncmpcpp uses this command to fetch the list of supported file extensions (it ignores the rest of the information) and then uses that to tune its interface when browsing local files.
The full output on my system uses this information (format is `<plugin> <mime types> <file exts>`):
```
mpegaudioparse {'audio/mpeg'} {'mp2', 'mp1', 'adif', 'mpga', 'aac', 'adts', 'loas', 'mp3'}
openmptdec {'audio/x-mod'} {'stm', 'mod', 'stx', 'dmf', 'dbm', 'dsm', …
```

bpd: support decoders command

---

beets/dbcore/db.py
beetsplug/loadext.py
docs/changelog.rst
docs/plugins/index.rst
docs/plugins/loadext.rst

This is a rough draft at the moment of what a `loadext` plugin could look like for loading SQLite extensions. This plugin can be used to fix #3160 by allowing users to load the ICU plugin like so;
```
loadext:
- libicu
```
Note that this will require the user to compile their own copy of `ext/icu` from SQLite sources.
I've got a few points of discussion I'd like to bring up regarding this PR;
1. The elephant in the room;
```Python
conn = lib._connection()
```
This is certainly less than ideal, as we're reaching into beets internals from this plugin. There ~are two~ is one possible solution~s~ I can think of to this;
* ~Use `SELECT load_extension(...)`~ This doesn't work properly, see [this thread](http://sqlite.1065341.n5.nabble.com/Error-on-loading-ICU-extension-td41219.html) regarding …

Add loadext plugin

---

.travis.yml

Looks like tox 3.9.0 fixes the issues we were seeing on Travis.
This reverts commit 777cfbbf610522c0b655659f8f11d519714606b5.

Revert "Travis: temporarily pin tox to <=3.8.1"

---

beets/dbcore/queryparse.py
beets/library.py

This PR removes the use of `beets.config['sort_case_insensitive']` from `beets.dbcore`, instead moving the configuration access into `library.py`.
There is still one more use of `beets.config` within `beets.dbcore`, which I am hoping to address separately.
Related: #1531

Stop using beets.config['sort_case_insensitive'] in beets.dbcore

---

beets/util/artresizer.py

Updated artresizer's ImageMagick commands to use the magick binary added in ImageMagick 7.x, rather than the legacy utilities ('convert', 'identify', etc.) This resolves an issue where beets is failing to detect or use ImageMagick on Windows even when it is set correctly on the PATH, which in turn restores functionality to the fetchart and embedart plugins on Windows.
Closes #2093

Update artresizer's ImageMagick commands to use the magick binary

---

beetsplug/replaygain.py
test/test_replaygain.py

I've opened this as a draft as I'm not 100% happy with my test implementation (and also the wording of the error itself). I implemented the test in the way I did as I didn't want us to actually require bs1770gain to run the test, as we are mocking the tool's output anyway. This meant that we couldn't use the existing `ReplayGainLdnsCliTest` class as it extends `ReplayGainCliTestBase`, which tries to run a whole suite of tests on the backend.
I'm not a fan of patching `beetsplug.replaygain.call`, as it's a somewhat "internal" feature of the plugin, but I couldn't see another way to mock the output from bs1770gain.
---
Fixes #2983

replaygain: Handle invalid XML output from bs1770gain

---

beets/dbcore/db.py
beets/library.py
beets/ui/__init__.py
beets/util/functemplate.py
docs/changelog.rst

As discussed in PR #2388, this PR makes gives some performance improvements for querying. On my database of around 14k songs, these commits make `beet ls > /dev/null` run in 6.4 seconds, down from 15.5.
The second commit confuses me. For some reason, inlining the call to `formatted()` makes the difference between 11 seconds and 6.4 seconds. I was confused for quite some time, thinking that `FormattedMapping` itself was doing something slow, but it turns out that the function call overhead was causing it?!
In this PR I have used `lru_cache` to cache the formatting templates. I would have preferred to explicitly create the template at the call site, but I can't seem to figure it out. The function `list_items`, in `ui/commands.py`, receives an argument `fmt`. I figured that this argument …

Improvements to query performance

---

beets/library.py

See [my comment](https://github.com/beetbox/beets/issues/3049#issuecomment-491009715) on #3049.

Use NullPaddedInt for all r128_album_gain fields.

---

beets/library.py
beets/util/__init__.py
docs/changelog.rst

Broken out from #3258, as it seems orthogonal.
The item formatter is fetching the related album for each item, even when it is not needed. This PR lazily fetches the album if it is really needed, and does not hit the DB in other cases.

Lazily fetch album in FormattedItemMapping, it's not needed in most cases

---

beets/util/artresizer.py

The `return` statement was at the wrong indent level, so we never checked for the legacy `convert` executable. I ran into this with the 1.4.8 upgrade, getting warnings since `convert` no longer gets detected.
@ababyduck looks like you were last in this code, this look OK to you?

Fix ImageMagick Detection

---

beets/ui/__init__.py
docs/changelog.rst

This commit adds support for the [`NO_COLOR` environment variable](https://no-color.org/).
I was looking for a way to temporarily disable colors while piping the output of `beet mbsync -p` to a file. Rather than implement this as a top-level `--no-color` option, it was much easier to just add support for `NO_COLOR`.

Add support for NO_COLOR.

---

test/test_random.py

Without this change `python setup.py test` fails to run, since this test was missing a `suite`.

Make test_random work with setup.py test

---

setup.py

We already do this in the optional dependency section so this shouldn't cause any problems. It's only used by the `thumbnails` plugin.
I noticed that Debian was carrying a patch to remove this line since they install beets with Python 3 only and don't have a Py3 package for pathlib.

Make pathlib dependency in tests conditional

---

beets/util/functemplate.py

Python 3.8 adds the required `posonlyargs` to `ast.arguments` (see the [Grammar](https://docs.python.org/3.8/library/ast.html?highlight=posonlyargs#abstract-grammar)), resulting in failures such as these: https://travis-ci.org/geigerzaehler/beets-alternatives/jobs/538912903.
There's some discussion about similar breaking API changes (namely in the inspect module) [here](https://github.com/python/cpython/pull/12701/files) and [here](https://bugs.python.org/issue36751),  which however does not mention the lower level ast syntax changes, so I'm assuming that the ast module is supposed to always reflect the grammer such that this is not to be considered a regression.
Does this warrant a changelog entry? Due to the werkzeug incompatibility, Python 3.8 still is not fully supported.

functemplate: Adapt ast syntax to PEP570 changes on python3.8

---

test/testall.py

I was unable to run the test suite using `testall.py` without removing this line. After this change it works when invoked from the top-level directory.
Our [Testing](https://github.com/beetbox/beets/wiki/Testing) wiki says one way to invoke tests is `cd test ; python testall.py`. I was unable to get this working:
* From the `test` directory, calling `python testall.py` results in:
```
File "testall.py", line 43, in <module>
unittest.main(defaultTest='suite')
File "/usr/lib/python3.7/unittest/main.py", line 100, in __init__
self.parseArgs(argv)
File "/usr/lib/python3.7/unittest/main.py", line 147, in parseArgs
self.createTests()
File "/usr/lib/python3.7/unittest/main.py", line 159, in createTests
self.module)
File "/usr/lib/python3.7/unittest/loader.py", …
```

Setup path correctly in testall.py

---

.travis.yml
appveyor.yml

I noticed some deprecation messages in the Travis outout when it's running `flake8` using Python 3.4. Let's update that to a more modern version. There's probably more that can be updated in the CI config while we're at it.

Update Python 3 versions for CI

---

setup.py

useful when run as
```
python setup.py install
```
Fixes #3264

Update setup.py to install to a directory rather than egg file

---

test/helper.py
test/test_dbcore.py
test/test_importer.py
test/test_pipeline.py
test/test_ui_importer.py

When using pytest's test collector, any class with a name starting with `Test` is collected. If it notices that the class has an `__init__` member then it skips it with a warning since it's probably a false positive. This isn't a big deal, but we can avoid warnings like this:
test/test_ui_importer.py:33
beets/test/test_ui_importer.py:33: PytestCollectionWarning: cannot collect test class 'TestTerminalImportSession' because it has a __init__ constructor
class TestTerminalImportSession(TerminalImportSession):
simply by renaming `TestX` to `XFixture`.

tests: avoid non-test classes named Test*

---

appveyor.yml

There's an `appveyor-retry` command that should help to make some of the dependency installation more reliable and the AppVeyor tests less flaky.

Retry dependency installation commands on AppVeyor

---

beets/ui/commands.py

Just taking care of the loose thread from #3224. This function from confuse wasn't necessary here in the one place that was using it. The old version was possibly a little clearer in intent, but the new version has less indirection.

Avoid using an internal confuse function

---

docs/guides/advanced.rst
docs/reference/config.rst

This adds two of the recipes from the Cookbook page to the "Advanced awesomeness" guide in the docs, changing markup syntax but otherwise leaving the text alone. The other two recipes already existed in the docs with different text. After this we can delete the Cookbook page (#3283).

Move wiki cookbook to the docs

---

beets/util/bluelet.py
beetsplug/bpd/__init__.py
docs/changelog.rst
docs/plugins/bpd.rst
test/test_player.py

Now that `idle` has been implemented, we're almost all the way to MPD 0.16 support. There are a couple of small commands that need adding, but most of what we need is already in place. More importantly, claiming to support the newer protocol version means that more clients will talk to us; fixes #800.
I've expanded my local tests to include ncmpcpp and two Android clients (MPDroid and MALP). So far bpd breaks all three of these clients. Known compatibility issues are listed below.

bpd: support MPD 0.16 protocol and more clients

---

README.rst

This is just to advertise that beets is available in distros. The badge links to a list of distro packages for beets and the current versions they have available, which is useful for users and contributors.

Add repology badge

---

beets/ui/__init__.py
beets/util/__init__.py
beetsplug/beatport.py
beetsplug/bpd/gstplayer.py
beetsplug/lyrics.py
beetsplug/spotify.py
docs/plugins/smartplaylist.rst
docs/plugins/web.rst
docs/reference/cli.rst
test/test_mb.py

Continuation of #3296. See commit messages for details.
This time I also changed/added a couple references in code.
Regarding beets.io, you'll probably need to update your [gh-pages settings](https://github.com/beetbox/beets/settings) to remove the custom domain name and then set it again so that Github will create a proper certificate for your domain. They support this for about a year now.

More https changes

---

beets/autotag/__init__.py
beets/autotag/hooks.py
beets/config_default.yaml
beets/library.py
beetsplug/discogs.py
test/test_discogs.py
tox.ini

Adding styles to discogs plugin. Closes #2579.

#2579 Adding styles to discogs plugin

---

docs/plugins/mpdstats.rst

Clarify that `mpdstats` is an MPD client and needs to be running all the time to collect statistics.
See https://discourse.beets.io/t/mpdstats-requirements/796

docs: mention mpdstats needs to be running

---

beetsplug/replaygain.py
docs/changelog.rst
setup.py

Fix #3311.
As suggested in the discussion there, the Q7.8 conversion has been moved into mediafile. Thus this depends upon [mediafile #16](https://github.com/beetbox/mediafile/pull/16).

replaygain: fix #3311

---

beetsplug/absubmit.py
docs/plugins/absubmit.rst

just wanted to have the possibility to skip items which have already Acousticbrainz data (which is now default). 
-force will go back to the old behavior
-dry will show only the items which would be processed
see
https://discourse.beets.io/t/acousticbrainz-for-big-libraries/378

Absubmit improvements

---

docs/plugins/convert.rst

One of the Convert plugin's greatest features is that it skips files that have already been converted. So one can just run `beet convert` willy-nilly without keeping track of which files have already been converted.
This adds one sentence to clarify the documentation, making it clear that one can run `beet convert` without fearing that previously-converted files will be needlessly re-converted.

Convert plugin skips previously-converted files

---

beets/util/__init__.py
beets/util/artresizer.py
beetsplug/absubmit.py
beetsplug/duplicates.py
beetsplug/ipfs.py
beetsplug/keyfinder.py
beetsplug/replaygain.py
docs/changelog.rst
test/test_keyfinder.py
test/test_replaygain.py

Return a namedtuple CommandOutput(stdout, stderr) instead of just stdout from
util.command_ouput, allowing separate access to stdout and stderr.
This change is required by the ffmpeg replaygain backend (GitHub
PullRequest #3056) as ffmpeg's ebur128 filter outputs only to stderr.

util.command_output: return stderr, too

---

docs/changelog.rst
test/test_player.py

The bpd test bind a socket in order to test the protocol implementation. When
running concurrently this often resulted in an attempt to bind an already
occupied port.
By using the port number `0` we instead let the OS choose a free port. We then
have to extract it from the socket (which is handled by `bluelet`) via
`mock.patch`ing.
Please note that I'm not really familiar with any of the relevant technologies (the `bpd` plugin, python's `multiprocessing`, `bluelet`, sockets and `unittest.mock.patch`). Please review thoroughly.

fix "Sporadic test failures in BPD tests #3309"

---

beetsplug/replaygain.py
docs/changelog.rst
docs/plugins/replaygain.rst
test/test_replaygain.py

Add a replaygain backend using the [ffmpeg](https://ffmpeg.org) CLI-tool and its [ebur128](https://ffmpeg.org/ffmpeg-filters.html#ebur128-1) filter.
It is a alternative to the bs1770gain to create R128_* tags.
#3055 also uses ffmpeg, but with an intermediary python module ("r128gain"). This pull request replicates some of the work done in r128gain, but avoids the (beta-) dependency.
The album gain algorithm implemented in this backend - the mean of all track gains, also used by the bs1770gain backend - gives different results than the implementation in r128gain (calculating the gain for a concatenation of all tracks). Calculating the mean is obviously faster than rescanning the whole album, but might deliver worse results.
This backend also does not implement any kind of threading (a …

Replaygain backend ffmpeg

---

beets/util/__init__.py
beetsplug/playlist.py
beetsplug/smartplaylist.py
docs/plugins/playlist.rst
docs/plugins/smartplaylist.rst
test/test_files.py

closes https://github.com/beetbox/beets/issues/3331

Add option to force forward slashes in paths 

---

beetsplug/replaygain.py
docs/changelog.rst
docs/plugins/replaygain.rst
test/test_replaygain.py

Remove REPLAYGAIN_* vs R128_* tag handling from the Backends, restrict it to the main plugin logic. That is archieved by passing the target loudness level to the backend with every album/track. It also necessitates that all Backends properly implement the target level.
As the different tag formats call for different default target levels this also seperates the configuration of those levels.

replaygain: target level refactor

---

beetsplug/replaygain.py
docs/plugins/replaygain.rst

When I tried to use the ffmpeg backend for the replaygain plugin it threw the following error:
```
replaygain: ReplayGain error: ffmpeg exited with status 1
```
When running the ffmpeg command manually the following error occurred:
```
Stream mapping:
Stream #0:1 -> #0:0 (mjpeg (native) -> wrapped_avframe (native))
Stream #0:0 -> #0:1 (flac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Cannot connect audio filter to non audio input
```
I figured out that the issue occurred when the file contains embedded album art. When the file has embedded album art ffmpeg also tries to calculate the replaygain values for the album art, which obviously doesn't work.
Therefore i added '-map a:0' to the command in order to inform ffmpeg to only apply the filter to the audio stream. …

ffmpeg replaygain backend: Only calculate replaygain for audio stream

---

beetsplug/discogs.py
docs/changelog.rst

Redoing #3337 with the style fixes and a changelog.
From what I understand, the Discogs Master isn't required like the MB Release Group, so sometimes the url is undefined
fixes #2965, fixes #3239

Use the 'resource_url' from discogs_client to not throw exception

---

beetsplug/spotify.py
docs/changelog.rst

I've had this fix in place locally for a while but forgot to submit a PR! This properly assigns the `AlbumInfo.year` attribute with year-only release dates returned by the Spotify Albums API and prevents a downstream `sqlite3.InterfaceError` when trying to insert e.g. `[2019]` in an INTEGER field.

Fix handling of Spotify year-only release dates

---

beets/ui/commands.py
docs/changelog.rst

fixes issue #3346: When the `per_disc_numbering` option was set, the UI would
previously show a `#0 -> #1` change when actually the index would be set
to 0 (a valid index, such as for hidden tracks).  Now, properly
distinguish index 0 and None (i.e. not set)

Correctly display track number 0 in show_change

---

beetsplug/convert.py
docs/changelog.rst
docs/plugins/convert.rst

This is an updated version of #2326 and 7d26639e134051ac3a8a1e715fb324581b0727dc, resolving merge conflicts and addressing the comments on that PR. Based on proposal in #2324.
Credit goes to @kierdavis for the original PR.
Closes #2326 if merged.

convert: add option to symlink or hardlink instead of copying

---

beets/importer.py
docs/changelog.rst

This adds the `data_source` field (flex-attribute) to Albums during an import, it copies the value from the  first Item's corresponding field.
Does this need a conditional test to make sure that the Item field exists and actually has a value first?

Fix for issue #1693 (Apply `data_source` field to albums)

---

beets/library.py

This makes it possible to recover from this case, as you can correct
whatever caused it, by either fixing album ids on tracks or removing the
empty album id.
I ran into this with joining albums and manual manipulation of the ids, which I expect most won't run into, but it's better to not get into a state that we can't easily recover from, so I think it's worthwhile to include the info needed to recover.

library: show album id in empty album error

---

beetsplug/deezer.py
beetsplug/discogs.py
beetsplug/spotify.py

Refactor the Spotify and Discogs plugins to use `beets.plugins.MetadataSourcePlugin` base class logic (introduced in https://github.com/beetbox/beets/pull/3355). If preferred, I can create separate PRs for changes to the Discogs and Deezer plugins, instead of including them here.

Integrate MetadataSourcePlugin

---

beetsplug/beatport.py
docs/changelog.rst
test/test_beatport.py

This fixes bug #3374 .
I have added checks to see if the response actually exists in the method `get_release`.
The reported bug should be fixed by looking first if the attribute in the dictionary is there and then checking if the list contained therein is truthy which means it has items in it that can then be accessed.
Two typos were in docstrings and one forgotton print statement.

Fix #3374 beatport

---

beetsplug/beatport.py
docs/changelog.rst

Fix a bug introduced in https://github.com/beetbox/beets/pull/3372 by defaulting the `musical_key` to None for Beatport releases, avoiding the following:
```
File "/Users/rahulahuja/Dropbox/.virtualenvs/beetbox/beets/bin/beet", line 11, in <module>
load_entry_point('beets', 'console_scripts', 'beet')()
File "/Users/rahulahuja/git/beetbox/beets/beets/ui/__init__.py", line 1267, in main
File "/Users/rahulahuja/git/beetbox/beets/beets/ui/__init__.py", line 1254, in _raw_main
File "/Users/rahulahuja/git/beetbox/beets/beets/ui/commands.py", line 956, in import_func
import_files(lib, paths, query)
File "/Users/rahulahuja/git/beetbox/beets/beets/ui/commands.py", line 926, in import_files
session.run() …
```

[beatport] Exclude invalid musical keys

---

docs/plugins/beatport.rst
docs/plugins/deezer.rst
docs/plugins/discogs.rst
docs/plugins/index.rst
docs/plugins/spotify.rst

I have found that the documentation of DiscogsPlugin does not mention the 'source_weight' option. This PR adds that information:
Add Configuration section and describe the 'source_weight' option.

docs/plugins/discogs.rst: Update plugin documentation

---

beets/autotag/__init__.py
beets/autotag/hooks.py
beets/library.py
beets/plugins.py
beetsplug/beatport.py
beetsplug/bpsync.py
beetsplug/deezer.py
beetsplug/mbsync.py
docs/changelog.rst
docs/plugins/bpsync.rst
docs/plugins/index.rst
test/test_beatport.py

This is a proof-of-concept for a `bpsync` plugin, Beatport's equivalent of `mbsync`. It allows users to sync changes to Beatport metadata and "backfill" new fields recently added in https://github.com/beetbox/beets/pull/3372.
I'm considering abstracting this functionality into a `SyncMetadataSourcePlugin` base class (similar to `MetadataSourcePlugin` introduced in https://github.com/beetbox/beets/pull/3355) which can also be leveraged for Spotify/Deezer/MusicBrainz, although that requires some larger refactors of `BeatportPlugin` and `MBSyncPlugin`, perhaps better suited for a separate PR? 
@sampsyo, what do you think? Is it worth putting the finishing touches on this Beatport-specific plugin, or investing time in a `SyncMetadataSourcePlugin` to future-proof?
This PR also closes …

Add BPSyncPlugin

---

beetsplug/export.py
docs/changelog.rst
docs/plugins/export.rst
test/test_export.py

The original export plugin only exported as JSON so I added the ability to export in CSV or XML format. To do this I created a new option `-f` or `--format` which specifies the export format, the default is still JSON. For example...
`$ beet export -f csv -i "title,album" ACDC`
I also updated the plugin documentation to reflect the changes I've made to the plugin. Lastly, I also created a unit test for the export plugin; since one hadn't been created yet.

Extended export plugin support

---

beetsplug/hook.py
docs/changelog.rst
test/test_hook.py

A small change but hopefully part of a larger piece of work around #2835.

hook: switch to using check_call

---

docs/plugins/playlist.rst

See https://discourse.beets.io/t/playlist-vs-smartplaylist-plugins/975/2

Fix wrong section name (smartplaylist => playlist)

---

beetsplug/bpd/__init__.py
docs/changelog.rst

This fixes the playlist not updating when in consume mode, at least in
ncmpcpp.
Someone who knows the mpd protocol better might want to make sure I'm doing this right, though,

Increment playlist_version when a track is consumed.

---

beetsplug/subsonicupdate.py
docs/plugins/subsonicupdate.rst

The plugin does a great job updating, but if I wanted to use the 443 port (https) it fails. Example, going to https://google:80 fails because it doesn't know how to forward this. So in the users' case, they would have to assume that giving port 80 in the config will forward to 443 using https properly. This just makes it more obvious.
I also added some more logs to make it more obvious to the user what's going on if they use the `--verbose` option. And if they don't, then it will send a `log.info` for success cases.
In terms of logging, I think I did this right. Please let me know if I didn't. Also first time contributing something in Python -- sorry if it doesn't look right. Let me know if I need to update anything!

Added schema variable and added more logging

---

beetsplug/discogs.py
docs/changelog.rst
docs/plugins/discogs.rst

This PR implements the feature described in #3458, enabled with the `index_tracks` option in the `discogs:` section.
Since `DiscogsPlugin.coalesce_tracks` discards index tracks that are used to title subtrack mergers, I don't *think* it interacts badly with this feature. But I might be missing something, in which case please correct me.

discogs: Add `index_tracks` option (closes #3458)

---

beetsplug/keyfinder.py
docs/changelog.rst
docs/plugins/keyfinder.rst

Added support for [keyfinder-cli](https://github.com/EvanPurkhiser/keyfinder-cli) to the keyfinder plugin, which doesn't want/rejects the -f flag before a path

support for keyfinder-cli, which doesn't want the -f flag for paths

---

test/test_replaygain.py

`bs1770gain` is marked as unavailable when it shouldn't be because `bs1770gain --replaygain` returns an error.

Remove --replaygain flag when checking bs1770gain availability

---

beetsplug/replaygain.py
docs/changelog.rst
test/test_replaygain.py

Fixes https://github.com/beetbox/beets/issues/3479.

Update Bs1770gainBackend to handle bs1770gain v0.6.0 XML output

---

docs/plugins/index.rst

I could not find a logical explanation to the order of the plugins so I assumed that they are in a chronological order and therefore I put mine to the bottom. (Maybe alphabetical would be better. What do you think?)

Added beets-bpmanalyser to the list of 'other plugins'

---

beetsplug/parentwork.py
docs/changelog.rst

Otherwise, this rewrites all your files every time.

parentwork: Only call store when the metadata has changed.

---

beets/__init__.py
docs/changelog.rst

I think it is better to know than ignoring it silently. I don't know how you feel about this but I am requesting this PR because I lost a good deal of time convinced that my configuration was read only to discover that I mistyped the path. We could also opt for a 'softer' warning...

Raising error on missing configuration file inclusion

---

beets/dbcore/query.py
docs/changelog.rst
test/test_query.py

It seems like tests are not hitting this method...

Fix #3516 - Erroneous @classmethod on NoneQuery.match

---

beets/autotag/hooks.py
beets/autotag/match.py
beets/autotag/mb.py
beets/config_default.yaml
beets/plugins.py
docs/changelog.rst
docs/reference/config.rst
test/test_importer.py

Here's a first go at the "hints" behavior discussed in https://discourse.beets.io/t/providing-hints-to-autotagger/1072/10.
This adds a single `extra_tags` config parameter that, when enabled, includes the following tags in the MusicBrainz query:  `media`, `year`, `country`, `label`, `catalognum`. The selection of tags to include is somewhat arbitrary, but based on a combination of the tags I needed in my particular use case and the tags already used by `likelies` in `current_metadata`.

Support extra tags for MusicBrainz queries

---

docs/plugins/index.rst

I'm not familiar with the process for adding new plugins on the plugins page, but here's a PR in case you'd like to include it.
[`beets-originquery`](https://github.com/x1ppy/beets-originquery) integrates with the new beets [`extra_tags`](https://github.com/beetbox/beets/blob/master/docs/reference/config.rst#id70) config setting to improve autotagger results by augmenting the MusicBrainz query with locally-sourced data. This allows you to more easily enable the `extra_tags` functionality since you don't have to update the tags first; tags can simply be specified in an _origin file_. The origin file format is extremely flexible and configurable, allowing for compatibility with the wide variety of supplemental metadata files people often include with their music.

Add beets-originquery plugin

---

beetsplug/lyrics.py
docs/changelog.rst
test/rsrc/lyrics/geniuscom/sample.txt
test/test_lyrics.py

Added the null check with a unit test and sample Genius page.

Fix #3535 - Genius Null Check

---

beetsplug/lyrics.py
test/test_lyrics.py

This will handle cases where the artist name includes some
characters which can cause a search failure for some
websites - mainly unicode.
Fixes https://github.com/beetbox/beets/issues/3340.

Add artist_sort as the last entry in the artists to search

---

beetsplug/replaygain.py
docs/changelog.rst

I've moved the check into the `try` block as per the discussion in #3533.
I've also rewritten the message, hopefully it is clearer now.

Fix #3533 - crash when calculating RG/R128 mix

---

beetsplug/web/__init__.py
docs/plugins/web.rst

The QueryConverter was added without much further explanation in commit
004e9a8144cd120f6f245dd9865db469c243d34d. Unfortunately, the query
converter breaks path queries as flask cannot distinguish between an
URL encoded and a plain '/' character during routing [\[0\]][0]. Additionally,
I don't get why the QueryConverter is needed in the first place as ','
characters can just be used in the URL directly. For example:
`/item/query/foo,bar`. As conversions of slashes into comma characters
wasn't documented anyhow removing this code shouldn't cause much harm.
Fixes #3566
[0]: https://github.com/pallets/flask/issues/900

web plugin: support path queries

---

beetsplug/fetchart.py
docs/changelog.rst

The remote album art sources write into `NamedTemporaryFile`s in order to check image type and dimensions.  However, when an image fails validation, it doesn't seem to get removed from /tmp.  I was fetching art for a large library with aggressive size filters, and found a bunch of temp album art crud piling up there, so I wanted fetchart to clean up after itself a bit.
This commit introduces a `cleanup_tmp(candidate)` method on sources, which is only called on candidates that fail validation.  The `LocalArtSource` has a no-op implementation, but `RemoteArtSource` simply calls `util.remove(candidate.path)`.
There is probably some more tmp cleanup work that could be done in the future.  If you're importing with `copy` or `link`, for example, any fetched art that passes validation seems to …

fetchart: clean up invalid tmp files

---

beets/autotag/__init__.py
beets/autotag/hooks.py
beets/autotag/mb.py
beetsplug/cue.py
beetsplug/discogs.py
docs/changelog.rst
test/test_autotag.py
test/test_ui.py

New attempt at dealing with https://github.com/beetbox/beets/issues/1547 learning from errors in https://github.com/beetbox/beets/pull/2650

First try adding new albuminfo and trackinfo class

---

beetsplug/subsonicplaylist.py

Fixes a bug introduced in #3425, where "MatchQuery" is used leading to wrong songs being added to a playlist.

Fix: subsonicplaylist wrong song selection
