beetbox/beets

beets/autotag/__init__.py

Hi! 
Coming back to https://github.com/beetbox/beets/pull/3568, I tried to add a new tag (as should be much easier now) but I noticed that any changes wouldn't get applied. I eventually found out that the problem was in ```beet/autotag/__init__.py``` in ```apply_metadata```, which gets the metadata it has to apply from a list. As the tags are flexible now, this doesn't work. In this PR, I change it to: 
Do your stuff with special tags (```track_id``` becomes ```mb_trackid``` and similar adaptations)
Take all the remaining tags and apply the changes to those. 
I wonder by the way how the ```scrub``` plugin reacts to tags being flexible, I didn't look into it.

Correct beet/autotag/__init__.py to adapt to flexible tags

---

beetsplug/parentwork.py
docs/plugins/parentwork.rst

Add a new tag, ```mb_workid_current``` that is checked when performing ```beet parentwork``` to check if some works changed and update the parentworks, updating changed works without having to check all parentworks.

Fetching parentwork if changed, even if not force

---

beetsplug/lyrics.py
docs/changelog.rst
test/test_lyrics.py

As noted in #3535, Genius now doesn't always produce html pages that the existing code can scrape. While the fix in #3554 stops the lyrics plugin from completely crashing, it now simply ignores these pages, even though they do contain the desired lyrics. I added a few lines to the algorithm to deal with this new layout.
While I was at it, I also removed the indirection over the /song api, so we only need to query Genius twice per song instead of thrice.
Another change was to include the artist in the search query sent to Genius. This produces much better search results for songs with very common names but less known arists.

Scrape new Genius song page html

---

beetsplug/subsonicupdate.py

Also gets rid of warning that `port` must be `int` when it's default was a `string`.
Left over from https://github.com/beetbox/beets/pull/3449.

feat: uses new subsonic format as default

---

beetsplug/subsonicupdate.py
test/test_subsonic.py

Fixes method call error created by this: https://github.com/beetbox/beets/pull/3449
Moved the helper static functions to the `SubsonicUpdate` class and made them private static.
Added tests for various of URL input and made sure that it can create a token and format URL correctly.

fix: use `endwith()` instead of `endWith()`

---

docs/reference/cli.rst

Didn't work since $tracktotal is not an Album field

Fix `list -af` example in documentation

---

beets/importer.py
docs/changelog.rst

Call tarfile.open instead of tarfile.TarFile from the importer so that
we can import compressed tar archives.
Note that tarfile.TarFile does not handle compressed archives:
$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tarfile
>>> tf = tarfile.TarFile("Lagrimas.tar.bz2")
[...]
tarfile.ReadError: invalid header
>>>
But tarfile.open does deal with them:
$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tarfile
>>> tf = tarfile.open("Lagrimas.tar.bz2")
>>>
Tested:
$ ls Lagrimas/*.mp3 | wc -l
11
$ tar cjf Lagrimas.tar.bz2 Lagrimas/
- …

importer: use tarfile.open to handle compressed archives

---

beetsplug/lyrics.py
docs/changelog.rst

Skip ReST writing & sphinx info messages if query doesn't yield anything
* `writerest` into `appendrest` and `writerest`, don't call `writerest(item=None)` to flush state at the end.

Fix item == None issues when writing lyrics ReST (issue #2805)

---

beetsplug/plexupdate.py
docs/changelog.rst
docs/plugins/plexupdate.rst
test/test_plexupdate.py

Attempt to fix issue #2871.
Adds two new options to the `plexupdate` config:
* `secure` - boolean of whether to use secure connections or not
* `ignore_cert_errors` - boolean of whether to ignore certificate errors

feat: support secure Plex connections

---

beetsplug/fetchart.py
docs/changelog.rst

The Cover Art Archive API offers pre-resized thumbnails of cover
art. If the `maxwidth` option of `fetchart` matches one of the
supported Cover Art Archive thumbnail sizes fetch it directly
instead of fetching the full size image then resizing it.

fetchart: Use Cover Art Archive thumbnails

---

beetsplug/fetchart.py
docs/changelog.rst

Revert PR #3637 and related changes due to issue #3638.
I will reworks this to make sure it falls back gracefully if the thumbnail image doesn't exist.

Revert Cover Art Archive thumbnails

---

.github/workflows/integration_test.yaml
test/test_lyrics.py
tox.ini

Fixes #3645
Adds a weekly integration (hitting real apis) test as a github action. Also adjust `test_lyrics.py` to use the new integration tests.

Add weekly integration test github action

---

beetsplug/parentwork.py
docs/changelog.rst
docs/plugins/parentwork.rst

Get the date of the parentwork, which may be different from the date of the child work.

---

.coveragerc
.github/workflows/ci.yaml
.github/workflows/integration_test.yaml
.gitignore
appveyor.yml
setup.cfg
setup.py
test/_common.py
test/test_parentwork.py
tox.ini

Fixes #2202
So this covers a few things:
1. [Since setup.py test is deprecated](https://github.com/pypa/setuptools/pull/1878), I removed the `test_requires` section of `setup.py` in favor of putting it under `extras`. This allows us to reference the dependencies in multiple locations e.g. `tox.ini`
2. Cleans `tox.ini` a bit removing unneeded or unused code
3. Since `nose` is deprecated, I transitioned to using `pytest`
Editing the Testing wiki is on my list of to-dos and I'm just waiting until I am finished going through all the testing stuff

Testing cleanup & nose -> pytest

---

.github/stale.yml

Fixes #3656
Adds a [stale-bot](https://github.com/probot/stale) that will comment and mark issues with the `needinfo` label and > 60 days inactivity, and pull requests with > 120 days of inactivity. If no further activity occurs in a week, the bot will close the issue/pull request.
[See usage & config options](https://github.com/probot/stale#usage) 
I also sent a request to install the bot to this repository. Note the bot will not be enabled until a `stale.yml` file is present.

Add a stale-bot

---

beetsplug/lyrics.py
docs/changelog.rst

See https://github.com/beetbox/beets/issues/2969

Fix a regression in the heuristic for detecting valid lyrics from the google source

---

beetsplug/ipfs.py
docs/changelog.rst

I was looking to use the IPFS plugin, but it seemed not to be compatible with Python 3. I've made some small updates here that bring it to where the Python 2 version was.
However, this does not bring the IPFS plugin totally up to date; there is an issue with the command `beet ipfs -g <hash>`  that became apparent when testing these changes. The other commands, `-a`, `-i`, `-p`, `-l` do seem to work though.
```
$ beet ipfs -g QmWZLpxqkcH6wwD1ZnpbhpSy6jhGZub42Vv24sh9rNPXFi
ipfs: Getting QmWZLpxqkcH6wwD1ZnpbhpSy6jhGZub42Vv24sh9rNPXFi from ipfs
No files imported from /home/user/src/beets/QmWZLpxqkcH6wwD1ZnpbhpSy6jhGZub42Vv24sh9rNPXFi
File "/home/user/.local/bin/beet", line 9, in <module>
load_entry_point('beets==1.4.4', 'console_scripts', 'beet')()
File …
```

compatibility of IPFS plugin with Python 3

---

beetsplug/thumbnails.py
docs/changelog.rst
test/test_thumbnails.py

Hi,
The `thumbnails` plugin was failing for me. The following patch fixed it.
```
$ python --version
Python 3.5.7
jojo at jojo-mini in ~/code/beets (master●)
$ beet thumbnails
File "/Users/jojo/.asdf/installs/python/3.5.7/bin/beet", line 11, in <module>
load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beets/ui/__init__.py", line 1266, in main
File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
File "/Users/jojo/.asdf/installs/python/3.5.7/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 78, in process_query
self.process_album(album) …
```

fix bug with pathlib

---

beetsplug/discogs.py
beetsplug/playlist.py
setup.cfg

Un-ignore flake8 errors that required zero or minimal change to the codebase.
See [the discourse discussion ](https://discourse.beets.io/t/updating-the-errors-we-ignore-with-flake8/1393)

Unignore flake8 E221, E226, E242, E704

---

.github/workflows/ci.yaml
.github/workflows/integration_test.yaml

Adds CI tests for development versions of python3.9
[Support to the github action was just recently added.](https://github.com/actions/setup-python/issues/20#issuecomment-660026867)
Hopefully, this will help us catch errors like https://github.com/beetbox/beets/pull/3621 in the future
Fixes: #3622

Add python 3.9-dev to CI tests

---

docs/plugins/fetchart.rst

update link from defunt page the plugin's current homepage
Fixes #X.  
(...)

update link to current homepage

---

CONTRIBUTING.rst

[discussion](https://discourse.beets.io/t/writing-tests-with-pytest/1435)
Clarifies test writing policy
I think the basics sections is fairly self explanatory at this point especially with the copious amounts of examples we have. Also, if we kept it, we'd have to expand on pytest basics as well. I'd rather just point to the docs/getting started guides for each.
This was quick, but I'm super excited about it.

Update pytest test writing restriction

---

.github/workflows/integration_test.yaml

This PR adds a step to our integration tests to send a message to our Zulip instance if the tests fail:
I've currently configured the step to post to #general, but @jtpavlock has suggested we create a new #github stream for this instead (which sounds good to me).
To set up this bot properly, someone on our Zulip instance (preferably @sampsyo) will need to create a bot by going to `Settings → Your bots`, and then set the `ZULIP_BOT_CREDENTIALS` GitHub secret to `bot email:api key`.

Notify Zulip chat on integration test failure

---

test/test_lyrics.py
tox.ini

Genius seems to be using Cloudflare, which blocks requests from GitHub actions. I've disabled Genius on GitHub actions in this PR, which allows our integration tests to pass.

Skip Genius integration test on GitHub actions

---

.github/flake8-problem-matcher.json
.github/workflows/ci.yaml

This PR implements the flake8 half of #3614 using a [problem matcher](https://github.com/actions/toolkit/blob/1cc56db0ff126f4d65aeb83798852e02a2c180c3/docs/problem-matchers.md), giving us nice inline errors like this on PRs:
I've had to disable `PY_COLORS` here, as the ANSI escape sequences were tripping up the regex used in the matcher.

Add flake8 problem matcher

---

.github/sphinx-problem-matcher.json
.github/workflows/ci.yaml

Fixes #3614. This PR implements the remaining sphinx half of #3614 using another problem matcher, giving us more nice inline errors like this on PRs:
Oddly enough, it seems like the errors reported by sphinx are for the first line of the paragraph containing the error, instead of the actual line of the error:
I don't know if there's much we can do about this, as it looks like it's a problem with sphinx itself.

Add sphinx problem matcher

---

beetsplug/mpdstats.py
docs/changelog.rst
test/test_mpdstats.py

MPD keeps the current track in the queue when stopping, so it's not
really like a skip, and I use it so that I can stop the music, and later
start at the beginning of a track.
I do this by keeping track of the current song id, and then comparing
them when we receive a stop signal.
Fixes #3722 .

mpdstats: Don't record a skip when stopping MPD.

---

beetsplug/chroma.py
docs/changelog.rst

This should be pretty self-explanatory.
I noticed that the file metadata was only updated when I used the `fingerprint` command, but not if I used the `submit` command and it generated the fingerprints while doing so. In the latter case, the database was updated, but the files were only updated after I ran `write` afterwards.
I must admit that I'm not fully sure if this is the intended behavior or not, but I thought creating this Pull Request shouldn't hurt, seeing as I fully expected its behavior to stay the same (i.e. to update the file after updating the database), regardless of whether it was triggered directly by `fingerprint` or indirectly via `submit`.
This PR makes the third argument match [this one](https://github.com/beetbox/beets/blob/06e7453a6066813edc68f888aab0e3e5806b6db7/bee …

Update file metadata after generating fingerprints through the `submit` command.

---

beets/ui/commands.py
docs/changelog.rst

When importing duplicate flac files, it is often less important what the bitrate is and more important the sample rate and bit depth. My change adds this for flac files for convenience

Added flac-specific samplerate-bitdepth reporting for duplicate imports

---

beetsplug/fetchart.py
docs/changelog.rst
test/test_art.py

Instead of blindly selecting the first image, we now treat all "front" images as candidates.
This is useful where some digital releases have both an animated cover and a still image and the animated image is the first image returned from the API.
Example release: https://musicbrainz.org/release/dc20e054-0177-4652-b6e7-fe0c193ea8dd

fetchart: Improve Cover Art Archive source.

---

beets/ui/__init__.py
beets/ui/commands.py
docs/changelog.rst
docs/reference/cli.rst
test/test_ui.py

I just wanted to remove a few individual tracks from my library, for which a query was not simple to construct. As it turns out, the `remove` command wasn't very helpful in this case. Hence, this adds interactive selection of items to the `remove` command, analogously to item selection in the `modify` command. The `yes/no` answers to the prompt work as before, and the `select` answer is added. Thus, there's no change of previous behaviour.
I also changed the output when `-a` is given to group albums more clearly.

Add possibility to select individual items to the remove CLI command

---

beetsplug/export.py
docs/changelog.rst
docs/plugins/export.rst
test/test_export.py

This adds support for the JSON Lines format as documented at
https://jsonlines.org/.
In this mode the data is output incrementally, whereas the other
modes load every item into memory and don't produce output until
the end.

export: Add --format=jsonlines option

---

beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst
test/test_lyrics.py

[LyricWiki was shut down on 2020/09/21 and no longer serves lyrics.](https://en.wikipedia.org/wiki/LyricWiki#Edit_lock_and_closure)
The integration tests on our CI have been failing because of this.

Remove LyricWiki source

---

docs/plugins/chroma.rst

Links were swapped and pointing to wrong locations. This re-swaps them so they point to the correct locations.
- [N/A] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [N/A] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)
- [N/A] Tests. (Encouraged but not strictly required.)

Swap links

---

docs/conf.py

It looks like the existing GitHub user page regex wasn't quite right - I've updated this to match anything at the top-level of GitHub (it was missing usernames containing hyphens before).
I've added genius to the link ignore list too, as they're still blocking GitHub actions (see #3713).
Here's hoping this is the final nail in the integration test failure coffin 💪

Fix linkcheck on GitHub actions

---

.github/ISSUE_TEMPLATE/bug-report.md
beets/ui/__init__.py
docs/changelog.rst
docs/reference/cli.rst

This PR adds a `--plugins` flag to beets, allowing enabling/disabling of plugins without adding them to the user's configuration.

Add --plugins flag

---

beets/util/artresizer.py
docs/changelog.rst

Fixes #3743.
It seems like specifying an image quality of 0 to PIL when saving a JPEG generates an image with the lowest possible quality, instead of using PIL's default quality of 75.
```Python
from PIL import Image
im = Image.open("./beet.jpg")
im.save("./beet_modified.jpg", quality=0)
```
<table>
<thead>
<tr>
<th>
<code>beet.jpg</code>
</th>
<th>
<code>beet_modified.jpg</code>
</th>
</thead>
<tbody>
<tr>
<td width="50%">
</td>
<td width="50%">
</td>
</tr>
</tbody>
</table>

Fix PIL image quality

---

beets/autotag/mb.py
docs/changelog.rst

Fixes #3053.
This used musicbrainz tags to populate the genre album tag.  This is still a WIP, and it requires this PR (https://github.com/alastair/python-musicbrainzngs/pull/266).  Let me know if anyone has any ideas on how this could work better.  Currently I just take the most-voted-for genre tag, breaking ties arbitrarily.

Add genre support using musicbrainz tags.

---

beets/dbcore/types.py
docs/changelog.rst
test/test_lyrics.py

This is an attempt to fix #3773 by more aggressively normalizing values for dbcore's `String` type.

Try normalizing the dbcore String type

---

beets/autotag/mb.py
beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst

This is a followup for #3781, adding a config option.
Let me know if I did anything wrong or missed anything, this is my first time adding a config option.

Add use_mb_genres config option.

---

beetsplug/fish.py

Change the fish plugin to escape "?" in the completions file, without escping ? is interpreted as a regex and creates lots of errors that interfere with the actual useful completions.
This PR introduces changes to escape "?" in the command names in fish.py to ensure working completions.
EDIT: I am not sure whether this should go into the changelog as the fish plugin is not even included in the latest release.

escape ? in fish completion

---

docs/changelog.rst
docs/plugins/index.rst

based on https://github.com/sbarakat/beets-copyartifacts/commit/63776efebe4da38c31d9583110614ca2bf402f3d sbarakat/beets-copyartifacts is no longer maintained. The repo suggest 2 beets plugins alternative, https://github.com/adammillerio/beets-copyartifacts, a fork of the repo and https://github.com/Holzhaus/beets-extrafiles another plugin to manage files. i choose the fork to replace the old repo and change the link name.
i can also add Holzhaus/beets-extrafiles if required.
- Tests. (Encouraged but not strictly required.)

change copyartifact doc

---

beets/config_default.yaml
beets/importer.py
beets/library.py
beets/util/__init__.py
docs/changelog.rst
docs/dev/plugins.rst
docs/reference/config.rst
setup.py
test/_common.py
test/test_files.py

(Would fix #2642) Rebased #2720 on master, thus supersedes #2720.
Outstanding discussion points:
@sampsyo 
> It might be useful to see the evolving discussion in #2785, but I think raising a custom exception or a FilesystemError from the utility function itself is the right thing for util. Then, to actually show the problem to the user—if we want to stop the program altogether—higher levels in the stack should probably catch this at an opportune moment and raise a UserError.
>
> Of course, if we wanted the same behavior as for trying to write to a read-only filesystem, for example, then just keeping it as a FilesystemError would be the right thing.
I will do the exception thing the coming hours.

Add reflink option

---

beetsplug/keyfinder.py
docs/changelog.rst
test/test_keyfinder.py

Fixes #2242 
When you run `keyfinder-cli` on some files (in my testing, files that are either corrupted or silent in some way), it will exit with 0 but return an empty output for the key. This caused an IndexError when attempting to access an index in the resulting empty array.
This PR adds exception handling for this case, where it just logs that it happened and continues. It also adds a unit test for this case.

keyfinder: Catch output from keyfinder-cli with no key

---

beets/plugins.py

This function is called from library.Item._getters(), making it a hot
path when exporting data. We cache plugin instances but previously we
reran `import` for each module on each call. We now return the cached
values providing a speed boost for `beet export`.
This has a small effect on `beet ls` speed: for me it went 11.00s ->
10.40.
It had a significant effect on `beet export` speed when combined with
https://github.com/beetbox/beets/pull/3762/.
Before:
$ time /home/sam/.local/bin/beet 'export' '--library' '--format' 'jsonlines' '--include-keys' 'artist,title,path,mb_artistid,mb_trackid' 'artist+ title+' > /dev/null
Executed in   25.13 secs
After:
$ time /home/sam/.local/bin/beet 'export' '--library' '--format' 'jsonlines' '--include-keys' 'artist,title,path,mb_artistid,mb_trackid' …

Use caching in plugins.find_plugins()

---

beetsplug/lastgenre/__init__.py
docs/changelog.rst
docs/plugins/lastgenre.rst

This makes the `lastgenre`'s title casing behaviour optional to stay truer to the whitelist tag formatting

lastgenre: Make TitleCasing optional

---

beetsplug/fish.py

The `_escape` helper was introduced in https://github.com/beetbox/beets/pull/3792, specifically 57a1b3aca86253d130848fdfcd2accbed861b5ee, but the omission of a `return` statement means that the function always incorrectly returns `None`. This causes `beet fish` to error when it eventually attempts to concatenate the value with a string:
```
File "/home/linuxbrew/.linuxbrew/bin/beet", line 8, in <module>
sys.exit(main())
File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/beets/ui/__init__.py", line 1278, in main
File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/beets/ui/__init__.py", line 1265, in _raw_main
File …
```

Fix escape helper in fish completion plugin

---

test/test_replaygain.py

Removes the `_store_retry_once` hack in favor of using an on-disk database, we have support for that in the test harness already.
Accessing the database from a new thread opens a new connection, with the `:memory:` path, that actually creates a per-thread database. Presumably, even with the `OperationalError`, the first store actually created the missing the table which let the second store succeed.
Closes: #3809

replaygain: Use on-disk database

---

beetsplug/replaygain.py
docs/changelog.rst
docs/plugins/replaygain.rst

Add an additional config parameter to enable parallelism on import. Defaults to `False` because this functionality is unpredictable and should be opt-in for now.

Disable replaygain parallelism during import

---

_layouts/main.html

Should fix youtube video now shown on github.io page when using https due to using http within https
https://beets.io/
vs
http://beets.io/
(...)

fix youtube video when using https

---

beetsplug/discogs.py
docs/changelog.rst

This PR fixes the behavior of the ``index_track`` option of the discogs plugin.
Currently, it only works when index tracks are of type "heading" in the discogs listing (like in https://www.discogs.com/Handel-Sutherland-Kirkby-Kwella-Nelson-Watkinson-Bowman-Rolfe-Johnson-Elliott-Partridge-Thomas-The-A/release/2026070), but not when they are of type "index" (like in https://www.discogs.com/fr/Glenn-Gould-Columbia-Symphony-Orchestra-Vladimir-Golschmann-Bach-The-Concertos-For-KeyboardClavier-S/release/10142332).
This is because index tracks are removed in function ``coalesce_tracks``. The fix is simply to keep them when there is no subtrack merging.
This also removes the semicolon when there is no index track. Currently, when the option is on, every track title will start with " : " when …

discogs plugin: fix index_track option

---

beetsplug/mpdstats.py
docs/changelog.rst

Fixes #3798.
Adds a check for Python 2/3 as to pass the correct init arguments to MPDClientWrapper. This removes the warning:
```
test/test_mpdstats.py::MPDStatsTest::test_update_rating
/home/andrew/Documents/beets/beetsplug/mpdstats.py:55: DeprecationWarning: use_unicode parameter to ``MPDClient`` constructor is deprecated
self.client = mpd.MPDClient(use_unicode=True)
```
~~Do the dependency constraints for python-mpd2 in setup.py need to be adjusted at all? Could there be a scenario where a user is using some version of Python 3 along with python-mpd2<2.0.0 that could cause issues?~~

Add Python version check for mpdstats

---

beets/autotag/mb.py
docs/changelog.rst

Fixes #3308. 
```musicbrainzngs.get_release_by_id``` doesn't provide all data beets asks for when a release has more than 500 tracks. I use ```musicbrainzngs.browse_recordings``` as a complement to ```musicbrainzngs.get_release_by_id``` for releases with more than 500 tracks to get the missing data. It doesn't work perfectly yet, mainly because ```musicbrainzngs.browse_recordings``` does not allow to fetch quite the same data than  ```musicbrainzngs.get_release_by_id``` (notably, ```work_level_rels``` and ```aliases``` are missing for reasons I don't quite understand) but it's already much better and on the day ```musicbrainzngs.browse_recordings``` does fetch this data, the update should be trivial.

Fetch data for releases with more than 500 tracks

---

beetsplug/convert.py
docs/changelog.rst

Builds on  #3153 
parallelizes convert using par_map on python3

convert: uses new par_map to work in parallel

---

beetsplug/chroma.py
docs/changelog.rst

Fixes #3834
Tracks which have already been fingerprinted do not return to be used by `beet submit` (part of the Chroma plugin). This results in  submission errors, as the fingerprint is omitted from the resultant payload sent to acoustID.

Fixes #3834: Submitting AcoustID information for tracks which already have a fingerprint

---

beets/util/pipeline.py

`PipelineThread.__init__()` already initializes this lock:
https://github.com/beetbox/beets/blob/109b547f7a85f5403a63d63d18d8bcb4ca815dc8/beets/util/pipeline.py#L211-L218

pipeline: remove duplicate code from previous refactoring

---

beetsplug/replaygain.py
docs/changelog.rst
test/test_replaygain.py

References in the documentation to this plugin were removed in beetbox/beets#3127 (beetbox/beets#3130) but no actual code changes were made.
This PR removes support for this dependency entirely.
Fixes #3127.

Removes support for bs1770gain.

---

beetsplug/mpdstats.py
docs/changelog.rst
docs/plugins/mpdstats.rst

Add `strip_path` option to mpdstats plugin. Combined with `music_directory` option it can help mangling the path received from MPD daemon to match beets library one.

Add strip_path to mpdstats

---

beetsplug/discogs.py
docs/changelog.rst
docs/plugins/discogs.rst
setup.py

discogs-client has been deprecated since June 2020, the replacement
is actively developed by the community and does not have any breaking
API changes.
Signed-off-by: George Rawlinson <george@rawlinson.net.nz>
Fixes #3608.

Fix #3608: Replace discogs-client with python3-discogs-client

---

beets/autotag/hooks.py
beets/autotag/mb.py
beets/library.py
docs/changelog.rst
test/test_mb.py

fixes beetbox/beets#1904
Fixes #1904.
(...)

Add trackdisambig from musicbrainz.

---

docs/changelog.rst
test/test_web.py

Adds a few tests for parts of the web plugin API not previously covered. In particular, for the
`/album/<n>?expand` request and the `/stats` request.
No new features or documentation required. changelog updated.
Signed-off-by: Graham R. Cobb <g+beets@cobb.uk.net>

Improved test coverage for web plugin JSON API

---

beetsplug/web/__init__.py
docs/changelog.rst
docs/plugins/web.rst
test/test_web.py

Fixes #3866.  
Change web/__init__.py to only remove `artpath` if `include_paths` is false.

Web artpath fix

---

beetsplug/aura.py
docs/changelog.rst
docs/plugins/aura.rst
docs/plugins/index.rst

This is a server implementation of an [AURA](http://https://auraspec.readthedocs.io) server.
``tox -e lint`` fails (see [here](https://github.com/beetbox/beets/runs/1145869325)), which would be easy enough to fix but puzzles me because no other plugins with the same "problems" cause an error. Does anyone know what's up with that?

AURA: Add aura plugin and docs

---

beetsplug/web/__init__.py
docs/changelog.rst
test/test_web.py

Fixes #3867. 
After discussion in #3867, this fix prevents replacement of `\` in web queries if and only if they include `::`, indicating that they are regex queries.
Several new tests have been created to test various queries of items and albums.
No documentation changes as this is expected behaviour.

Web regex fix

---

beetsplug/web/__init__.py
docs/changelog.rst
docs/plugins/web.rst
test/test_web.py

Fixes #3870
This PR adds a new web configuration option ``readonly``. If ``readonly`` is true (the default)
only _GET_ operations are allowed. ``readonly`` must be false to allow _DELETE_ or _PATCH_ operations.
**NOTE**: this is a change, which may break existing users of the _DELETE_ or _PATCH_ operations, but after discussion in #3870 it was decided that the default has to be read only. Re-enabling them is just a matter of adding ``readonly: no`` to the web configuration.

Web readonly

---

beetsplug/bareasc.py
docs/changelog.rst
docs/plugins/bareasc.rst
docs/plugins/index.rst
test/test_bareasc.py

Create prototype plugin for "bare-ASCII" matching query. Plugin is called bareasc and defaults to using # as the prefix.
For investigation and further discussion in feature request #3882.

Experimental "bare-ASCII" matching query

---

beetsplug/discogs.py

Fixes https://github.com/beetbox/beets/issues/1051 (and maybe a reoccurrence of https://github.com/beetbox/beets/issues/2387)
As described in [this comment](https://github.com/beetbox/beets/issues/1051#issuecomment-800584218) I encountered a `TypeError: sequence item 0: expected str instance, bytes found` error, and it seems the step to encode to ascii is no longer required. Removing it resolved this issue for me.

Remove ascii encode step

---

beets/library.py

... for keys that exist both as Item and Album fields
Fixes #3880

when iterating over item keys, do not return duplicates

---

beets/ui/__init__.py

See https://github.com/beetbox/beets/issues/3880#issuecomment-801844630
```
I didn't actually benchmark this, but creating new FormattedItemMapping
views in each iteration of the loop appeared like a rather inefficient
way of doing things. In reality, this is probably completely irrelevant,
since one would usually not show huge numbers of changed Models at a
time.
```

slight performance optimization for ui.show_model_changes

---

beets/library.py

Shouldn't be a user-facing issue, but this took me a while to figure out while debugging.
I'm not sure about what exactly was going on, but it involved pytest trying to `repr()` some function arguments when logging an exception, and that then resulted in a deadlock.

Avoid deadlocks in Item.__repr__

---

beets/ui/__init__.py
docs/changelog.rst

This seems like the simplest fix we can do to achieve this.
I think there may be something else wrong here though - should we be using `util.text_string()` to decode arguments without specifying an encoding (defaulting to `utf-8`)? It looks like `beets modify` uses `decargs` instead, which actually uses `util.arg_encoding()` as the encoding.
I'm not sure if it's worth merging this functionality between `modify` and `import`, as it seems to work slightly differently and it is just a `x.split('=', 1)` anyway.
Fixes #2984.

Allow equals within import --set value

---

.github/workflows/ci.yaml
tox.ini

We lost the ability to show skipped tests when transitioning to gh actions. As it turns out, all of the replaygain tests were being skipped, so as a start, try to install at least one backend.
Let's see whether installing ffmpeg actually works, I don't really know what I'm doing regarding Github actions.

ci: install ffmpeg for replaygain tests; show skipped tests

---

.github/workflows/ci.yaml

Hopefully, this helps to spot breaking changes early. Unfortunately, the UI appears to be somewhat lacking: https://github.com/actions/toolkit/issues/399

ci: also run on latest Python alpha, but allow failure

---

docs/changelog.rst

While we're at it, we might announce the intent to drop 3.5 together with 2.7.

Warn about dropping Python 3.5 support in the changelog

---

beetsplug/lyrics.py
docs/changelog.rst

Sometimes Musixmatch lyrics come in 2 parts.
Also, sometime non-existent lyrics return some content
* Fix for lyrics that divided into 2 or more <div> elements.
* Ignore "fake" lyrics when lyrics not found but some content still being retrieved.

Fix for Musixmatch multi-part lyrics

---

beetsplug/lyrics.py
docs/changelog.rst

Fixes #3904 
Did mange to reproduce the specific error the user saw
* Fixed cases where false positives occurred for certain searches such as https://www.tekstowo.pl/szukaj,wykonawca,Boy+In+Space,tytul,Hsafjsahfkjsahfkl.html
* Fixed additional edge-case found while testing

Fix falso positive lyric pages for Tekstowo

---

.github/workflows/ci.yaml

Changes `ci` workflow to only run when:
- A push to `master` happens
- A pull request gets opened and it's base is `master`
- This will also kick of sequential `ci` runs if the branch is updated (synchronized: GitHub's terminology)
This makes for deduping the checks ran.

ci: scope ci workflow

---

beets/dbcore/db.py
beets/library.py
beetsplug/export.py
beetsplug/info.py
docs/changelog.rst
docs/plugins/info.rst
test/test_info.py

This changes greatly improves the speed of `beet export` and `beet info`
when the `--include-keys` option is used.
Listing all fields for an item requires querying the database to find
any flex attributes. This is slow when done for every item being
exported. We already have a way for the user to specify a fixed set
of keys, but we previously queried everything and filtered it afterwards.
The new approach is more efficient.
Code that iterates through all fields now have to handle invalid field
names. The export and info plugins output invalid fields as None.
Timings before:
> /usr/bin/time beet export -i title,path,artist -l  Bob Dylan
13.26user 20.22system 0:34.01elapsed 98%CPU (0avgtext+0avgdata 52544maxresident)k
> /usr/bin/time beet export -l  Bob Dylan
12.93user 20.15system …

Optimise FormattedMapping when querying a specific set of fields

---

beets/autotag/mb.py
beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst

Enable HTTPS for musicbrainz.org API access by default. I noticed that beets was using HTTP with no way for the user to change this.
This patch does change default behavior since the use_https configuration option is set to yes by default. Setting this to no by default might be more appropriate.

Add HTTPS support/configuration option for Musicbrainz

---

docs/changelog.rst
docs/reference/cli.rst

Remove reference to rarfile version in pypi link in `cli.rst`

Remove reference to rarfile version in link

---

beets/autotag/mb.py
beets/library.py
docs/changelog.rst

This adds ISRC information as a tag.  There are a couple of TODO I could use input on.

Add ISRC identifiers from musicbrainz.

---

beetsplug/metasync/itunes.py
docs/changelog.rst
test/test_metasync.py

This adds `itunes_dateadded` to the metasync plugin.

Add itunes_dateadded to metasync plugin

---

test/rsrc/lyricstext.yaml

Fixes integration test failures caused by missing tekstowo test data (https://github.com/beetbox/beets/runs/2647894205).

Add missing test data for tekstowo

---

docs/changelog.rst
docs/index.rst

Resolves https://github.com/beetbox/beets/discussions/3953
freenode has had a hostile takeover (see [DWF CVE-2021-1000189](https://github.com/distributedweaknessfiling/dwflist/blob/main/2021/1000xxx/CVE-2021-1000189.json)) and the network is no longer safe. This PR sets out to document Libera.Chat as our new home on IRC.
(Nothing to test.)

Document Libera.Chat as the new official IRC home

---

beets/library.py
docs/changelog.rst
test/test_types_plugin.py

Fix ifdef behavior with non-string fields (bug #3852)

---

beetsplug/duplicates.py
docs/changelog.rst

Fixes the remainder of https://github.com/beetbox/beets/issues/3943 now that #3930 was merged.
Fixes #3943

duplicates: fix crash on empty query

---

_layouts/main.html

The website still pointed to freenode. Do we have a log bot around? (@Freso ?) For now, I've removed the link since `botbot.me` appears to be defunct.

update irc link: freenode -> libera

---

beetsplug/lyrics.py

I experienced a failure to parse Tekstowo for song lyrics. 
This patch allowed the lyrics plugin to fetch the lyrics from another provider as opposed to failing.
No bug was reported before this patch was generated

return None for lyrics if Tekstowo fails to extract lyrics

---

beetsplug/lyrics.py
docs/changelog.rst

Follow up to https://github.com/beetbox/beets/pull/3994, see the comments there, and the message for the second commit in this PR:
```
The previous code had the potential to crash if (when?) Tekstowo changes
their website structure sufficiently.
The new code is rather ugly due to the explicit checks after each and
every function call. Unfortunately, the alternative would be to catch a
bunch of very generic Exceptions (AttributeError, ...), since there's no
such thing as a `BeautifulSoupNotFoundError`.
```

Crash-resilient Tekstowo lyrics source

---

docs/plugins/index.rst

As briefly mentioned in #3793, this PR adds a reference to the up-to-date bandcamp autotagger.
I additionally ordered the external plugins list alphabetically to make it a bit easier to
navigate.

Add reference to an external beetcamp autotagger in the docs

---

beetsplug/smartplaylist.py
docs/changelog.rst
docs/plugins/smartplaylist.rst

This commit introduced a way to generate a stream-frienldy playlists.
This is that I've missed to make me very happy at #3847
~Right now current code encodes at least at python `3.8.7` a string `Ayọ` as `Ayo%CC%A3` when it should be `Ay%E1%BB%8D`.~
~Until it is fixed I ask to don't merge it. @sampsyo if you have any idea how to fix it I'll be appreciated.~

Stream-friendly smart playlists

---

test/test_ui.py

Fixes #4037.
The `test_cli_config_file_loads_plugin_commands` test uses beets' normal plugin loader to load a test plugin, however it never tidies up after itself. This leads to any future plugin loads being ignored until the next `unload_plugins` call.
I'm not entirely sure why or how this is passing on our CI at the moment (or on my local machine when running all tests), as it looks like this would have been broken for a while. I'm also not sure why it only affects this test - others should also be impacted by the fact that the `zero` plugin is not loaded.
This PR changes the config tests so that we always call `load_plugins` on setup (to store the default beets state) and `unload_plugins` on teardown (to restore the previously stored state).
You can reproduce the failure by just …

Unload plugins in UI config test

---

beets/autotag/mb.py
docs/changelog.rst
docs/reference/config.rst

This adds the votes from each.
This also changes the behavior to reset genre tags if the genre option is
enabled and no tags are received from musicbrainz.
This also sorts genres by the number of votes.
This is typically more useful because release-groups are usually better tagged, and now the %first function can be used to get the most popular genre tag.  Let me know if there are any other improvements I could make here.

Get genres from both musicbrainz releases and release-groups.

---

docs/plugins/index.rst

Adds [beets-importreplace](https://github.com/edgars-supe/beets-importreplace) to external plugins list. See #4047.

Add beets-importreplace to external plugins list

---

beetsplug/albumtypes.py
docs/changelog.rst
docs/plugins/albumtypes.rst
docs/plugins/index.rst
test/test_albumtypes.py

Added a plugin to add a configurable album template field `$atypes` to format `albumtypes` of an Album (see #4045).
Should I rename the plugin to `atypes` since that's the field it adds, and to reduce possible confusion with the actual field `albumtypes`?

Add plugin for formatting albumtypes

---

docs/plugins/albumtypes.rst

Was just admiring how the documentation looks on the website; noticed a couple of typos. The extraneous bracket is nothing, but misspelling Pink Floyd? Blasphemy!

Fix typos in `albumtypes` plugin docs

---

beetsplug/permissions.py
docs/changelog.rst
test/test_permissions.py

This change makes the permissions plugin set the album art file permissions to the configurable file permissions whenever the `set_art` event is triggered.

permissions: set album art permissions

---

docs/reference/config.rst

Fixes #929.
This was proposed but never dealt with, so after going through some confusion around this myself I figured it's about time.

Add additional asciify documentation

---

docs/guides/main.rst

Make sure all installation instructions have similar formatting.
Previously, the Fedora instructions stood out.
_Not sure any of the below are applicable?_ 🤔

Docs: improve formatting of the Getting Started guide

---

docs/faq.rst

It's another installation option that may be useful.
See also:
https://github.com/beetbox/beets/issues/4027#issuecomment-932232208

FAQ: Add another option for installing in editable mode

---

CONTRIBUTING.rst
docs/conf.py
docs/plugins/spotify.rst

As the integration tests show, some of our links are rotting...
...also, sphinx is trying to access AURA at 127.0.0.1.

docs: fix links that were failing sphinx' linkcheck

---

beetsplug/export.py

Removes a `TODO` comment that was completed in #4124 (but I didn't notice the comment in the code until after it was merged and I was looking at the file again later :facepalm:).

Remove completed TODO item

---

beets/util/__init__.py

The idea of this changes is simple: let move file to some temporary name inside distance folder, and after the file is already copy it renames to expected name.
When someone tries to save anything it also moves file to trigger OS level notification for change FS.
This commit also enforce that `beets.util.move` shouldn't be used to move directories as it described in comment.
Thus, this is fixed #3849

Introduce atomic move and write of file

---

beets/util/artresizer.py
beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst

Introduces an option to force an image format, as some IEMs (notably, Rockbox) might lack support for some image formats.
I want to do tests, but I am unsure as to how to implement a test that changes the resulting cover file name.
PS: there might be a bug in cleanup of the temporary files here, however, my `/tmp` is too polluted to test, so consider this a call for help. I also don't have Windows anywhere to test on.

Add option to convert cover art file format.

---

beets/library.py
docs/changelog.rst
test/test_library.py

This allows to use flexible attributes as aunique keys.
Example: `foo%aunique{albumartist album,flex}`
Result using fast query: `foo_no such column_ flex_`
Result using slow query: `foo [flex1]`
Fixes #2678
Fixes #3553

Use slow queries for flexible attributes in aunique (fix #2678, close #3553)

---

beets/ui/__init__.py
docs/changelog.rst

Making these types and queries available is part of fully loading the plugins,
so the event should not be sent until this work is done. This allows plugins
to make use of those types and queries in a pluginload listener.

Send the pluginload event after types and queries are available

---

beets/dbcore/query.py
docs/changelog.rst

This improves the performance of `dbcore.AndQuery.match` and `dbcore.OrQuery.match`.
They would evaluate all queries and construct a list of all query results and then pass that list to `all` / `any`.
This modification passes a generator to `all` / `any`, which allows to stop querying at the first false / true result (short-circuit evaluation).
I guess we could also code the whole loops so that we do not run into the same issue accidentally.
Fixes #4145
Related to #2388 ?

Use short-circuit evaluation in AndQuery and OrQuery (fix #4145)

---

test/test_library.py

Unit test may fails when path to temprorary library contains `.`; to garantue that bug wasn't here, it forces to use one more `.` inside path.
Fixes: https://github.com/beetbox/beets/issues/4151

Prevent fails of tests when path contains dots

---

beets/library.py
docs/changelog.rst
docs/dev/plugins.rst

This works similarly to the existing 'item_removed' event but is called with an `Album` object.
My primary goal for writing this is to scratch my own itch. I'd like to update the `mbcollection` plugin to support automatically removing albums when an album is removed from the library. There was no easy way to do this (e.g. you have to use the `item_removed` event and keep track of all the items in an album) so here we are 😄 
It's been a while since I've had a look at the code so please feel free to let me know if this is the correct way to approach this.

Add an 'album_removed' event.

---

beetsplug/aura.py
docs/changelog.rst

When constructing paths to image files to serve, we previously spliced strings from URL requests directly into the path to be opened. This is theoretically worrisome because it could allow clients to read other files that they are not supposed to read.
I'm not actually sure this is a real security problem because Flask's URL parsing should probably rule out IDs that have `/` in them anyway. But out of an abundance of caution, this now prevents paths from showing up in IDs at all—and also prevents `.` and `..` from being valid names.
Closes #4111.

aura: Sanitize filenames in image IDs

---

.gitignore

lib64/ was already included, but sometimes lib64 is a symlink to lib/

Add lib64 to .gitignore

---

beetsplug/lyrics.py
docs/changelog.rst

Currently, the Genius lyrics search does not work.
It throws the following error for all files I tried:
```
lyrics: Genius failed to find a matching artist for <artist>
```
I tested it locally and I now see:
```
lyrics: got lyrics from backend: Genius
lyrics: fetched lyrics: <song>
```

[Lyrics] Genius uses query param not body

---

beetsplug/unimported.py
docs/changelog.rst

Adds a default value for the new option introduced in #4086 . Without this, the plugin requires you to set it:
```
$ beet -vv unimported
user configuration: /home/sjung/.config/beets/config.yaml
data directory: /home/sjung/.config/beets
plugin paths:
inline: adding item field disc_track_padded
Sending event: pluginload
library database: /home/sjung/music/beets.db
library directory: /home/sjung/music
Sending event: library_opened
configuration error: unimported.ignore_subdirectories not found
```

Add default for unimported.ignore_subdirectories

---

beetsplug/kodiupdate.py
docs/changelog.rst
docs/plugins/kodiupdate.rst

Fixes #4101
* Read `kodi` configuration as an array and handle all configured instances.
* Backwards compatible with previous config (non-array single instance)
* When failing to connect to/update an instance, log and move on to the next one instead of bailing at the first failure

kodiupdate: Support multiple instances

---

beetsplug/spotify.py
docs/changelog.rst

Basically, keep fetching tracks until there are no more available for
the specified album.
Fixes #4180 .
I tested this by locally importing some albums, but please let me know if you want more extended tests. I am not sure how to write them, though.
EDIT: Fix issue number.

fix spotify pagination

---

beetsplug/limit.py
docs/changelog.rst
docs/plugins/index.rst
docs/plugins/limit.rst
setup.cfg
test/test_limit.py

The `limit` plugin adds the command `lslimit` and the query prefix `<` for limiting query results to the head or tail. (Tail is supported by command only.) 
The impetus for this change was for `smartplaylists` with size limits. Such a feature has been requested before and there looks to have long been talk about this behavior through pagination (see #750).

Limit plugin

---

beetsplug/web/__init__.py
docs/changelog.rst

The routing map translator `QueryConverter` was misconfigured:
* decoding (parsing a path): splitting with "/" as tokenizer
* encoding (translating back to a path): joining items with "," as separator
Instead the encoding should have used the same delimiter (the slash) for the backward conversion.
How to reproduce:
* query: `/album/query/albumartist::%5Efoo%24/original_year%2B/year%2B/album%2B`
* resulting content in parsed argument `queries` in the `album_query` function:
* previous (wrong): `['albumartist::^foo$,original_year+,year+,album+']`
* new (correct): `['albumartist::^foo$', 'original_year+', 'year+', 'album+']`
I am not sure, why the issue was not noticed before. Maybe `werkzeug`s handling of routing maps has changed.

beetsplug/web: fix translation of query path

---

beetsplug/convert.py
docs/changelog.rst
test/test_convert.py
test/test_hook.py
test/test_play.py
test/test_query.py
test/test_ui.py

Makes the import converter respect the quiet and pretend flags.
When the `delete_originals` is set, beets prints the following, regardless of the presence of the quiet parameter:
```
convert: Removing original file /path/to/file.ext
```
This PR ensures that the log is only printed when quiet is not present.
In addition, I noticed that some tests were annotated with the following:
```python
@unittest.skipIf(sys.platform, 'win32')  # FIXME: fails on windows
```
I believe the first parameter to this annotation is a condition and the second a description, which means the tests were always skipped regardless of platform. I corrected these annotations to be
```python
@unittest.skipIf(sys.platform == 'win32', 'win32')  # FIXME: fails on windows
```

Makes the import converter respect the quiet and pretend flags

---

beetsplug/lyrics.py
docs/changelog.rst

Fixes #4228, #4161
Used to include some non-lyrics content in the lyrics, see e.g. https://www.tekstowo.pl/piosenka,au_revoir_simone,crazy.html

Minor fixes to lyrics scrapers

---

beetsplug/discogs.py
docs/changelog.rst
docs/plugins/discogs.rst

Fixes #4222.
- When files are missing both, album and artist tags, the Discogs metadata
plugin sends empty information to the Discogs API which returns arbitrary
query results. The resulting "Candidates" are not affiliated with the release being searched for at all and thus are more confusing than helpful to the beets user.
- This patch catches this case and states it in beets import verbose output.
- An example output of such arbitrary results with untagged files can be found here: https://github.com/beetbox/beets/discussions/4222#discussion-3769077
- There might be a similar issue in other metadata source plugins as well (amazon, beetport, ...) but I haven't looked into them since I don't use them (yet).
- There might be a better place to fix this than in the in the candidates method, …

discogs: Skip Discogs query on insufficiently tagged files

---

beets/util/__init__.py
docs/changelog.rst

The original problem was that this implementation of atomic moves, in #4060, used bytestrings incorrectly to invoke `mktemp`. This caused a regression that crashed beets when it tried to move files across filesystems (which, of course, actually involves a copy).
However, `mktemp` is deprecated, so this PR just avoids it altogether. Fortunately, the non-deprecated APIs in `tempfile` support all-bytes arguments.
Fixes #4168. Also closes #4192, which it supersedes.

Improved fix for Unicode mistakes in atomic move

---

docs/changelog.rst
docs/plugins/limit.rst

The index in the plugins looked weird and this was due to wrong headers in the limit plugin description:

Correct headers in limit plugin documentation

---

.github/workflows/ci.yaml
tox.ini

A recent change in Sphinx, as covered in https://github.com/sphinx-doc/sphinx/issues/10112, introduced a new warning about missed extlink opportunities. These warnings are causing spurious CI failures. Some of these suggestions are good but many of them are not, and there is not currently a way to disable the warning (globally or locally). So the only workable solution currently seems to be to pin an old version of Sphinx in CI for now. Hopefully there will be an option to disable this in 4.4.1, at which point we can unpin.
<details>
<summary>For posterity, here is the full set of warnings when I ran this a moment ago.</summary>
<pre>
/Users/asampson/Documents/code/beets/docs/changelog.rst:50: WARNING: hardcoded link 'https://github.com/beetbox/confuse' could be replaced by an extlink …

Pin Sphinx <4.4.0 in CI to work around new warning

---

CONTRIBUTING.rst

Remove obsolete advice on strings.

CONTRIBUTING.rst: minor Python 3 adaptation

---

test/test_logging.py
test/test_replaygain.py

Apparently we haven't hit these exceptions in a while; see the commit messages for details.
tl;dr: `raise e0, None, e2` was incorrectly translated to `None.with_traceback(e2)`, but clearly, `None` has no such attribute ( `BaseException` has). `e0.with_traceback(e2)` would be correct, but we need here can be expressed in a simpler way on Python 3.

Fix exception handling in tests

---

beetsplug/replaygain.py
docs/changelog.rst
docs/plugins/replaygain.rst
test/helper.py
test/test_replaygain.py

Part of #3893: While working on improved parallelism, I did quite a bit of refactoring of the replaygain plugin to make the code easier to understand and modify (to me, at least). This also adds a few new tests for previously uncovered codepaths.  There's also a bugfix in one of the commits (`replaygain: clarify docs for overwrite/force and actually respect it correctly`). None of the other commits should change the behaviour of the plugin, though.
If someone dares to review (sorry! - this is quite extensive), best look at the individual commits and their commit messages, I've tried to split this into small-ish changes.

Refactoring of the replaygain plugin

---

beets/dbcore/query.py
beets/library.py
docs/changelog.rst
docs/reference/query.rst
test/test_query.py

Adds 2 new query prefixes to specify exact matches for strings; `=` for case-sensitive matches and `~` for case-insensitive.  For example, the queries `~braid` and `=Braid` both match "Braid" but not "Braids".
I have often wished for a way to do this without having to write a regex on the command line.  Perhaps there is a better way than what I am suggesting in this PR, but I wanted to get the ball rolling on this (imo) handy feature.

Add query prefixes :~ and :=

---

beetsplug/convert.py
docs/changelog.rst
test/test_convert.py

This rectifies a couple of things in #4226, as pointed in https://github.com/beetbox/beets/pull/4226#issuecomment-1011499620:
- Undo the `pretend` sensitivity in the import path, because it's not clear how this setting could ever be true.
- Preserve the log message in debug mode, even when quiet.

convert: Revert some recent changes to convert-on-import path

---

extra/_beet

Use directory name completion for -d/--dest option.

zsh completion: handle destination for "convert"

---

test/test_lyrics.py
tox.ini

Inspired by the recurring test failures of the kind seen in https://github.com/beetbox/beets/runs/4993930755?check_suite_focus=true
Generate more useful output on failed assertion in the lyrics integration tests, in particular provides more details for the failures in https://github.com/beetbox/beets/runs/4993930755?check_suite_focus=true
In addition, `subTest` is used to better separate tests of different backends, and avoids aborting the entire test function if one backend fails.
Nothing, this is only improves the tests.

Improve lyrics tests

---

test/test_replaygain.py

This is the same as d26b0bc1 (from #4244), which I reintroduced again in a new test
due to a botched rebase...

test_replaygain: fix exception handling again

---

beetsplug/convert.py
docs/changelog.rst
docs/plugins/convert.rst

Fixes #2116 
Prior to this PR, the convert plugin didn't resize album art when embedding it into the file, even when a maximum art size was set in the config file for the plugin. I discovered this to be a serious issue when every ~2.5 MB Opus file in an album got bloated to over 20MB because of some scanned hi-res art from a vinyl album.
This PR refactors the handling of album art resizing slightly to avoid code duplication.
A useful next step would be to add "force_jpg" and "quality" options to the config file for the convert plugin. Even when resizing the embedded art to something reasonable like 1080x1080, PNG art can still end up quite large. The art resizing code already supports converting to JPEG and setting the quality parameter.

Resize album art when embedding (convert plugin)

---

beets/art.py
beets/util/artresizer.py
docs/changelog.rst
test/test_art_resize.py
test/test_embedart.py

Fixes #4272. In the process, I found that I didn't like some details of the code for checking art similarity and `ArtResizer` in general, so this includes a fair bit of refactoring. For review, best read the commits individually and look at the commit messages.

Fix embedart with compare_threshold on ImageMagick 7

---

beetsplug/fish.py
docs/changelog.rst
docs/plugins/fish.rst

I find it useful because it would allow us to generate the completion script when creating an .rpm package.

fish plugin: Add --output option

---

beets/autotag/match.py
docs/changelog.rst

First discussed in https://github.com/beetbox/beets/discussions/4269#discussioncomment-2251701
Fixes album candidates being treated as duplicates when the album id (assumed to be musicbrainz id) is not set.
(...)

fix: dont deduplicate matches if musicbrainz ID is not set for album matches

---

beetsplug/discogs.py
docs/changelog.rst
test/test_discogs.py

- Fixes #4225
- Discogs changed their release URL format. This fixes the albumid extraction by using an improved extraction method.

discogs: Fix discogs_albumid extraction

---

README.rst
README_kr.rst

Hi beets, long time no see 👋
Just a tiny change today, checked the link and made it HTTPS, skipping the redirect HTTP => HTTPS this way 0:-)
As [the link](https://www.w3.org/TR/html-markup/audio.html) is being redirected and most likely not showing what was intended before it potentially could even be replaced, for example with either of
- https://en.wikipedia.org/wiki/HTML5_audio
- https://html.spec.whatwg.org/multipage/media.html#the-audio-element
- https://caniuse.com/audio
I even went back and checked where the link originally pointed at: https://web.archive.org/web/20161125120800/http://www.w3.org/TR/html-markup/audio.html
Just say the word if I should change something :)
- N/A Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` …

README.md: HTTP => HTTPS

---

beets/autotag/hooks.py
beets/autotag/mb.py
beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst

Fixes #400.  
Related to #2686
As I mentioned in https://github.com/beetbox/beets/issues/400#issuecomment-1067666254, this adds a patch that allows to disable the MusicBrainz metadata source during the import process.
I had a little go at making the `MusicBrainz Options` section in the docs a little bit more consistent, and copied over the entire default config section for clarity.

Ability to optionally disable the musicbrainz metadata source

---

beets/util/artresizer.py
beetsplug/thumbnails.py
test/test_art.py
test/test_art_resize.py
test/test_embedart.py
test/test_thumbnails.py

A follow-up to https://github.com/beetbox/beets/pull/4275. Previously, `ArtResizer` had several backend -> method mappings, which seems to be a poor substitute for proper classes given that the `ArtResizer` has outgrown its name and supports many methods these days. This also allows for a cleaner separation of backend-specific concerns such as handling the modern/legacy ImageMagick invocations.
Some patterns in this code still feel a little clunky (such as the repeated checks for local/proxy backend), but in my opinion, this is at least a small improvement. Do you agree? In particular, I'd be interested if the last commit in this series, which moves some code from the thumbnails plugin to `ArtResizer`, seems sensible. Or is this not really universal enough to warrant moving to beets' …

Refactor: ArtResizer backends are classes

---

test/rsrc/lyricstext.yaml

Fixes #4334 
https://github.com/beetbox/beets/commit/3f896ab28117cd9032a0d9fcc8fc5c871f954324 fixed the plugin `lyrics` for Tekstowo. However the current test suite _expects_ the extraneous text, which is why it's [failing](https://github.com/beetbox/beets/runs/5706550224?check_suite_focus=true). 
This PR removes the extraneous text from this particular song's definition.
https://github.com/beetbox/beets/blob/e52b5980164edb23d5549fd31793b6c6287cf91e/test/rsrc/lyricstext.yaml#L57-L62

Remove Tekstowo extraneous text from `lyricstext.yaml` to fix `test_lyrics`

---

test/test_lyrics.py

As per https://github.com/beetbox/beets/pull/4344#issuecomment-1119098074, this updates "first" and "second" in the test_lyrics output to "expected set" and "result set" to make it clearer which is which.
Thanks for maintaining beets, I've been using it for years now :)

Change "first" and "second" in test_lyrics output to "expected" and "result"

---

beetsplug/spotify.py
docs/changelog.rst

Partially Fixes #4347.  
Added additional keys to save Spotify `track_id` and `album_id` as flexible attributes.

Save Spotify album_id and track_id as flexible attributes

---

docs/guides/main.rst

I found the "Installing on Windows" section of the "Getting Started" guide, specifically pertaining to step 2 (i.e. setting the `PATH `environment variable), to be incompatible with more modern Windows machines, as it seems to be based off Windows 7. 
I updated this section from utilizing a Windows 7 to a Windows 10 specific step-by-step instruction set.
- Not sure if this requires a changelog entry. However, it can be appended if needed.

Update Windows installation instructions to Windows 10

---

docs/plugins/beatport.rst

Fixes the command line formatting for the Beatport plugin page in the Documentation.

add cl formatting to beatport plugin docs

---

beets/library.py
docs/changelog.rst
test/test_query.py

Fixes #1865.  
* [As per @intelfx suggestion](https://github.com/beetbox/beets/issues/1865#issuecomment-180027742),
implicit path queries are replaced with explicit ones by prepending `path::` to them.
* @sampsyo thanks for adding a test for this issue in 19a5d8c - it's been unskipped.

Make implicit path queries explicit and simplify their handling

---

beets/mediafile.py

This is for mediafile what cc8c3529fbf528da8eadadf2ff61389db9adf767 was for confit, cf. https://github.com/beetbox/beets/pull/4263.
Spotted in the top post of https://github.com/beetbox/beets/issues/4330

mediafile: Improve deprecation warning

---

beetsplug/spotify.py
docs/changelog.rst
docs/plugins/spotify.rst

This PR extends the `spotify` plugin to add another command `beet spotifysync` to obtain all the audio features available for a track. This includes the `popularity` information and `audio_features`. The following `audio_features` are included: acousticness, danceability, energy, instrumentalness, key, liveness, loudness, mode, speechiness, tempo, time_signature, valence. See details [here](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-audio-features). 
This command only processes tracks that already have the `spotify_track_id` (which was introduced in #4348). So, the workflow will be to run `beet import` to obtain the `spotify_track_id`. This information can then be used to run `beet spotifysync`. 
Fixes #4347 #3578 #4094
optional config:
```
spotify: …
```

Extend Spotify plugin to obtain (popularity and audio features) track attributes

---

docs/plugins/index.rst

Adds a link to the [beets-audible plugin](https://github.com/Neurrone/beets-audible)
(...)

docs: add link to Beets-audible plugin

---

beetsplug/spotify.py
docs/changelog.rst

Added ability to handle API error (too many requests). 
Fixes #4369

Add Spotify 429 (too many requests) API error handling

---

beets/ui/commands.py
docs/changelog.rst
docs/guides/tagger.rst
docs/reference/cli.rst
test/test_ui.py

feat(import): Add support for reading skipped paths from logfile

---

beetsplug/importadded.py
docs/changelog.rst

Fixes #4389
It seems to me that this issue may be fixed in a similar way to previously fixed importadded issue #1107 and hardlink option #2445.

Fix importadded plugin with reflink

---

beetsplug/acousticbrainz.py

Add a missing space one of the Acousticbrainz plugin warning logs.

Fix typo in Acousticbrainz warning log

---

beets/autotag/hooks.py
beetsplug/spotify.py
docs/changelog.rst

As discussed in #4398, this PR adds the Spotify album information when importing tracks. I understand there are unresolved issues about which album to import for other taggers (e.g., MB). Thus, this PR only works for Spotify taggers. The behavior is unchanged for other sources.

Spotify: Add album name for singleton imports

---

beets/plugins.py
beetsplug/spotify.py

Fixes #4411
I had to add a few additional guard clauses to prevent errors. 
Tested this fix with the same track with both Spotify and MB match and it works fine.

Fix: Crash when search encounters a 404 error 

---

beetsplug/convert.py
docs/changelog.rst
docs/plugins/convert.rst

It looks like the convert option for wma used to be called windows media.  We could just remove this alias, but might be good to keep for backwards compatibility.
Fixes error when trying to use wma format in convert.

Fix old alias

---

beetsplug/spotify.py
docs/changelog.rst

Added `spotify_lastupdatedat` field that can be used to economize on the API calls. For example, we can use this field to update only those tracks that have not been updated in the last 6 months.

[Small PR] Add spotify_lastupdatedat field

---

beetsplug/web/__init__.py
docs/changelog.rst
test/test_web.py

Hi! In the last version of Flask, the `attach_filename` parameter was removed of the `send_file` function, used by the web plugin to stream the file. So thing change broke the web plugin. [Flask changelog](https://flask.palletsprojects.com/en/2.2.0/changes/#version-2-2-0)
Also, I added a test for that feature.

Fix get item file in web plugin

---

beets/config_default.yaml
beets/library.py
docs/changelog.rst
docs/reference/config.rst
docs/reference/pathformat.rst
test/test_library.py

Solution for https://github.com/beetbox/beets/discussions/4436. It is mostly copied from the `aunique` template. I don't know if there could be better defaults for the `disambiguators`.

Add path template "sunique" to disambiguate between singleton tracks

---

beets/library.py
docs/changelog.rst
docs/reference/query.rst
test/test_query.py

#4251 added exact match queries, which are great, but it was subsequently pointed out in https://github.com/beetbox/beets/pull/4251#issuecomment-1069455483  that the `~` query prefix was already in use.
So this changes the prefix from `~` to `=~`. A little longer, but hopefully it makes the relationship to the similarly-new `=` prefix obvious.

Change the prefix for exact match queries

---

docs/plugins/index.rst

Adding my plugin in the documentation as it was suggested [in the discussions](https://github.com/beetbox/beets/discussions/4375).
Also, would you like if I add this plugin code in the `beetsplug` folder of this repo? What are the prerequisites for it?

Add Beetstream in the plugin list

---

extra/release.py

Fixes the issue noted in #4395
> Thanks! Not sure how this one didn't get bumped when the other occurrences did.
_Originally posted by @sampsyo in https://github.com/beetbox/beets/issues/4395#issuecomment-1172913377_

release.py: fix version regex (remove u'' string prefix)

---

beets/library.py
docs/dev/library.rst

Closes: https://github.com/beetbox/beets/issues/4404

Document Album.items() / LibModel.items() conflict

---

beets/util/pipeline.py
beetsplug/lyrics.py
test/test_art.py
test/test_player.py

I found a few deprecations because [pytest](https://docs.pytest.org/) surfaces warnings by default (unlike nose). Fortunately, they were all pretty easy to fix.

Resolve some deprecation warnings

---

beetsplug/mbsubmit.py
docs/changelog.rst
docs/plugins/mbsubmit.rst

Adds a command `mbsubmit` to run even after the initial import. The command accepts queries and prints the tracklist to be submitted to MB. Users can now run something like `beet mbsubmit album:"Atrangi Re"` to generate the track listing (see output below). 
```
arsaboo@ubuntuvm2:~/beets$ beet mbsubmit album:"Atrangi Re"
01. Garda - A.R. Rahman, Daler Mehndi (3:44)
02. Chaka Chak - A.R. Rahman, Shreya Ghoshal (4:31)
03. Tere Rang - A.R. Rahman, Haricharan, Shreya Ghoshal (4:34)
04. Little Little - A.R. Rahman, Dhanush, Hiral Viradia (4:18)
05. Tumhein Mohabbat - A.R. Rahman, Arijit Singh (3:07)
06. Rait Zara Si - A.R. Rahman, Arijit Singh, Shashaa Tirupati (4:51)
07. Toofan Si Kudi - A.R. Rahman, Rashid Ali (3:37)
```
Fixes #4455

Extend mbsubmit plugin to run after initial import

---

setup.py
test/test_library.py

Unidecode 1.3.5 (a yanked PyPI version) [changed the behavior](https://github.com/avian2/unidecode/blob/414199246e4871669896756279e3460ff0364839/ChangeLog#L5) for some specific characters:
> Remove trailing space in replacements for vulgar fractions.
As luck would have it, our tests used the 1/2 character specifically to test the behavior when these characters decoded to contain slashes. We now pin a sufficiently recent version of Unidecode and adapt the tests to match the new behavior.

Adapt tests to latest Unidecode version

---

beetsplug/replaygain.py
docs/changelog.rst

This is a second fix to errors that have been cropping up in CI lately. Put this one into the bucket labeled "I don't know why this ever worked," but it's causing problems only on the Windows CI builds.
The parallelism strategy in #3478, in retrospect, used a pretty funky way to deal with exceptions in the asynchronous work—since `apply_async` has an `error_callback` parameter that's meant for exactly this. The problem is that the wrapped function would correctly log the exception *and then return `None`*, confusing any downstream code. Instead of just adding `None`-awareness to the callback, let's just avoid running the callback altogether in the case of an error.

replaygain: Fix error handling for parallel runs

---

beets/util/__init__.py
beetsplug/convert.py
beetsplug/duplicates.py
docs/changelog.rst
test/test_util.py

This is very much an experiment, but it's an attempt to address persistent issues with invoking command-line tools with non-ASCII arguments. For example, the `replaygain` plugin wants to invoke `ffmpeg` on filenames that might contain special characters. Doing this in a cross-platform way has always been extremely fraught—it's hard to get it to work right simultaneously on Unix (where filenames are plain bytes that need not obey *any* specific encoding) and on Windows (where filenames are weird, but they are closer to being Unicode strings).
The experiment here is to centralize on the Python standard library's implicit recommendations for this: `fsencode` and `fsdecode`. These use surrogate escaping (at least in most configurations??), so they probably shouldn't crash. The `subprocess` …

Use Python's standard filesystem encoding for command-line arguments

---

beets/autotag/mb.py
beets/config_default.yaml
docs/changelog.rst
docs/reference/config.rst

Sometimes a user may want to use an artist's locale-specific alias but *not* want to use their legal name, for example.
A good example of this would be the artist [Qeight](https://musicbrainz.org/artist/9888f61e-3ec8-4dcd-ae11-3115da898f0a). On MusicBrainz, their `en` locale is set to their legal name. While technically correct for the data in MusicBrainz, this probably isn't what a user expects when using beets.
(No tests yet but I can add them if this PR is going to be merged)

Add a `import.ignored_alias_types` option to ignore alias types.

---

beetsplug/lastgenre/genres.txt
docs/changelog.rst

Remove "Trip-hop" because it's duplicate (the other one is "Trip hop").
For more information see https://github.com/beetbox/beets/discussions/4503#discussioncomment-3781639
(...)

Remove duplicate "Trip-hop" genre

---

beetsplug/convert.py
docs/plugins/convert.rst
test/test_convert.py

Bug introduced in c6d623241b578d1c409affaa2cef27c4f27cb02c, should_transcode would return False even when the format was different.

Fix recent bug that would not transcode when format was wrong

---

beets/config_default.yaml

We don't currently comment anything in the default config. For more advanced users, occasional comments may be helpful. I think this is most true in the "replace" section, which otherwise requires an eagle eye and a memorization of Python regex escape rules + how regex works.
Comments should be sparing, analogous to code comments vs. code docs in other projects. In our actual docs I may toss a link to https://regexr.com/.

Sort and comment "replace"

---

beets/autotag/mb.py
beets/library.py
docs/changelog.rst
test/test_mb.py

Fixes #4428
Adds the remixer field from the musicbrainz database to the beets library. I haven't added any documentation since I didn't know if it is necessary for the changes I made.

Added remixer field

---

beets/logging.py
setup.cfg

The primary change here is to adapt to adapt to the issue described in https://github.com/PyCQA/flake8/issues/1689#issuecomment-1326319235, wherein a recent change to flake8 required reformatting of `setup.cfg`.
I also took the opportunity to remove one particularly suspicious flake8 "ignore" override, for `from _ import *` wildcard imports. There was one place we were relying on this that didn't really seem necessary.

Fix some CI breakage due to backwards-incompatible flake8 changes

---

test/test_embedart.py
test/test_zero.py

tests: fix assertions for empty MediaFile.images

---

test/test_ui.py

From #4582 (@jpluscplusm)
> I strongly suggest that this only be merged after tests are added that would have caught this problem before 1.6.0 was released. I've added no tests in this PR as the relevant parts of the Beets test suite quickly put me out of my depth. I really think it's worth getting a failing test in place, before merging this (I'll happily rebase, or anything else needed) as I /believe/ this bug will be causing any Beets user on 1.6.0+ to be re-tagging much/all of their library on each write.
This PR should do the trick.
I'm not up to speed on the issue and the history of the `albumtype[s]` fields, this is only a quick test made from the description of the problem. So, I can't really comment on the solution and an automated database fix that the next beets version might …

tests: add a (xfailing) test for issue #4528

---

.github/workflows/ci.yaml
.mypy.ini
setup.py
tox.ini

Add mypy to tox and CI configurations, and add a few type stubs to the dependencies. This allows failures, similar to the nightly Python tests. Unsurprisingly, mypy does fail currently.
cf. https://github.com/beetbox/beets/pull/4495#issuecomment-1356458837

Add mypy to tox and CI

---

beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst

Musixmatch are currently blocking all requests with the beets user agent. This MR removes Musixmatch from the default enabled sources and documentation.
Fixes #4585.

Remove Musixmatch from default enabled sources

---

beets/plugins.py
beetsplug/discogs.py
docs/changelog.rst

- Handle "join keyword" in MetadataSourcePlugin.get_artist() and make use of the new functionality in the Discogs source plugin.
- Fixes #4401 (Note that despite being discussed here, no version bump of python3-discogs-client is required since the `data` attribute being used, contains the required "join" field already.)

Handle "join keyword" in `MetadataSourcePlugin.get_artist()`

---

docs/changelog.rst
docs/plugins/discogs.rst

Small docs update conveying the limitations of the Discogs plugin for singletons until this functionality is added.
Related to #2544 and #3574.
(First PR here, so please let me know if anything is out of order.)

Add Discogs singleton limitation to docs

---

docs/reference/config.rst

This fixes a simple grammatical error in config.rst. I'm not sure if a changelog entry is needed here, so I didn't add it.
- [] Documentation. (If you've add a new command-line flag, for example, find the appropriate page under `docs/` to describe it.)
- [] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)

config.rst: Remove extraneous for

---

docs/plugins/index.rst

This PR changes the list of plugins in the documentation:
* it converts the *unordered lists* of plugins into *definition lists*, more appropriate for this kind of listing
* it changes the terms of the lists from the documentation page name to the relative plugin's id, allowing easier search when the exact plugin name is known
_None of the checkboxes seems applicable to this pull request._

Use definition lists with the plugins' names in the documentation

---

beetsplug/discogs.py
docs/changelog.rst
docs/plugins/discogs.rst

Implements `item_candidates` for the Discogs plugin, which begins to address #2544 and #3574.
Continues staled PR #3682 by implementing a subset of its provided features as requested by @sampsyo.
**Major change from  #3682**: no longer using string distance to narrow matches before returning candidates. This additional narrowing seems reasonable but it slowed down `item_candidates` (though marginally compared to the API call) and more importantly used a string match tolerance that users had no obvious way to control as far as I could tell. It seems preferable for as much pruning/matching to happen in a single unified function which would take all candidates returned by `item_candidates` as input; hardcoded matching in a separate function could result in harder to control and debug …

Implement item_candidates for Discogs plugin

---

beets/library.py
docs/changelog.rst
test/test_library.py

Fix album store method to cascade flex field deletions to items

---

beetsplug/fetchart.py
docs/changelog.rst

PR #3748 changed the way cover art is fetched from the cover art archive, but the manual addition of a `-` to the width suffix that was needed when the image URI was being constructed manually was not removed. Because of this the plugin would try to look up the property under `thumbnails` that didn't exist (for example `-1200` instead of `1200`), which would fail.

Fix cover art archive fetching

---

CONTRIBUTING.rst
beets/autotag/hooks.py
beets/dbcore/query.py
beets/library.py
beets/logging.py
beets/ui/__init__.py
beets/ui/commands.py
beets/util/__init__.py
beets/util/functemplate.py
beetsplug/hook.py
beetsplug/keyfinder.py
beetsplug/smartplaylist.py
beetsplug/web/__init__.py
docs/changelog.rst
docs/guides/main.rst
setup.py
test/helper.py
test/test_query.py
test/test_ui.py
test/test_util.py

Fixes #4372; best reviewed commit-by-commit. Don't merge this just yet, I want to review the `case_sensitive` change again (please do so, too!).

Drop Python 3.6, some Python 2 + Python <= 3.6 cleanup

---

docs/guides/main.rst

Supersedes #4382, with a somewhat simpler set of context around the link. Also fixes a link to Twitter (we're on Mastodon now).

Docs: Add a link to the walkthrough from the main tutorial guide

---

beets/autotag/hooks.py
beetsplug/absubmit.py
beetsplug/acousticbrainz.py
docs/changelog.rst
docs/plugins/absubmit.rst
docs/plugins/acousticbrainz.rst
docs/plugins/index.rst

Fixes #4627.
AcousticBrainz is shutting down as of early 2023. Deprecate the `absubmit` and `acousticbrainz` plugins, and modify them to only function if an AcousticBrainz server has been configured.

Deprecate `absubmit` and `acousticbrainz` plugins

---

docs/changelog.rst

Added a note to the very top of the changelog.rst that editors should add there "new things" to the bottom to the list. Some people add it to the top, some to the bottom. Basically it doesn't really matter in the end where a feature/fix is placed in the final release notes, but since we constantly have to resolve merge conflicts within this file I think it would reduce confusion at least a little if we know that "news" are at the bottom _always_.

Improve "Changelog goes here note" in changelog.rst

---

beets/plugins.py
beets/util/id_extractors.py
beetsplug/beatport.py
beetsplug/deezer.py
beetsplug/discogs.py
beetsplug/spotify.py
test/test_discogs.py
test/test_plugins.py

Tidy up and streamline ID extraction utilities used by metadata source plugins. Enable the usage of those utilities from everywhere.
- Introduce a new module `beets.util.id_extractors`
- Move the Discogs ID extractor function to the new module.
- Move the regex variables for the following services to the new modul:
- Spotify
- Deezer
- Beatport
- Leave a note about Bandcamp ID's
- Refactor the MetadataSourcePlugin._get_id() to use the new utility location.
- Fix the Beatport plugin to use the shared functionality of MetadataSourceplugin which it already inherits.
- Fix the Discogs ID extractor function to support a legacy format that is still in use.

Refactor metadata source ID extraction utilities

---

beetsplug/deezer.py

```
** error loading plugin deezer:
File "\git\beets\beets\plugins.py", line 268, in load_plugins
namespace = __import__(modname, None, None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "e:\git\beets\beetsplug\deezer.py", line 26, in <module>
from betts.utils.id_extractors import deezer_id_regex
ModuleNotFoundError: No module named 'betts'
```
(...)

Fix typo in deezer.py

---

beetsplug/discogs.py
docs/changelog.rst
setup.py

Addresses #4691, providing a warning if the user attempts to use a non-compliant version of `discogs_client` (any version of the abandoned package `discogs-client` or `python3-discogs-client` < 2.3.10). These non-compliant versions give no error when running `beet import`, but instead manifest as a large number of `No matching records found` due to rate limiting (which is expected to be implemented by `discogs_client`).

discogs_client version check

---

docs/plugins/convert.rst

Fixes https://github.com/beetbox/beets/issues/4711
Add another example to `convert` plugin to allow specifying a format to convert.

Add additional example to convert plugin 

---

beets/autotag/mb.py
beets/config_default.yaml
beets/importer.py
beetsplug/beatport.py
beetsplug/deezer.py
docs/changelog.rst
docs/plugins/index.rst
docs/reference/config.rst

MusicBrainz provides links to related websites via the "External links" section , usually found at the bottom right of a release page:
Fortunately this information is available via the MusicBrainz API. This PR adds the fetching of these URL's, extracts the "metadata source ID's" from those and saves them in the corresponding fields in the Beets library. 
Currently the following sources are supported: Discogs, Bandcamp, Spotify, Deezer, Beatport. Typically **a link to a Discogs release is very likely** to be provided and seems to be considered a "quasi standard" for MusicBrainz editors. It seems worth for Beets to access this information and use it with  future features. The rest of the supported external sources are not that likely to be found.
- Fixes #4220
- Is required for future …

Save external ID's via MusicBrainz

---

beets/util/id_extractors.py

Update beetcamp URL in id_extractors

---

beets/util/__init__.py
beets/util/m3u.py
beetsplug/convert.py
docs/changelog.rst
docs/plugins/convert.rst
test/rsrc/playlist.m3u
test/rsrc/playlist.m3u8
test/rsrc/playlist_non_ext.m3u
test/rsrc/playlist_windows.m3u8
test/test_convert.py
test/test_m3ufile.py

- Enables the functionality proposed in https://github.com/beetbox/beets/discussions/4373
- The convert plugin is suitable to be used as a media file exporter already.
- Thus it makes sense to add a feature to save a playlist file into the export folder containing all exported media files in the order they were exported/converted.
- Since with the convert plugin all sorts of "beets queries" could be exported/converted, the feature uses a more general approach than described in the initial proposal (above linked discussion). To achieve exactly what's described in the discussion, additionally the beets `playlist` feature can be used.
- Relative paths should be used to make the playlist file portable, e.g used on another computer.
- The classic m3u format does not do well with special …

convert: New feature "Write m3u playlist to destination folder"

---

beets/ui/commands.py
docs/changelog.rst
docs/reference/cli.rst

Fixes #4693. 
To address the bug outlined in issue #4693, we added a utf-8 encoding argument to the import_files function in the commands.py file.

Enforced utf-8 encoding on imported files

---

beets/library.py
docs/changelog.rst
test/test_query.py

Added `SingletonQuery` which queries 
* `album_id is NULL` for `singleton:true`
* `not (album_id is NULL)` for `singleton:false`
As a result
* A nice speed-up of the `singleton:true` query 
* `singleton:1` and `singleton:0` now work fine!
This is ultimately building towards replacing python-only queries with SQL equivalents.
Tested with default config on my ~7K items library that has 350 singletons. Numbers represent seconds, and each command was run 10 times.

Define SingletonQuery to perform filtering through SQL

---

beets/dbcore/db.py
beets/dbcore/query.py
beetsplug/bareasc.py
docs/changelog.rst

* Define a custom function which performs regex lookups natively in SQL. This improves
performance of lookups like `beet list path::hello`.
* Define a function which runs `unidecode` for the `bareasc` lookups

Perform regex and `bareasc` lookups using SQL

---

beets/importer.py
docs/changelog.rst
test/test_importer.py

- Fixes #4726 
- Refactors preserving of flexible attributes in the importer's `reimport_metadata()` method.
- New logging message when flexible attributes are excluded from the preserving process and _actually_ set to a new value.
- Reformats all existing logging messages and streamline their looks.
- Adds a new unittest that checks if the data_source album field is _not_ reset to its original value on a reimport.

Fix data_source not updated on re-import and refactor `reimport_metadata`

---

beetsplug/embedart.py
docs/changelog.rst
docs/plugins/embedart.rst
test/test_embedart.py

Fixes [#83](https://github.com/beetbox/beets/issues/831)
Added another option `-u` to provide an image URL. The plugin can now download the image, check if it is valid, and then embed the picture as cover art.

Added option to embedart using an image URL [small PR]

---

beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst
setup.py

Added `spotify` as a fetchart source. 
Let me know if this approach looks fine.

Add spotify as a fetchart source

---

beetsplug/fetchart.py

Small follow-up to #4771: We have a bunch of source-specific code in the plugin constructor: It seems cleaner to me to move that into the source classes and properly separate concerns.

fetchart: Move some source-specific code from base plugin into source classes

---

beetsplug/fetchart.py

cf. @arogl's comment https://github.com/beetbox/beets/commit/254bb297c894c0323174012ff27500867416d02b#commitcomment-111922347
> Now that this has been merged, external plugins that add to the fetchart plugin now fail with:
>
> ```AttributeError: module 'beetsplug.fetchart' has no attribute 'SOURCES_ALL'``

fetchart: revert a cleanup from #4774 that could break plugins

---

.github/workflows/ci.yaml
beets/dbcore/db.py
test/test_dbcore.py
test/test_importer.py
test/test_m3ufile.py
test/test_ui_init.py

Given that Python 3.11 is released, we've not been testing the most recent versions anymore. Thus, (try to) use semver x-ranges in order to avoid needing manual updates of this in the future.
~~Don't merge yet, I'm not sure that the range specification for `-dev` versions is actually valid as I used it here.~~
Unfortunately, [semver intentionally doesn't give a way to specify `3.x-dev`](https://github.com/npm/node-semver#prerelease-tags) to always get the latest development version. Thus, the 3.12 specification will still need to be updated manually.

CI: update python versions

---

beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst

Fixes #4707 
It turned out to be a lot simpler than I thought. As discussed in #4707, this PR creates a generic function that will use the image URL from `cover_art_url` field and update the album art. The idea was discussed in the linked issue to allow any plugin to save the cover art link to a flexible field `cover_art_url` and then `fetchart` should be able to use that field. Users can also manually update this field to specify a covert art image. 
Tested this with the [JioSaavn](https://github.com/arsaboo/beets-jiosaavn) plugin and it works perfectly.

Fetchart: use cover_art_url flex attr as a cover art source

---

docs/plugins/index.rst

`beets-popularity` has been archived since 2019. Removing it from the list of community plugins to avoid confusion.

Remove archived plugin - beets-popularity

---

beetsplug/spotify.py
docs/changelog.rst

Prevent reimporting album if an album is permanently removed from Spotify

---

beetsplug/fetchart.py
docs/changelog.rst

Use `spotify_album_id` instead of `mb_albumid` to always obtain the right values. 
Fixes #4803

Fetchart: Use the right field to obtain Spotify album id

---

beets/autotag/mb.py
beets/config_default.yaml
beets/importer.py
docs/changelog.rst
docs/reference/config.rst

Following #4708, this PR adds the ability to also import Tidal album id, which is also sometimes available on the release pages.

Allow importing Tidal album id from MusicBrainz

---

test/_common.py

As discussed in #4798 the `reflink` library seems to be unmaintained and it may be annoying to install. This is a tiny change to to avoid depending on it to run *all* tests.

Don't require reflink to run the tests

---

beets/library.py

Missed this while implementing #4809.

Make sure release_group_title is applied to album objects.

---

beetsplug/fetchart.py
docs/changelog.rst

fanart.tv uses a string to output the number of likes (see https://fanart.tv/api-docs/api-v3/). In order to sort numerically we need to convert the string into an int.
This was tested locally with `http://webservice.fanart.tv/v3/music/albums/1cbc1a5a-5512-3f8e-997b-d9281b83722b?api_key=...`

Fix fanarttv sorting

---

beets/dbcore/query.py

Slight cleanup of dbcore typings:
> It seems like `Query`s and `Sort`s should really be generic over `Model`.
>
> Also, make use of the postponed evaluation of annotations that we get with `from future import __annotations__`.

dbcore/query: remove spurious dependency on library

---

beets/dbcore/types.py
beetsplug/edit.py

Yet another follow-up to dbcore typing. I've had this in the pipeline for a while, but only now got around to finishing it up and figure out the last bits around handling the `model_type` `Type`-valued field.
Please have a close look at this PR; does the approach look sensible? I restructured the class hierarchy a bit to avoid some conflicting signature. This could potentially break plugins that depend on details of the db and type handling (as it turns out, the edit plugin does).

typing: corrections for dbcore/types.py

---

beets/ui/commands.py

For some reason, the completion test is always failing for me locally. While this PR doesn't actually fix that; at least it removes a spurious warning.

test_ui: Fix spurious warnings in completion test

---

test/_common.py
test/helper.py
test/test_art.py
test/test_convert.py
test/test_embedart.py
test/test_filefilter.py
test/test_files.py
test/test_importadded.py
test/test_importer.py
test/test_info.py
test/test_library.py
test/test_plugin_mediafield.py
test/test_plugins.py
test/test_query.py
test/test_smartplaylist.py
test/test_thumbnails.py
test/test_ui.py
test/test_ui_commands.py

I've had #3690 in the pipeline for a long time; and it has grown too big to look at in one piece. This is just the first commit rebased on master. It is still quite big, but only touches test code, so should be safe (assuming CI is green).

Always use syspath conversions (#3690 split up, part 1)

---

beets/autotag/mb.py
beets/ui/commands.py
docs/changelog.rst
test/test_importer.py
test/test_mb.py

Fixes #654 
As in the issue suggested I implemented the "easiest/most obvious approach".
It fetches release relations and "follows" the ones for the type [transl-tracklisting](https://musicbrainz.org/relationship/fc399d47-23a7-4c28-bfcf-0607a562b644) for pseudo releases. The additional data gets merged with the pseudo-release. I am not 100% sure if I included all applicable fields for the merge. I left the pseudo-releases id's as is.
This change makes it near impossible to differentiate the pseudo releases from the actual releases in the ui, so I added that to `disambig_string`.  Are there any unwanted side effects from that change?
A small screenshot for reference:
This implementation has almost the same approach as the [plugin](https://github.com/TypicalFence/beets-resolve-pesudo-release …

resolve transl-tracklisting relations for pseudo releases

---

docs/plugins/index.rst

I wrote a plugin that scans MusicBrainz and Discogs for versions of releases that have more tracks than the ones in the user's database, such as deluxe, expanded or anniversary editions. For example:
```
beet more "Electric Light Orchestra"
```
```
more: Electric Light Orchestra - Discovery
more:     Fetching data from MusicBrainz...
more:     Version with 12 tracks found (have 9).
more:     See https://musicbrainz.org/release/23bf913d-3709-4f84-a3df-f19d3928cb2b​.
more: Electric Light Orchestra - Out of the Blue
more:     Fetching data from MusicBrainz...
more:     Version with 20 tracks found (have 17).
more:     See https://musicbrainz.org/release/9a86feb3-66db-3946-a477-67312641cc93​.
```
This PR adds it to the community plugins list.

Add beets-more to community plugins

---

beets/autotag/mb.py

The 'status' field is potentially null, and in this case the dictionary key is not returned by the API. Using get will return null in this case. Tested locally and this solves the issue!
Fixes #4832.

Fixed check for pseudo-release.

---

beets/autotag/mb.py
test/test_mb.py

Some pseudo-releases (erroneously) lack the relation to the actual release which previously would've caused a crash.
Examples:
- https://musicbrainz.org/release/5642e194-51ee-4012-bc4e-36b1cbd7bc06
- https://musicbrainz.org/release/f8f0c58a-b40a-4334-9294-14a5fd1300ab
Related to #4714.
cc @TypicalFence.

Handle missing release-relation-list field during pseudo-release lookup

---

beets/util/artresizer.py
docs/changelog.rst

Fixes #4836
ImageMagick 7.1.1-12 changed the default colorspaces used by the PHASH
compare function from sRGB,HCLp to xyY,HSB. This breaks the current code
for comparisons, so let's define the colorspaces ourselves.

Define colorspaces for imagemagick comparison

---

beetsplug/deezer.py
docs/changelog.rst
docs/plugins/deezer.rst

Fixes #4841 
Imports few other fields provided by Deezer. 
In addition, I added a function `deezerupdate` that updates the rank information without going through the import process. The rank information is updated daily and users may want to refresh the rank information periodically.

Import additional fields from Deezer and add function to update rank

---

beets/dbcore/db.py
beets/dbcore/query.py

The next iteration of introducing typings into dbcore. This is splitting out only `dbcore.query`; with some additional changes, I have clean mypy on `dbcore`, but that'd be a bit too much for a single PR.

typings: Fixes and improvements for dbcore.query

---

beets/util/artresizer.py
beetsplug/convert.py
beetsplug/embedart.py
beetsplug/fetchart.py
beetsplug/ipfs.py
beetsplug/metasync/itunes.py
beetsplug/thumbnails.py
test/test_thumbnails.py

Follow-up to #4830:
> I've had https://github.com/beetbox/beets/pull/3690 in the pipeline for a long time; and it has grown too big to look at in one piece. This is just the first commit rebased on master. It is still quite big, but only touches test code, so should be safe (assuming CI is green).
This is part 2, which mostly concerns plugins (except for a small fix to the `artresizer` module such that it's internally consistent).

Always use syspath conversions (#3690 split up, part 2)

---

test/_common.py
test/test_convert.py
test/test_files.py
test/test_importer.py
test/test_smartplaylist.py
test/test_ui.py

Follow-up to #4830, #4848 and #4849:
> I've had https://github.com/beetbox/beets/pull/3690 in the pipeline for a long time; and it has grown too big to look at in one piece. This is just the first commit rebased on master. It is still quite big, but only touches test code, so should be safe (assuming CI is green).
this replaces assertions of the form
```py
self.assertTrue(os.path.exists(syspath(path)))
```
by
```py
self.assertExists(path)
```
which includes the syspath conversion and is much easier to read.
Occurences where located using
```sh
git grep -E 'assert(True|False).*(isdir|isfile|exist)'
```

tests: make use of our custom filesystem assertions for conciseness

---

beets/importer.py
beets/library.py
beets/ui/commands.py

Follow-up to https://github.com/beetbox/beets/pull/4830 and #4848:
> I've had https://github.com/beetbox/beets/pull/3690 in the pipeline for a long time; and it has grown too big to look at in one piece. This is just the first commit rebased on master. It is still quite big, but only touches test code, so should be safe (assuming CI is green).
This is part 3, with some changes to beets' core. Thus, this is probably the most sensitive PR in the series.

Always use syspath conversions (#3690 split up, part 3)

---

beets/autotag/hooks.py
beets/config_default.yaml
beets/ui/commands.py
beetsplug/discogs.py
docs/changelog.rst
docs/plugins/discogs.rst
docs/reference/config.rst

The Discogs metadata plugin now saves album information when importing singletons.
- Fixes #4716
- Is a refactored / simplified version of #4717
- Presents album information in the singleton importer UI as:
```
eDit, edit Candidates? 4
Tagging track: Portishead - Numb
Album: Numb
URL:
https://www.discogs.com/release/1385011-Portishead-Numb
(Similarity: 100.0%) (Discogs, Index 1, Track A1)
Apply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort,
eDit, edit Candidates? 
```
- Additionally this PR extends the "disambiguation string" for _all_ singleton imports with track index and alternative name (track_alt field):
```
Candidates:
1. Portishead - Numb (100.0%) (Spotify, Index 7)
2. Portishead - Numb (100.0%) (Spotify, Index 1)
3. Portishead - Numb (100.0%) (Spotify, Index 27) …
```

Support providing album information on singleton imports via Discogs

---

beetsplug/smartplaylist.py
docs/changelog.rst

Log the creation of a smart playlist as info instead of debug log level. 
In an explicit run (not while importing) it doesn't hurt to get some progress to the UI since creating/updating smart playlists can take a singinficant amount of time.

Log smart playlist create msg as info log

---

beetsplug/smartplaylist.py
beetsplug/subsonicupdate.py
docs/changelog.rst
docs/plugins/subsonicupdate.rst

- Fixes triggering subsonicupdate on a database_change event instead of only at an import event.
- Sends a new event from the smartplaylist plugin whenever lists are updated/created and has subsonicupdate plugin listen to it.
- Both events register new listeners that launch the actual Subsonic library update _at the very end of a beets run_ (cli_exit) instead of being triggered by each change (similar to how the mpdupdate plugin does it).
- It doesn't hurt if Subsonic is informed on subsequent changes of smart playlists (while the user is heavily experimenting with them) since once a subsonic-rescan is triggered, it keeps running and doesn't restart from scratch.

Trigger subsonicupdate on database and smart playlist changes

---

beetsplug/importfeeds.py
docs/changelog.rst
docs/plugins/importfeeds.rst
test/test_importfeeds.py

Adds a new output format named `m3u_session` that saves a playlist named `<m3u_name>_<import_begin_datetime>` on each run of `beets import ....`

Add m3u per session feature to importfeeds plugin

---

beets/autotag/hooks.py
beets/dbcore/query.py
beets/importer.py
beetsplug/acousticbrainz.py
test/test_datequery.py
test/test_mbsync.py

It's pretty common for updates to flake8 & pycodestyle to add new style-related lint warnings. There are a few of these surfaced in this recent CI run:
https://github.com/beetbox/beets/actions/runs/5716141601/job/15486984755?pr=4866
These all look like perfectly reasonable improvements that are unlikely to break anything.

Adapt to some recent flake8/pycodestyle changes

---

beets/util/artresizer.py
docs/changelog.rst

The `ANTIALIAS` attribute has long been deprecated, and was finally removed in pillow 10.0.
The recommendation is to migrate to `Resampling.LANCZOS` instead.
https://pillow.readthedocs.io/en/stable/deprecations.html#constants
Fixes #X.  
(...)

Fix compatibility with pillow 10

---

CONTRIBUTING.rst
beets/autotag/mb.py
beets/dbcore/query.py
beets/importer.py
beets/library.py
beets/ui/completion_base.sh
beets/util/__init__.py
beets/util/artresizer.py
beets/util/hidden.py
beetsplug/absubmit.py
beetsplug/export.py
beetsplug/fetchart.py
beetsplug/lyrics.py
beetsplug/sonosupdate.py
beetsplug/thumbnails.py
docs/changelog.rst
docs/plugins/absubmit.rst
docs/plugins/aura.rst
docs/plugins/fetchart.rst
docs/plugins/limit.rst
docs/plugins/replaygain.rst
docs/reference/config.rst
test/helper.py
test/test_lyrics.py
test/test_mb.py
test/test_plugins.py
test/test_ui_init.py
test/test_web.py

Fixes various user-facing and non-user-facing typos

Fix various typos

---

beetsplug/lyrics.py
docs/changelog.rst

Fixes #4875, a small forgotten case in the BeautifulSoup filtering callback.

lyrics: Bypass None values in Google backend

---

beets/config_default.yaml
beets/ui/commands.py
docs/changelog.rst
docs/reference/config.rst

A new config option allows to enable a more detailed view when a duplicate is detected during import of an album or singleton.
- New `import` config option:
```
import:
duplicate_verbose_prompt: no
```
- Disabled by default.

Optional more verbose duplicates prompt

---

beets/library.py
beets/ui/commands.py
beetsplug/ipfs.py
docs/changelog.rst
docs/reference/cli.rst
test/test_ipfs.py
test/test_library.py

- Fixes #4822
- Keeps the default behaviour of inheriting album (fixed) attributes modifications to album tracks.
- Fixes album modifications of flexible attributes to be inherited to album-tracks as well.
- Adds a new CLI option `--noinherit/-I` that prevents inheriting to album-tracks, which allows changing fixed/flexible attributes on an album only.

Streamline album attributes modification behaviour and allow override via CLI

---

beetsplug/embyupdate.py
docs/changelog.rst
docs/plugins/embyupdate.rst

Fixes #4402.  
Adds a `userid` config option for the `embyupdate` plugin. When the
`userid` is provided, the Emby user lookup is bypassed. This avoids a
failure to get the user ID for private users.

Add embyupdate `userid` config option

---

beetsplug/substitute.py
docs/changelog.rst
docs/plugins/index.rst
docs/plugins/rewrite.rst
docs/plugins/substitute.rst

Fixes #2786.
Add the substitute plugin that is a replacement to **rewrite** plugin. Indeed, rewrite plugin modifies the metadata tags of the file, this plugin does not modify the metadata.

Substitute plugin

---

CONTRIBUTING.rst

Changed line 291 from  ``python -m pip install tox=3.8.3`` to  ``python -m pip install tox==3.8.3`` as shown in the 7th example: https://pip.pypa.io/en/stable/cli/pip_install/#examples, this is the correct way to install specific versions.

Correcting pip specific version install from "=" to "==" in Contributing.rst

---

beetsplug/scrub.py
docs/changelog.rst
test/test_importer.py

Fixes #4326.
`scrub.py:import_task_files` now passes `ui.should_write()` to `_scrub_item` to control restoring tags.
I also added a few tests to `test_importer.py`.

4326 scrub should not restore on import if "write" is disabled

---

docs/plugins/index.rst

Hi, adding the `beets-mpd-utils` plugin I shared in the discussions (#4915) to the community plugins list.

Add beets-mpd-utils to the community plugin list

---

beets/ui/commands.py
beets/util/__init__.py
docs/changelog.rst

When importing things using beets, by pure chance, it is apparently possible to have an item inserted into the database that does not have a path registered. Because the database returns `None` for the items' paths, cascading errors cause most library-wide operations to fail. Update, write, etc, all fail.
This effectively poisons the database and there's no way to remove it other than manually editing the database file. 
This PR just changes two lines and a typing so that the `update` command can still be used. The other commands will still fail but this seems to be a pretty rare edge case so I've only changed the `update` command. Now the logic, when there is no path associated with an entry, will consider it to be the same as a deleted file and purge it from the database.

Catch when items have no path

---

beetsplug/autobpm.py
docs/changelog.rst
docs/plugins/autobpm.rst
docs/plugins/index.rst
setup.cfg

This plugin uses librosa to automatically calculate the BPM for a track. It is based on the keyfinder plugin, and rounds the BPM to an int.
It's quite slow, but should be useful for DJs :).
Fixes #3856

Add autobpm plugin

---

beets/config_default.yaml
beets/ui/commands.py

This adds configurable disambiguation strings when importing. The defaults I've provided are what is currently in place but there are a number of limitations.
- When used with the `beets-audible` plugin, sometimes there are 'None' values that are printed, I haven't managed to narrow down the cause of that yet, but it may be limited to something that that plugin does.
- Values that may be printed can contain comma-separated values, which is how the disambiguation string is printed. This makes it appear as though there are more fields than there are, because it is CSVs nested in CSVs.
- This modification does not allow for any computation or formatting of values. Note that I've had to leave the medium and disc-number parsing in place, because my solution does not allow for formatting the …

Add customisable disambiguation strings for importer

---

beetsplug/fetchart.py
docs/changelog.rst
docs/plugins/fetchart.rst
test/test_art.py

This patch fixes two bugs with the Cover Art Archive provider of the `FetchArt` plugin:
-  the pre-sized thumbnails of the release group of an album would be ignored when the `maxwidth` option matches one of the available sizes (250, 500, and 1200 pixels).
- This allows the release group to behave exactly like the release itself (which does take the pre-sized thumbnails into account).
- no cover would be found and downloaded when the `maxsize` option is defined, is in the pre-sized thumbnails list, but CAA does not provide thumbnails for this release/release group
This patch can significantly speed up the fetching process of some albums, as the default size of some cover arts can be quite large (e.g. [this cover ](https://coverartarchive.org/release-group/1cd77af1-5fe8-45ac-9953-710315c856 …

FetchArt : fix an error with CAA where the pre-sized thumbs of release groups would be ignored

---

beets/config_default.yaml
beets/ui/__init__.py
beets/ui/commands.py
docs/changelog.rst
docs/reference/config.rst
test/test_ui.py

Continuing work on PR #1685 implementing an improved UI, with more discussion/screenshots at #1593.
Previous work has been rebased on `beetbox/beets/master`. Currently I've fixed many of the tests which were failing due to the code targeting Python 2.7 (such as `isinstance(basestring)`) taking care to retain backwards compatibility so that we can get this into release 1.5.0. The current tests that are failing are asserting the output of the UI, ~I'm not sure if that's because they are yet to be updated for the new UI but that shouldn't be hard to address if so~ **Update:** The failing tests were due to a change in UI. I've adjusted the failing tests to match the new UI output, however there are extra tests that must be written to check, for example, Unicode output of the "not equals" sign …

Importer UI overhaul rebase/update

---

beetsplug/advancedrewrite.py
docs/changelog.rst
docs/plugins/advancedrewrite.rst
docs/plugins/index.rst

This plugin allows rewriting fields based on a given library query. This can be helpful, for example, when an artist was renamed but you'd like to keep their older releases under their old name, or if you have a single track from a Various Artists release and want to have it included with the original artist.
Example configuration (restores the old name of a recently renamed artist for releases before 2023):
```yaml
advancedrewrite:
- match: "mb_artistid:dec0f331-cb08-4c8e-9c9f-aeb1f0f6d88c year:..2022"
field: artist
replacement: "이달의 소녀 오드아이써클"
```
Depending on whether this feature is desired, I'll address the remaining points.

Add advanced rewrite plugin

---

beetsplug/spotify.py
docs/changelog.rst

Gracefully handle Spotify API errors

---

beetsplug/spotify.py
docs/changelog.rst

Part 2 of the PR - #4943 
Currently, the plugin will endlessly keep retrying. I added the max-retries so that it stops after three retries.

Add retry logic for Spotify 

---

beets/dbcore/query.py
beets/library.py

To help with debugging queries that behave unexpectedly. Not sure whether this is really going to be helpful, but while looking at #4955 I realized I would like to know exactly what the queries parse to, because to be honest, I never remember the details our query syntax.

library: debug log parsed queries (and convert to f-strings)

---

test/plugins/test_edit.py
test/test_autotag.py
test/test_datequery.py

The black conversion moved some `# noqa` statements to the wrong lines, leading to lint failures. This moves them back to the offending lines.

fixup noqa after black auto-formatting

---

.github/workflows/formatting_check.yml

cf. https://github.com/beetbox/beets/pull/4654, the `formatting_check.yml` is invalid and never runs, immediately aborting on parsing this configuration file.

fix formatting_check CI config

---

CODE_OF_CONDUCT.rst
CONTRIBUTING.rst
docs/code_of_conduct.rst
docs/index.rst

Hello! I'm a first time contributor and thought it'd be great if the repo could have a Code of Conduct to help foster a positive and inclusive environment and give guidelines to help curb negative behaviors. Thus, I created the CODE_OF_CONDUCT.rst document based on the Contributor Covenant v2.1.

Added Code of Conduct Documentation

---

beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst
test/plugins/test_lyrics.py

This PR adds support for [LRCLIB ](https://lrclib.net) as a lyrics provider.
I recently set up Navidrome on my home server and the web UI for that [only supports embedded, synced lyrics](https://github.com/navidrome/navidrome/issues/491#issuecomment-946782864). From what I can tell, the current lyric providers only return plain lyrics. I did a little research and found LRCLIB, which offers an [easy to use API](https://lrclib.net/docs) that includes both synced and plain lyrics. Note that all four parameters (track, artist, album, duration) to the `/get` endpoint are required.
Inspired by https://github.com/tranxuanthang/lrcget/issues/2#issuecomment-1471512530.

Add LRCLIB as a provider for the lyrics plugin

---

CONTRIBUTING.rst

`detox` has been superceded by a native option in `tox`, so it is no longer maintained. 
See: https://github.com/tox-dev/detox

Remove reference to detox

---

beetsplug/spotify.py
docs/changelog.rst

Support writing ISRC to tracks in Spotify plugin

---

CONTRIBUTING.rst
README.rst
docs/changelog.rst

This is just a small doc fix: update the Twitter link in README to point to the Mastodon account (the pinned forwarding address on X isn't accessible to non-logged-in users anymore), and fix a typo that broke the link to the code of conduct in CONTRIBUTING.

Fix some docs links

---

.pre-commit-config.yaml

There is an error on the previous version of isort, on my machine at least, that causes it to fail setup. This just fixes that.

Update precommit hook versions

---

docs/reference/config.rst

I was going through the code, preparing to do a PR that makes it find the terminal width dynamically, but to my surprise that is already the case. So this is a short thing that just adds that information to the docs.

Add more detail to option about terminal width in the docs

---

beets/ui/commands.py
docs/changelog.rst

Fixes https://github.com/beetbox/beets/issues/4980
When importing, the old behaviour before the UI upgrade was that changed tracks were always displayed. After the update was merged, this was changed to showing no tracks at all unless the detail configuration was enabled, in which case all tracks are shown. This changes the behaviour back to what it should be.

Revert line change behaviour when importing tracks

---

beetsplug/deezer.py
docs/changelog.rst

Improve Deezer error handling

---

beetsplug/mbsubmit.py
docs/changelog.rst
docs/plugins/mbsubmit.rst
test/plugins/test_mbsubmit.py

Make it possible to open picard from the import menu when there are weak recommendations. Add another menu option to print the tracks into a beets-unmatched file for later parsing.
A better alternative to #4749 - closes #4749 . Also provides an intermediate solution to https://github.com/beetbox/beets/issues/1866 .
cc @ybnd .

mbsubmit: Add picard `PromptChoice`

---

beets/ui/commands.py
docs/changelog.rst
docs/reference/cli.rst

Fixes #4958
Exposes `import.incremental_skip_later` configuration option as CLI option.

expose incremental_skip_later as cli option

---

beetsplug/smartplaylist.py
docs/changelog.rst
docs/plugins/smartplaylist.rst
test/plugins/test_smartplaylist.py

Adds the boolean configuration option `smartplaylist.extm3u` to allow generating extm3u playlists that contain additional information (artist, title, length) per track. See [Extended M3U (Wikipedia)](https://en.wikipedia.org/wiki/M3U#Extended_M3U) and [playlist specification for HTTP Live Streaming (RFC8216)](https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.2.1).
This is to be able to display meaningful metadata and search tracks within a playlist within a player without having to load the linked audio files of that playlist.

smartplaylist: add extm3u/extinf/m3u8 support

---

beets/ui/__init__.py
docs/changelog.rst

Bring back NO_COLOR support.

---

beetsplug/smartplaylist.py
docs/changelog.rst
docs/plugins/smartplaylist.rst

Add CLI options to `splupdate` command:
* `--playlist-dir`, `-d`
* `--relative-to`
* `--prefix`
* `--urlencode`
* `--forward-slash`
* `--pretend-paths`

smartplaylist: expose config as CLI options

---

beetsplug/advancedrewrite.py
docs/plugins/advancedrewrite.rst
test/plugins/test_advancedrewrite.py

Rework the `advancedrewrite` plugin as discussed in #5002.

advancedrewrite: Support simple syntax and improve advanced syntax

---

beetsplug/smartplaylist.py
docs/changelog.rst
docs/plugins/smartplaylist.rst
test/plugins/test_smartplaylist.py

The boolean flags `--extm3u` and `--no-extm3u` are replaced with a string option `--output=m3u|m3u8`.
This reduces the amount of options and allows to evolve the CLI to support more playlist output formats in the future (e.g. JSON) without polluting the CLI at that point.
This is a follow-up of #5046.
Relates to #5048.

smartplaylist: change option --extm3u to --output

---

beetsplug/smartplaylist.py
docs/changelog.rst
docs/plugins/smartplaylist.rst
test/plugins/test_smartplaylist.py

Beets web API already allows remote players to access audio files but it doesn't provide a way to expose the playlists defined using the smartplaylist plugin.
Now the smartplaylist plugin provides an option to generate ID-based item URIs/URLs instead of paths.
Once playlists are generated this way, they can be served using a regular HTTP server such as nginx.
To provide sufficient flexibility for various ways of integrating beets remotely (e.g. beets API, beets API with context path, AURA API, mopidy resource URI, etc), the new option has been defined as a template with an `$id` placeholder (assuming each remote integration requires a different path schema but they all rely on using the beets item `id` as identifier/path segment).
To prevent local path-related plugin configuration from …

smartplaylist: add --uri-format option

---

beets/plugins.py
docs/changelog.rst

Raises an exception if multiple plugins provide template functions for the same field.
Closes #5002, supersedes #5003.
Tested locally.

beetsplug: Error out on conflicts in template functions

---

beets/config_default.yaml
docs/changelog.rst

Sorted the default config into categories, more or less. Added a FIXME and URL for an undocumented feature but otherwise it just re-arranges the existing config. No changes to substance.

 Sort and categorize config_default.yaml

---

beetsplug/web/__init__.py
docs/changelog.rst

Do not let the web plugin overwrite the Content-Length header with the full file length since flask/werkzeug [sets the requested range's/chunk's length](https://github.com/pallets/werkzeug/blob/eafbed0ce2a6bdf60e62de82bf4a8365188ac334/src/werkzeug/wrappers/response.py#L702) when handling a range request.
This is to allow playing large audio/opus files using e.g. a browser/firefox or gstreamer/mopidy without making a reverse-proxy/nginx emulate range request support and hide range-related headers from the backend.
I tested the fix successfully using firefox and gstreamer (mopidy-beets).
Previously (before beets 1.6.1), range requests had to be workedaround explicitly using a reverse-proxy such as nginx. A corresponding nginx server configuration could look as follows:
```
server {
listen …
```

web: fix/add range request support

---

beetsplug/advancedrewrite.py

Unfortunately, I mistakenly assumed that `list()` was equivalent to `[]`. However, this transforms a rewrite `Value` into `['V', 'a', 'l', 'u', 'e']` instead of `['Value']` as it was intended.

advancedrewrite: Fix multi-valued fields specified as a single string

---

tox.ini

In cf69cad56f6 the Sphinx version was pinned to "<4.4.0".
The issue at that time (a spurious warning) is described in:
https://github.com/sphinx-doc/sphinx/issues/10112
The problematic check was removed in Sphinx v4.5:
https://www.sphinx-doc.org/en/master/changes.html#id334
The issue of spurious warnings was fixed in v5.x:
https://github.com/sphinx-doc/sphinx/pull/10137
Technically it would be suitable to add negative version pin of Sphinx for "4.4".
But that version is quite outdated and at least Debian never shipped Sphinx v4.4 in a stable release.
This change fixes the current CI build failure, which is caused by an incompatibility of `sphinxcontrib-applehelp` with the older version of Sphinx.

build: remove version pin for Sphinx

---

docs/changelog.rst
extra/_beet

The `zsh` completion script for the `beet` command is more portable now:
- avoids the `mawk`-specific `{,n}` regex operator
- a directly usable `sqlite3` output format is selected explicitly, when retrieving suggestions for field values; this avoids the previously used GNU-`sed`-specific post-processing of the `sqlite3` output
- `zsh` completion caching is enabled for the `beet` command and its parameter contexts, even if not enabled globally by the user; caching is required for field value suggestions
Fixes #3546.

Fixes zsh completion dependency on specific awk/sed/sqlite3 versions and settings

---

.pre-commit-config.yaml
beets/dbcore/query.py
beets/dbcore/types.py
beets/ui/commands.py
beetsplug/export.py
beetsplug/permissions.py
beetsplug/replaygain.py
setup.cfg
test/plugins/test_ihate.py
test/plugins/test_lyrics.py
test/plugins/test_spotify.py
test/plugins/test_subsonicupdate.py
test/plugins/test_the.py
test/plugins/test_web.py
test/plugins/test_zero.py
test/test_metasync.py
tox.ini

Recent commits have been showing the formatting action failing due to black and isort not being pinned to a specific version in the tox. Changes to the tool were causing additional formatting to be applied to a small subset of files that the PRs hadn't actually touched. This PR pins the versions in the tox files to the current versions while also applying the few changes that have occurred.
In the future, upgrading the formatters will be done in a PR process, explicitly, to catch this kind of change.

Pin formatters version

---

beets/util/functemplate.py
docs/changelog.rst

Remove unused functions. Fixes #5103.
The function `ex_varassign` is never called. The function `ex_lvalue` is only called by `ex_varassign`.

Remove unused functions

---

beetsplug/advancedrewrite.py
test/plugins/test_advancedrewrite.py

Well, this is awkward. The second for-loop for the advanced rules ended up overwriting the template fields for the simple rules, nullifying the main reason for merging the simple rule support into this plugin.
This bug was introduced in #5044, and previous test cases unfortunately didn't cover it. A combined test case has thus been introduced as a regression test for this bug.
Please let me know if you'd like to have a changelog entry for this issue.

advancedrewrite: Fix simple rules being overwritten by advanced rules

---

beetsplug/convert.py
docs/changelog.rst

I've noticed that `beet convert` with the `never_convert_lossy_files: yes` just copies `.wav` files instead of converting them. This fixes that. (see commit message for details)

convert: Correctly identify WAVE format as lossless

---

beets/autotag/mb.py
beets/ui/commands.py
docs/changelog.rst

Fixes when you import a release with mixed media, the importer just shows the first medium for every medium.
https://github.com/beetbox/beets/issues/4947
Is this the best fix? Any ideas for improving the format?
```
$ beet imp .
/Volumes/Music/ti/hh/Four (14 items)
Match (97.7%):
Hampton Hawes with Barney Kessel, Shelly Manne & Red Mitchell - Four!
≠ media, year
MusicBrainz, 2xHybrid SACD (CD layer), 2023, US, Contemporary Records, CR00501, Contemporary Records Acoustic Sounds Series
https://musicbrainz.org/release/03f118d7-99bb-4daa-ad58-ab86d5325398
* Artist: Hampton Hawes with Barney Kessel, Shelly Manne & Red Mitchell
* Album: Four!
* Hybrid SACD (CD layer) 1
≠ (#2-1) Yardbird Suite (6:43) -> (#1-1) Yardbird Suite (6:40)
≠ (#2-2) There Will Never Be Another You (7:02) -> (#1-2) There …
```

Fix Media Headers on Import

---

docs/changelog.rst

missing changelog for #5153

---

beetsplug/unimported.py
docs/changelog.rst

Fixes #5130 
only immediate children of ignored directories were discounted.

bugfix: ignore subdirectories of ignored directories in unimported plugin

---

beetsplug/smartplaylist.py
docs/changelog.rst
docs/plugins/index.rst
docs/plugins/smartplaylist.rst
test/plugins/test_smartplaylist.py

Allow generating extm3u playlists so that they contain additional item fields such as the `id`.
The feature is required by the [webm3u plugin](https://github.com/mgoltzsche/beets-webm3u) (M3U server) to transform playlists using a request based item URI template which may require additional fields such as the `id`, e.g. `beets:library:track;$id`.

smartplaylist: allow exporting item fields, rename m3u8 output to extm3u

---

docs/changelog.rst
test/plugins/test_art.py
test/plugins/test_bareasc.py
test/plugins/test_export.py
test/plugins/test_fetchart.py
test/plugins/test_keyfinder.py
test/plugins/test_lyrics.py
test/plugins/test_player.py
test/plugins/test_smartplaylist.py
test/plugins/test_spotify.py
test/plugins/test_types_plugin.py
test/plugins/test_zero.py
test/test_art_resize.py
test/test_autotag.py
test/test_config_command.py
test/test_dbcore.py
test/test_files.py
test/test_importer.py
test/test_library.py
test/test_mb.py
test/test_plugins.py
test/test_query.py
test/test_sort.py
test/test_ui.py
test/test_ui_commands.py
test/test_util.py

As a first-time contributor with a background in researching Python unit tests, I conducted a thorough static analysis of the project's test code. This examination revealed various "test smells" that could potentially degrade both the efficiency and quality of our tests. To address these issues, I've refactored the relevant code segments. The modifications I propose not only aim to eliminate these inefficiencies but are also expected to reduce execution time within GitHub Actions. This reduction could contribute to lower operational costs for the project.
Test smells refactored:
- Suboptimal Assert: Instead of using statements such as assertIsNone, assertIsInstance, always simply use assertTrue or assertFalse. This will decrease the code overall readability and increase the execution time …

Enhancement: Refactor Test Code for Efficiency and Quality

---

beets/dbcore/db.py
beets/library.py

As I was devving, I did something wrong and had `beet mv` command fail on me.
Later, having spent an hour investigating why beets kept throwing me 'User-defined function raised exception' I discovered that it was failing because that previous `beet mv` command ended up writing value `NULL` in one of the items' `path` column. This was not handled well by the `BYTELOWER` implementation.
Since we do not have a **NOT NULL** constraint for the `path` column in the db, it's best to insure ourselves against this kind of stuff anyways.

Handle NULL values in the path column

---

.mypy.ini
beets/dbcore/__init__.py
beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/util/__init__.py
beetsplug/playlist.py
test/test_dbcore.py

While working on the DB optimization and looking at updates upstream I discovered one query which does not follow the `FieldQuery` interface —`PlaylistQuery`, so I looked into it in more detail and ended up integrating it as a `FieldQuery`.
One special thing about it is that it uses **IN** SQL operator, so I added implementation for this sort of query outside the playlist context, see `InQuery`.
Otherwise, it seems like `PlaylistQuery` is a field query with a special way of resolving values it wants to query. In the future, we may want to consider moving this kind of custom _initialization_ logic away from `init` methods to factory/@classmethod: this should make it more clear that the purpose of such logic is to resolve the data that is required to define a particular `FieldQuery` class …

Enforce the same interface across all `...Query` implementations

---

.mypy.ini
setup.cfg
tox.ini

Move `mypy` configuration to `setup.cfg` and define the paths to lint in the
configuration, removing the need to explicitly specify them in `tox.ini`.

Configure mypy

---

docs/index.rst

Update documentation to link to Libera.Chat for IRC support
Changed the reference to Libera.Chat in the documentation to a hyperlink pointing to https://libera.chat/ for better accessibility
Fixes #X.  
(...)

Update index.rst to link to Libera.Chat

---

.github/workflows/make_release.yaml
extra/release.py

I humbly present a solution our lack of releases: a workflow that can be triggered to automatically create one. This workflow builds the project, creates a GitHub release, and publishes beets to PyPi, for a one-stop solution.
@sampsyo this would make it much easier to create releases, as it requires only one little interaction: going to the actions tab and entering a version number. Once that's done, the workflow should take care of the rest. 
I have only tested the `build` job so far, since I can't do anything about the pypi or do a release just to test, but the code is lifted from other similar actions and should work fine.
It also requires one piece of setup. This is that PyPi must be set up with a [trusted publisher](https://docs.pypi.org/trusted-publishers/) to receive the new …

Add a workflow for easily creating releases

---

beetsplug/absubmit.py
beetsplug/acousticbrainz.py
beetsplug/deezer.py
beetsplug/embyupdate.py
beetsplug/fetchart.py
beetsplug/kodiupdate.py
beetsplug/lyrics.py
beetsplug/plexupdate.py
beetsplug/spotify.py
beetsplug/subsonicplaylist.py
beetsplug/subsonicupdate.py
docs/changelog.rst
test/plugins/lyrics_download_samples.py

Fixes bug where some plugin commands hang indefinitely. 8 years have passed since opening https://github.com/psf/requests/issues/3070, and we still have to deal with this stuff 😔 10 seconds value have been chosen as it's used multiple times in the codebase.

Add timeout argument to all `requests` calls

---

test/test_files.py

A trivial changes to skip test which requires reflink.

Add missed `HAVE_REFLINK` in test_files.py

---

beets/util/__init__.py
docs/changelog.rst

Rigth now it creates something like:
```
.../Perota Chingo/Un viajecito/.12 Rie Chinito.flac64u8gm5u.beets
```
where no separatio  between temp name and file extention, and it makes quite hard to read it.
So, this changes adjust name to
```
.../Perota Chingo/Un viajecito/.12 Rie Chinito.flac.64u8gm5u.beets
```
This was one of forgotten fixup from https://github.com/beetbox/beets/commit/8d50301be58463ac860cafaf898670fccb525bbe
Fixes #X.  
(...)

Adjust temporary files

---

.github/workflows/ci.yaml
CONTRIBUTING.rst
beets/autotag/mb.py
beets/dbcore/types.py
beets/library.py
beets/logging.py
beets/ui/commands.py
beets/util/__init__.py
beets/util/artresizer.py
beets/util/functemplate.py
beetsplug/discogs.py
beetsplug/substitute.py
docs/changelog.rst
docs/dev/plugins.rst
docs/guides/main.rst
setup.py

Fixes #5222.  
Drop Python 3.7. `pyupgrade` is responsible for most of the changes in the code. I undid some of the bits it attempted to update that aren't strictly necessary:
1. Converting `List/Dict/Tuple` -> `list/dict/tuple` in modules that have `from __future__ import annotations` import. This should be done in a separate PR, and for all modules
2. Converting some `.format(` calls to f-strings. It didn't do it consistently, and it should also be done in a separate PR, I believe.
Python upgrade unblocks several other PRs, for example #5266 and #5248.

Upgrade to Python 3.8 / drop Python 3.7

---

.github/workflows/make_release.yaml
docs/changelog.rst
extra/release.py

This hopefully fixes the issue we experienced where the version was not incremented before the package was built. This should make sure that it works correctly.

Fix the version error in the release workflow

---

beets/importer.py
docs/changelog.rst
test/test_importer.py

The docs say:
> The `auto` option uses reflinks when possible and falls back to plain
> copying when necessary.
I've been using this option for a while, and recently discovered that despite the option, copying fails between two BTRFS filesystems with:
Error: OS/filesystem does not support reflinks. during link of paths /mnt/fs1/file, /mnt/fs2/file
I tracked this down to how the configuration is handled in the importer.
I love beets dearly, thanks for your great work :)

Fix `reflink: "auto"` option

---

beets/ui/completion_base.sh

Some functions used by the bash completion script have become deprecated.  This was causing the test suite to break on faster-moving distributions (e.g. Arch Linux and Gentoo).  The issue is only noticeable because the tests for the completion function explicitly disallow compatibility implementations from being loaded.  Rather than allowing compatibility implementations, I've added some basic logic to the completion script so that older and newer versions of `bash-completion` can be supported simultaneously.
For some reason, this issue wasn't caught on CI - I think the newer `bash-completion` hasn't reached the distribution used there.  Still, this code is now forward-compatible.
Fixes #5243 ([see here](https://github.com/beetbox/beets/issues/5243#issuecomment-2164074169)).
I suppose it …

Update the bash completion script

---

beets/autotag/hooks.py
beets/autotag/match.py
beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/types.py
beets/library.py
beets/util/pipeline.py
beetsplug/bareasc.py
beetsplug/bpd/__init__.py
beetsplug/fuzzy.py
beetsplug/replaygain.py
beetsplug/the.py
test/plugins/test_albumtypes.py

I noticed that some development work was waiting on cleaner `mypy` runs, so I thought I would help out a bit.  This PR just contains a number of miscellaneous fixes across the codebase that I hit.  I'm happy to add more, or remove any problematic changes (though I don't think I've broken anything, only type annotations have changed).

Resolve some 'mypy' errors

---

.github/workflows/changelog_reminder.yaml
beets/random.py

Use `pull_request_target` event for the changelog update reminder
See https://github.com/marketplace/actions/comment-pull-request#permissions for more details.
Additionally, refactor the workflow into a more canonical form utilising the `tj-actions/changed-files` GitHub action.

Fix changelog workflow

---

.github/workflows/lint.yml
docs/changelog.rst
poetry.lock
pyproject.toml
setup.cfg

See https://github.com/beetbox/beets/security/dependabot/7

Fix black security vulnerability

---

pyproject.toml

I realised that when users install beets, this `release` script would also get installed for them, which is not ideal, I guess.

Remove release script from pyproject

---

.github/workflows/make_release.yaml

This adds a step to the GitHub release so that it sends a toot on Fosstodon, beets' Mastodon account, to publicise that and get some engagement!
Not tested, but this is lifted straight from the action repo so it *should* be okay. @snejus for a sanity check if you wouldn't mind

Make the release send a toot on Fosstodon

---

.github/workflows/changelog_reminder.yaml
beets/plugins.py

Quote the breaking glob as noted by @bal-e.

Fix changelog reminder workflow

---

.github/workflows/make_release.yaml
poetry.lock
pyproject.toml

This was missed out in #5266: build the Python package distribution using Poetry in the release workflow.
In addition to the above, I slightly simplified the release pipeline which should hopefully make it easier to debug if things go wrong in the future.

Update release workflow with poetry

---

.github/workflows/ci.yaml
.gitignore
pyproject.toml
setup.cfg

Fixes #5242.
This PR moves coverage measurement from the default `pytest` invocation to a separate action `test-with-coverage`.

Do not run coverage by default

---

poetry.lock
pyproject.toml
setup.cfg

Have come across this interesting case since I submitted a PR with an edit in a file that falls out of these exclusion rules: #5233 . :grin:

Remove flake8 docstrings and its exclusion rules

---

beets/dbcore/db.py
beets/importer.py
beets/test/_common.py
beets/test/helper.py
beets/ui/__init__.py
beets/util/__init__.py
beets/util/artresizer.py
beetsplug/aura.py
beetsplug/convert.py
beetsplug/fetchart.py
beetsplug/replaygain.py
beetsplug/thumbnails.py
beetsplug/web/__init__.py
test/plugins/test_player.py
test/plugins/test_smartplaylist.py
test/test_importer.py
test/test_metasync.py
test/test_ui.py
test/test_ui_init.py

- **Replace py3_path by standard os.fsdecode**
- **Use native os.cpu_count**
- **Replace bytestring_path with os.fsencode**
These functions had been written before builtins achieving the same have been made available (in
Python 3.2 and 3.4). 
Now that they are available though, this PR updates the codebase to use builtin implementations rather than the custom ones.

Replace `py3_path` and `cpu_count` implementations with builtins

---

.github/workflows/ci.yaml

While the commit merged yesterday fixed the coverage upload to coveralls, it broke the source files preview on the platform.
This was due to the missing actions/checkout step in the coverage upload job.

Bring back source files to codecov

---

beets/autotag/hooks.py
beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/importer.py
beets/library.py
beets/util/__init__.py
beetsplug/aura.py
beetsplug/bareasc.py
beetsplug/bpd/__init__.py
docs/changelog.rst
docs/reference/query.rst
poetry.lock
pyproject.toml
setup.cfg
test/plugins/test_limit.py
test/plugins/test_web.py
test/test_autotag.py
test/test_dbcore.py
test/test_query.py

Another and (hopefully) final attempt to improve querying speed.
Fixes #4360 
Fixes #3515
and possibly more issues to do with slow queries.
This PR supersedes #4746.
The `album` and `item` tables are joined, and corresponding data from `item_attributes` and `album_attributes` is merged and made available for filtering. This enables to achieve the following:
You can see that now querying speed is more or less constant regardless of the query, and the speed is mostly influenced by how many results need to be printed out
Compare this with what we had previously
https://github.com/beetbox/beets/issues/5318
https://github.com/beetbox/beets/issues/5319

Make queries fast, filter all flexible attributes

---

beets/autotag/hooks.py
beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/importer.py
beets/library.py
beets/util/__init__.py
beetsplug/aura.py
beetsplug/bpd/__init__.py
docs/changelog.rst
docs/reference/query.rst
poetry.lock
pyproject.toml
setup.cfg
test/plugins/test_limit.py
test/plugins/test_web.py
test/test_autotag.py
test/test_dbcore.py
test/test_query.py

Fixes: #5325 
As @arsaboo underlined, this change makes interaction with `beets` unbearably slow for systems that have SQLite version below `3.38.0`. This is what Ubuntu ships with by default.
I have also tested other commands, like `beet update`, and found that even with up to date SQLite version, this command takes twice as long to execute as before.
Thus, I think that the performance gain we see using some of the more complex queries is not worth the performance loss for the most common operations. Therefore, at least for now, I am reverting this change an leaving this work on the `only-fast-filtering` branch to be revised.

Revert only fast queries

---

beets/util/__init__.py
beetsplug/aura.py
docs/changelog.rst
poetry.lock
pyproject.toml

Use `typing_extensions` only for Python <= 3.10.
`Self` was added in Python 3.11.
`TypeAlias` was added in Python 3.10.

Use typing_extensions only when needed

---

beets/autotag/hooks.py
beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/library.py
beets/util/__init__.py
beetsplug/limit.py
docs/changelog.rst
docs/reference/query.rst
setup.cfg
test/test_autotag.py
test/test_query.py

Fixes #4360
This PR enables querying albums by track fields and tracks by album fields, and speeds up querying albums by `path` field.
It originally was part of #5240, however we found that the changes related to the flexible attributes caused degradation in performance. So this PR contains the first part of #5240 which joined `items` and `albums` tables in queries.

Filter albums by tracks fields and vice versa

---

beets/util/hidden.py

The implementation was unnecessarily convoluted.  I've rewritten it to declare fewer functions, and it now uses `pathlib`.
P.S. I'm starting to feel bad for opening so many PRs :P

Rework `beets.util.hidden`

---

beets/test/helper.py
beets/util/__init__.py
beets/util/artresizer.py
beetsplug/fetchart.py
beetsplug/play.py
pyproject.toml
test/plugins/test_art.py
test/plugins/test_bareasc.py
test/plugins/test_embedart.py
test/plugins/test_info.py
test/plugins/test_play.py
test/plugins/test_playlist.py
test/test_art_resize.py
test/test_config_command.py
test/test_importer.py
test/test_plugins.py
test/test_ui_commands.py

Fixes #5229, is part of #5361 and relates to #5285.
I have to admit thsi was a fairly tough task - I initially assumed that the problem lies
with how the tests are setup, and that we're probably missing some `teardown_beets` calls
here and there.
Unfortunately, it was not so simple. I came across several issues that gave rise to
leftover temporary files:
1. `fetchart`, `artresizer` and `play` handling of temporary files. These plugins created
isolated temporary files outside of the directories that tests clean up. You will find
I added a couple of functions (namely `get_module_tempdir`) that force these plugins to
create files in directories determined by their module names. This way we can clean up
after them using the new `CleanupModulesMixin`.
2. Tests that ran temporary directories …

Make sure tests do not leave any temp files behind

---

beets/autotag/hooks.py
beets/autotag/mb.py

These days musicbrainz returns unicode strings as expected.

Remove redundant unicode decoding

---

beets/dbcore/queryparse.py

I surprisingly found that many queries for fields that exist in the database are 'slow'. Querying items with `month:0` used a slow query while `title:0` used a fast one.
I found the mistake in the logic: the field existence in the db check was done *after* prepending the table name to the field. This meant that the logic wrongly checked e.g. `items.field` instead of `field`.
This commit fixes the above and renames the variables for more clarity.

Fixup: use fast queries for fields shared between albums and items tables

---

beets/autotag/__init__.py
beets/autotag/mb.py
beets/importer.py
beets/test/helper.py
docs/changelog.rst
test/test_importer.py

I believe this fixes #4785, but I might be misunderstanding the description and it might already be fixed.
Tagging @JOJ0 since they created both the bug linked above, and 5bf4e3d92f5b4010a19cd3e8222fbf28b7b844e0 which mentions it.

fix(import): don't throw away album flexible fields

---

beets/library.py
docs/changelog.rst
docs/reference/pathformat.rst
test/test_library.py

This creates a new template function that capitalizes the text (make the first character have upper case and the rest lower case). Example:
```console
beet list -f '%capitalize{$title}'
```
This does not do the same as the *%title* function.
(...)

Create a new template function: capitalize

---

.github/workflows/ci.yaml
beets/test/_common.py
beets/test/helper.py
beets/util/__init__.py
docs/reference/config.rst
poetry.lock
pyproject.toml
test/test_files.py
test/test_importer.py

See my comment under #5406 for context
> The build on win32 is failing to install reflink because it's [only supported until Python 3.7](https://gitlab.com/rubdos/pyreflink/-/blob/master/setup.py?ref_type=heads).
>
> I will address this in a separate PR and rebase this one accordingly once the fix is merged.
>
> Note: this issue popped up now because I added a new requests-mock dependency which invalidated cached dependencies.

Update dependencies and do not install reflink on Windows for tests

---

docs/reference/config.rst

Solves #5314.
I'm not entirely sure what this documentation should look like, especially the examples (I've never personally had to use this feature anyway).  Still, this is better than leaving it undocumented.

Document `overwrite_null`

---

beetsplug/fetchart.py
docs/changelog.rst
test/plugins/test_art.py

Defer the evaluation of the source file removal options (`import.delete` and `import.move`) to the point where the fetchart plugin is actually called instead of only evaluating those configuration options on plugin initialization.
This is to allow other plugins (such as the [ytimport](https://github.com/mgoltzsche/beets-ytimport/blob/v1.8.1/beetsplug/ytimport/__init__.py#L194) plugin) to invoke the import directly (within the same python process; implicitly invoking the fetchart plugin) with temporarily overwritten configuration options.
Addresses https://github.com/beetbox/beets/issues/5167#issuecomment-2106465172

fetchart: defer file removal config option evaluation

---

beetsplug/deezer.py
docs/changelog.rst

This PR adds gracefully handling requests error in teh Deezer plugin. Right now, it errors out when it receives error:
```bash
File "/home/arsaboo/.local/bin/beet", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/arsaboo/.local/lib/python3.12/site-packages/beets/ui/__init__.py", line 1865, in main
File "/home/arsaboo/.local/lib/python3.12/site-packages/beets/ui/__init__.py", line 1852, in _raw_main
File "/home/arsaboo/.local/lib/python3.12/site-packages/beets/ui/commands.py", line 1395, in import_func
import_files(lib, paths, query)
File "/home/arsaboo/.local/lib/python3.12/site-packages/beets/ui/commands.py", line 1326, in import_files
session.run()
File …
```

Deezer: Improve requests error handling

---

beetsplug/discogs.py
docs/changelog.rst
test/plugins/test_discogs.py

Fixes the following error:
```
File "/home/konstantink/.local/bin/beet", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/konstantink/.local/share/pipx/venvs/beets/lib64/python3.12/site-packages/beets/ui/__init__.py", line 1865, in main
File "/home/konstantink/.local/share/pipx/venvs/beets/lib64/python3.12/site-packages/beets/ui/__init__.py", line 1852, in _raw_main
File "/home/konstantink/.local/share/pipx/venvs/beets/lib64/python3.12/site-packages/beets/ui/commands.py", line 1395, in import_func
import_files(lib, paths, query)
File "/home/konstantink/.local/share/pipx/venvs/beets/lib64/python3.12/site-packages/beets/ui/commands.py", line 1326, in import_files
session.run()
File …
```

Fixes TypeError in the Discogs plugin

---

beets/library.py
docs/changelog.rst
poetry.lock
pyproject.toml

Fixes #5168 and follows on #5333.
Thanks to @snejus for suggesting `platformdirs` instead of trying to roll my own XDG `user-dirs.dirs` parser.  It's well-tested, supports more platforms, and may come in handy for other features in the future.

Add support for `platformdirs`

---

beetsplug/ftintitle.py

Fixes bug introduced in #5356.
The new `keep_in_artist` option for the ftintitle plugin was introduced in #5356.
However, it was not passed to the `imported` function. (See @chrishoage's comment in #5356).
This is fixed with this PR.

Fix missing keep_in_artist option in ftintitle plugin (introduced in #5356)

---

CONTRIBUTING.rst
beets/dbcore/query.py
beets/library.py
beetsplug/web/__init__.py
docs/changelog.rst
test/test_library.py

Fixes #4709 SQL use of Double Quoted Strings.
Replacing #5236

Reworked #4709 after latest release

---

beetsplug/ftintitle.py
docs/changelog.rst
test/plugins/test_ftintitle.py

Fixes #5441 
This small change explicitly passes the `for_artist` keyword to the `plugins.feat_tokens` function that constructs the regex for matching existing "feat. X" parts in song titles.
Previously, it was not passed and set to the default (`True`), which caused using the pattern intended for the artist field to also be used for the title field.
This caused some false positives as shown in #5441

ftintitle: Fix false positives in "feat. X" detection in title

---

.github/workflows/ci.yaml
.github/workflows/lint.yml

This fixes coverage submission in CI, which has been failing for PRs submitted from forks.

Make coverage token available in forks

---

beetsplug/convert.py
docs/changelog.rst
test/plugins/test_convert.py

I was running the `convert` plugin with the following config:
```
no_convert: samplerate:..48000 bitdepth:..16
```
but anything that was 24/48 was also not being converted, this was due to the code returning `False` for `should_transcode` if any part of the query matches, rather than considering the whole query. This meant that `bitdepth:...16` was being ignored.
I have changed this so the `no_convert` value is considered as one query.

Fix the no_convert option of the convert plugin stopping conversion when there is only a partial match.

---

.github/workflows/ci.yaml
.github/workflows/lint.yml
beetsplug/convert.py
poetry.lock
pyproject.toml
test/plugins/test_convert.py

Seems like readthedocs build expects docs dependencies to be available
as an extra, see one of the failing builds: https://app.readthedocs.org/projects/beets/builds/26079213/.
You can see this has been failing due to missing 'pydata_sphinx_theme' which is one of our dependencies:
```
raise ThemeError(__('no theme named %r found (missing theme.toml?)') % name)
sphinx.errors.ThemeError: no theme named 'pydata_sphinx_theme' found (missing theme.toml?)
Theme error:
no theme named 'pydata_sphinx_theme' found (missing theme.toml?)
```

Fix docs build

---

beets/importer.py
docs/changelog.rst
test/test_importer.py

Fixes #4840 by converting input values to strings before they are used. Modifies the test cases for ``set_fields`` to appropriately test this behavior.

Fix the ``TypeError`` when ``import.set_fields`` is provided non-string values

---

beetsplug/listenbrainz.py
docs/changelog.rst

Improve ListenBrainz error handling and simplify playlist handling

---

beets/test/_common.py
beets/test/helper.py
setup.cfg
test/plugins/test_aura.py
test/plugins/test_mbsync.py
test/test_library.py
test/test_sort.py

This PR refactors the test codebase by removing redundant functions and simplifying item
and album creation. Key changes include:
- Removed redundant `_item_ident` index tracker from `_common.py`.
- Removed `album` function from `_common.py` replacing it with direct `library.Album` invocations.
- Removed `generate_album_info` and `generate_track_info` functions, replacing them directly with `TrackInfo` and `AlbumInfo`.
- Updated `setup.cfg` to exclude test helper files from coverage reports.
- Adjusted the tests regarding the changes, and simplified `test_mbsync.py`.

Test helpers: Remove unneeded data generation abstractions

---

beets/test/helper.py
poetry.lock

Update mediafile to 0.13.0

---

beets/test/helper.py
beetsplug/substitute.py
docs/changelog.rst
docs/plugins/substitute.rst
test/plugins/test_substitute.py

This utilises regex substitution in the substitute plugin. The previous approach only used regex to match the pattern, then replaced it with a static string. This change allows more complex substitutions, where the output depends on the input.
Say we want to keep only the first artist of a multi-artist credit, as in the following list:
```
Neil Young & Crazy Horse -> Neil Young
Michael Hurley, The Holy Modal Rounders, Jeffrey Frederick & The Clamtones -> Michael Hurley
James Yorkston and the Athletes -> James Yorkston
````
This would previously have required three separate rules, one for each resulting artist. By using a regex substitution, we can get the desired behaviour in a single rule: 
```yaml
substitute:
^(.*?)(,| &| and).*: \1
```
(Capture the text until the first `,` ` &` or ` …

Perform a regex substitution in the substitute plugin

---

beets/autotag/match.py
beets/config_default.yaml
docs/changelog.rst

Fixes #5148.  
When importing, the code that matches tracks does not consider the medium number. This causes problems on Hybrid SACDs (and other releases) where the artists, track numbers, titles, and lengths are the same on both layers.
I added a distance penalty for mismatching medium numbers.
Before:
```
$ beet imp .
/Volumes/Music/ti/Red Garland/1958 - All Mornin' Long - 1 (6 items)
Match (95.4%):
The Red Garland Quintet - All Mornin' Long
≠ media, year
MusicBrainz, 2xHybrid SACD (CD layer), 2013, US, Analogue Productions, CPRJ 7130 SA, mono
https://musicbrainz.org/release/6a584522-58ea-470b-81fb-e60e5cd7b21e
* Artist: The Red Garland Quintet
* Album: All Mornin' Long
* Hybrid SACD (CD layer) 1
≠ (#2-1) All Mornin' Long (20:21) -> (#1-1) All Mornin' Long (20:21)
≠ (#2-2) They Can't …
```

Fix Hybrid SACD importing

---

test/plugins/test_autobpm.py

Debian doesn't have `librosa`. Allow the tests to continue.

Skip autobpm tests if librosa isn't available

---

docs/plugins/zero.rst

I've spent 2 hours troubleshooting why none of my music had genre tag. It was because the single `genre`, without `s` doesn't seem to cover any good ganre tags... at least it didn't on my opus files
looking at the code: https://github.com/beetbox/mediafile/blob/7ecd86101ec3344e7fb25bbf781cd7f86646aa9d/mediafile.py#L1669-L2167 i don't honestly know why anyone created the single `ganre` field in the first place

Change `zero` documentation mentions of genre to genres

---

beetsplug/lyrics.py
docs/changelog.rst
test/plugins/test_lyrics.py

The `synced` config flag was not working the way the docs described it for the LRCLIB source. With `synced: yes`, if a track does not have synced lyrics, but does have plain lyrics, the plugin would return no lyrics. The docs imply that, with the flag enabled, it would still use plain lyrics if there are no synced lyrics.
LRCLIB API call that returns plain lyrics can be found [here](https://lrclib.net/api/get?artist_name=Hania%20Rani&track_name=Moans&album_name=Ghosts&duration=274).

lyrics: Fallback to plain lyrics if synced lyrics not available

---

beets/autotag/__init__.py
beets/util/__init__.py
docs/changelog.rst
test/test_autotag.py

This PR fixes an issue where the `beet write` command repeatedly shows differences for certain fields (`mb_artistid`, `mb_albumartistid`, `albumtype`) even after writing the tags. 
This happens because these fields are actually stored as lists in the media files (`mb_artistids`, `mb_albumartistids`, `albumtypes`), but beets maintains both single and list versions in its database.
This PR addresses this issue in a non-invasive way: the fix ensures consistency between single fields and their list counterparts by:
1. When setting a single field value, making it the first element of the corresponding list
2. When setting a list, using its first element as the single field value
This resolves long-standing issues #5265, #5371, and #4715 where users experienced persistent "differences" in these …

Stop perpetually writing `mb_artistid`, `mb_albumartistid` and `albumtypes` fields

---

pyproject.toml

wheels are directly unpacked into site-packages, so this means likely conflict with other packages
if a changelog entry is needed, I am happy to add one.  tests/docs seem not applicable (as this is purely a packaging issue)

pyproject.toml: don't install docs et al into the wheel

---

beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/dbcore/types.py
beets/library.py
beets/util/__init__.py

Thanks to @wisp3rwind's suggestion this PR adds types to the relationship between `Model`, `Database` and `Library`.
Then I worked through the rest of the issues found in the edited files. Most of this involved providing type parameters for generic types (or defining defaults, rather 😉).
There `queryparse` module had a somewhat significant issue where the sorting construction logic only expected to receive `FieldSort` subclasses, while `SmartArtistSort` was not one. Thus `SmartArtistSort` has now been forced to behave and is a `FieldSort` subclass. It's also been moved to `query.py` module which is where the rest of sorts are defined.

Properly type db on the model, sort out generic types issues

---

beets/util/__init__.py

Fixes #4622.
I don't think this changes other behavior of the function, but it fixes the problem with the moved files being created with the wrong permissions for me.

Use shutil.move() to move files.

---

beets/autotag/match.py
docs/changelog.rst
poetry.lock
pyproject.toml

Fixes #5207.
This PR replaces the `munkres` library with `lap` (Linear Assignment Problem solver) for computing optimal track assignments during the auto-tagging process. The main changes are:
- Remove `munkres` dependency and add `lap` and `numpy` dependencies
- Refactor the track assignment code to use `lap.lapjv()` instead of `Munkres().compute()`
- Simplify cost matrix construction using list comprehension
- Move config value reading outside of `track_distance` function to improve performance
The motivation for this change comes from benchmark comparisons showing that LAPJV (implemented in the `lap` library) significantly outperforms the Munkres/Hungarian algorithm for the linear assignment problem. See detailed benchmarks at: https://github.com/berhane/LAP-solvers
The change should …

Replace munkres with lapjv for track assignment

---

test/plugins/test_bucket.py

2025 won't be in the future, forever.
Fixes: https://bugs.debian.org/1091495

Future proof BucketPluginTest.test_year_single_year_last_folder

---

beets/autotag/match.py
beets/test/helper.py
test/test_autotag.py

A regression was introduced when adjusting the track matching logic to use `lapjv` instead of `munkres`. The `lapjv` algorithm returns `-1` for unmatched items, which wasn't being handled correctly in the matching logic. This caused incorrect track assignments when importing new music.
- Modified the mapping creation to filter out unmatched items (where index is `-1`)
- Updated test case to properly catch this scenario

Fix track matching regression

---

beetsplug/lastgenre/__init__.py
docs/changelog.rst

- Fix `lastgenre -A` in combination with config option `source: track` (_Tracks inherited the album's genre even when this option was set_)
- Now, When an album-level genre is set already, single tracks don't fall back to the album's genre and request their own last.fm genre.
- Fix log-level and message wording being slightly different for `source:` track, album, artist genre
- Now log messages follow the same wording, level and structure throughout.
_Note: This was split out from PR #4982_

lastgenre: Fix track-level handling and streamline logging

---

.github/workflows/ci.yaml
docs/conf.py
extra/release.py
test/test_release.py
test/test_ui.py

Adjust Sphinx configuration and release script
Changes:
- Update `source_suffix` in docs/conf.py to use dict format as required by newer Sphinx
versions
- Fix typo in theme config: `pygment_light_style` -> `pygments_light_style`
- Improve release script to handle Sphinx intersphinx output formatting:
- Replace tabs with spaces for consistent parsing
- Add reference to sphinx.ext.intersphinx command in docstring
- Update line parsing to match space-indented format
- Restructure CI workflow to ensure relevant dependencies are installed and changelog formatting is tested.
These changes ensure compatibility with newer Sphinx versions and improve the robustness
of the release script's reference parsing.
Edit:
While working on this PR GitHub decided to upgrade their linux/ubuntu runners with …

Fix Sphinx configuration post-update

---

beets/dbcore/db.py
beets/dbcore/query.py
beets/dbcore/queryparse.py
beets/importer.py
beets/library.py
beetsplug/aura.py
beetsplug/bpd/__init__.py
docs/changelog.rst
test/test_dbcore.py
test/test_query.py

Fixes a `sqlite3.OperationalError` that occurs when querying *any* field and a field that only exists in the relation table. For exaple, trying to list albums that contain **keyword** and contain a track with **foo** in its title:
```
beet list -a keyword title:foo
```
SQLite fails when JOINs contain ambiguous column references. This happened because:
- *any* Album field search looks at `album`, `albumartist` and `genre` fields.
- The second part of the query `title:foo` queries a field in the `items` table, which got
JOINed with `albums`
- Some fields (like `album`) exist in both `items` and `albums` tables, thus SQLite couldn't resolve which table's column to use
- Centralize query construction in `LibModel` with consistent table qualification
- Add methods:
- `field_query()` - Creates …

Handle ambiguous column names in queries involving 'any' field and a relation field

---

beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst
test/plugins/test_lyrics.py

Fixes #5102
- Fixed fetching lyrics from `lrclib` source. If lyrics for a specific album, artist, and title combination are not found, the plugin now searches for the artist and title and picks the most relevant result, scoring them by
1. Duration similarity to the target item 
1. Availability of synced lyrics
- Updated the default `sources` configuration to prioritize `lrclib` over other sources for faster and more reliable results.
- Added type annotations to `fetch` method in all backends.
- Introduced `LRCLyrics` and `LRCLibItem` classes to encapsulate lyrics data and improve code structure.
- Enhanced error handling and logging enchancements to the `LRCLib` backend. These will be added to the rest of the backends in a separate PR.
- Added new tests to cover the updated functionality …

Fix lrclib lyrics

---

docs/guides/main.rst

Added a quick checkpoint to ensure the config file is set up correctly prior to users importing their music library. This was something I discovered later after running into an issue with my config file and hope it helps new users avoid the issues I had.

Checkpoint to make sure config file is set up correctly added to the getting started guide 

---

beetsplug/_typing.py
beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst
setup.cfg
test/plugins/lyrics_pages.py
test/plugins/test_lyrics.py

I've made several updates to the lyrics plugin to enhance its functionality and address a few bugs. Here's a quick overview of what has changed:
- Fixed #4791: Resolved an issue with the Genius backend where it couldn't match lyrics if there was a slight variation in the artist's name.
* **Session Management**: Introduced a `TimeoutSession` to enable connection pooling and maintain consistent configuration across requests.
* **Error Handling**: Centralized error handling logic in a new `RequestsHandler` class, which includes methods for retrieving either HTML text or JSON data.
* **Logging**: Added methods to ensure the backend name is included in log messages.
* Added a new `dist_thresh` field to the configuration, allowing users to control the maximum tolerable mismatch between the …

Lyrics: Refactor Genius, Google backends, and consolidate common functionality

---

beets/test/helper.py
test/plugins/test_importadded.py
test/test_importer.py

Fixes a confusing typo when setting the MusicBrainz matcher in a few tests. It looks like the matcher defaults to `IDENT` so change it to that, since that would have been the value used in the tests with the typo.

Fix matcher typo

---

beets/util/__init__.py
docs/changelog.rst

Without explicitly closing this file descriptor, the temp file would be kept open until the program exited and could not be deleted by the fetchart plugin.
Fixes #5521

Close file descriptor generated from tempfile.mkstemp()

---

docs/faq.rst
docs/guides/tagger.rst

Update documentation to use specific GitHub issue templates instead of generic issue links. This helps users provide better structured feedback when reporting bugs or requesting features.
This was noted in https://github.com/beetbox/beets/issues/5610#issuecomment-2628985640

Populate bug issue template automatically

---

beetsplug/_typing.py
beetsplug/lyrics.py
docs/changelog.rst
docs/plugins/lyrics.rst
setup.cfg
test/plugins/test_lyrics.py

🎵 The Refactoring Blues 🎵 by [Claude](https://claude.ai)
Verse 1:
Got those lyrics plugin blues
Cleaning up some messy code
Moving classes, fixing views
Making changes down the road
Chorus:
We're refactoring tonight
Making the codebase clean and bright
Translation's got a brand new home
And ReST files found their own
Verse 2:
Added Microsoft Translate
Keeping tokens safe and sound
Config options up-to-date
Better structure all around
Bridge:
Path operations simplified
Groups of artists, neat and tied
Error handling's looking fine
Comments clear along each line
Verse 3:
RestFiles in their own class now
Cleaning imports, showing how
Better typing makes it clear
What should go and what stays here
Final Chorus:
We're refactoring tonight
Making the codebase clean and bright
Translation's got a …

Lyrics: Resurrect translations and refactor ReST and command line handling

---

beetsplug/convert.py
docs/changelog.rst

My library is managed using Beets for organization and [git-annex](https://git-annex.branchable.com/) as storage backend. Therefore when using this system, while my library files always exists on my filesystem, some files may be empty (without content). In this case, when I'm running the `convert` plugin,  I don't wants it to process files which are empty (same apply for any Beets plugin). Hence, I added a check that the file is readable as a `MediaFile` before doing any process. 
Before this fix, trying to encode an empty file would have lead to an error  while leaving `convert` doing its side-effects **and** `convert` would also copy empty files to destination for files that doesn't need to be re-encoded.
In my case, this is empty files, but the problem can be anything else (depending …

Fix convert plugin attempting to process a non-media file

---

beets/util/artresizer.py
docs/changelog.rst
test/plugins/test_embedart.py

ImageMagick 7.1.1-44 now outputs phash result in a different format (as of https://github.com/ImageMagick/ImageMagick/commit/d85a7583f9a96bf031941c24d774b71529de3ce0):
```shell
$ magick --version | head -n1
Version: ImageMagick 7.1.1-43 Q16-HDRI x86_64 afd817ca6:20241222 https://imagemagick.org
$ compare -metric PHASH a.jpg b.jpg NULL:
649.922
```
```shell
$ magick --version | head -n1
Version: ImageMagick 7.1.1-44 Q16-HDRI x86_64 f1c26bed0:20250222 https://imagemagick.org
$ compare -metric PHASH a.jpg b.jpg NULL:
4.25933e+07 (649.931)
```
Fixes #5527.

Fix IMBackend#compare on ImageMagick 7.1.1-44

---

beetsplug/listenbrainz.py
docs/changelog.rst
docs/plugins/listenbrainz.rst

Fix ocurrence of `UnboundLocalError` in plugins/listenbrainz > `get_tracks_from_listens()` when `mbid` is not available.
Removed a print statment.
Fix link to config.yaml.
Fix link to Listenbrainz "get the token" documentation.

fix: plugins/listenbrainz: Fix UnboundLocalError in cases where 'mbid' is not defined

---

.github/workflows/ci.yaml

Bump python version in the CI to current versions.
This is the same as #5503 that for some reason got closed when the merge of the `drop-py38` branch happened

Update python in CI

---

beets/util/pipeline.py

Typing Extensions is an optional requirement for `python>3.10`, thus
TypeVarTuple and Unpack need another import in higher python versions as `typing_extensions` is not available
see https://docs.python.org/3.10/library/typing.html for supported types
close #5695

typing_extensions requirement inconsistency

---

beetsplug/lastgenre/__init__.py
docs/plugins/lastgenre.rst
test/plugins/test_lastgenre.py

Fixes #5649, more precisely the behavior described in comment https://github.com/beetbox/beets/issues/5649#issuecomment-2732245358 where a last.fm genre was found for the album but `_resolve_genre()` kicked it out because it was't allowed by the whitelist which resulted in writing an empty genre as the final result.
- This fix makes sure that when no album genre is found the next stage is hit - returning with either the original genre (if any), the configured fallback genre or None.
- A new option `--debug` or configuration setting `extended_debug: yes` can be set to see precisely what tags were fetched during the track, album or artist stages prior to filtering by a whitelist or canonicalization tree. It's not enabled by default since it clutters up the debug log quite a bit especially …

Fix lastgenre returning empty genre instead of fallback genre

---

beetsplug/thumbnails.py
docs/changelog.rst
test/plugins/test_thumbnails.py

Using the correct function signature for g_file_new_for_path fixes the tests on s390x.
I do not have the full story on why this failed consistently only on s390x, but I guess the big endian might have something to play with this.
Here is how the tests were failing:
```
169s ___________________________ ThumbnailsTest.test_uri ____________________________
169s
169s self = <test.plugins.test_thumbnails.ThumbnailsTest testMethod=test_uri>
169s
169s     def test_uri(self):
169s         gio = GioURI()
169s         if not gio.available:
169s             self.skipTest("GIO library not found")
169s
169s >       assert gio.uri("/foo") == "file:///"  # silent fail
169s E       AssertionError: assert '' == 'file:///'
169s E
169s E         - file:///
169s
169s test/plugins/test_thumbnails.py:268: …
```

plugins/thumbnails: fix FFI with GIO on s390x

---

beets/autotag/hooks.py
beets/autotag/match.py
beets/plugins.py
beetsplug/deezer.py
beetsplug/discogs.py
beetsplug/mbsync.py
beetsplug/missing.py
docs/changelog.rst
docs/plugins/mbsync.rst
docs/plugins/missing.rst
test/plugins/test_discogs.py
test/plugins/test_mbsync.py

This PR adds support for alternate metadata backends in the `mbsync` and `missing` plugins, allowing them to work with any metadata backend the items are tagged with instead of being limited to just MusicBrainz.
Key changes:
- Removed redundant `albums_for_id` and `items_for_id` methods.
- Updated `album_for_id` and `track_for_id` implementations to return a single album/track as their names suggest.
- Updated both plugins to use the above functions instead of MusicBrainz-specific ones.
- Updated `missing` plugin docs to make it clear that missing albums for artists can only be obtained for the `musicbrainz` metadata backend
- This is possible with other backends but implementation was outside of this PR's scope.
- Slightly simplified the existing implementation
The changes maintain …

`mbsync` / `missing` plugins: consider all metadata backends

---

beetsplug/ftintitle.py

Due to reviewing #5718, I was looking at the `ftintitle` plugin (which I'm otherwise not familiar with). Given that it is simple enough, I quickly added typings. The second commit adds a refactoring that flattens the logic in the core `ft_in_title` function, motivated by the fact that I found this more difficult to read than necessary during the review.

Ftintitle typing

---

beets/dbcore/db.py
docs/changelog.rst
test/test_dbcore.py
test/test_library.py

This might be a quick one, depending on how you feel about it... It allows you to pickle DB model objects. I don't think this is used directly in Beets, but it might be useful in general. For instance, we encountered an issue where we wanted to quickly pickle an Item or Album. This sometimes worked and other times failed, which seemed quite inconsistent.
Some DB model methods and properties have the side effect of attaching an SQLite connection to self (._db), which prevents serialization. The fix is quite straightforward, so I thought we might want to integrate this into beets directly.

Allow to pickle db models by removing the current connection.

---

pyproject.toml
setup.cfg

which added some mypy config to pyproject.toml, leading to mypy ignoring setup.cfg (this shows up in CI output for #5701, but is not very visible since we currently ignore mypy errors)
Related: https://github.com/beetbox/beets/pull/5728

fixup #5701

---

beets/test/helper.py
beets/ui/commands.py
beets/util/__init__.py
beetsplug/convert.py
beetsplug/hook.py
beetsplug/ipfs.py
beetsplug/thumbnails.py
beetsplug/web/__init__.py
test/plugins/test_convert.py
test/plugins/test_ipfs.py
test/plugins/test_thumbnails.py
test/rsrc/convert_stub.py
test/test_ui.py
test/test_util.py

This PR simplifies the codebase by removing Python 2 compatibility code related to string encoding and decoding operations. Key changes:
- Remove custom `_convert_args`, `arg_encoding()`, `_fsencoding()` and `convert_command_args()` functions
- Replace with standard library's `os.fsencode()` and `os.fsdecode()` for file system path handling
- Simplify bytestring/string conversions throughout the codebase
- Update test code to use modern string handling
These changes reduce code complexity and maintenance burden since Python 2 support is no longer needed.

Use os.fsencode to encode bytes

---

beetsplug/parentwork.py
docs/changelog.rst

Fixes #4120.
This may not be the fully desired behavior, let me know if there's anything I should tweak.,

Only output verbose details for parentwork plugin when running explicitly

---

beets/library.py
beets/util/__init__.py
docs/changelog.rst
test/test_util.py

This PR addresses an issue where path legalization, specifically the `truncate_path` function, incorrectly removed parts of filenames that followed a dot. This occurred because `pathlib.Path.with_suffix` was used, which replaces the existing suffix (or what it considers a suffix) rather than just appending.
The fix modifies `truncate_path` to manually append the original suffix after truncating the filename stem. This ensures that dots within the filename, not part of the actual extension, are preserved.
Fixes #5771.

Do not remove everything that follows a dot in item destination path

---

beets/plugins.py
beets/util/id_extractors.py
beetsplug/beatport.py
beetsplug/deezer.py
beetsplug/discogs.py
beetsplug/musicbrainz.py
beetsplug/spotify.py
test/plugins/test_discogs.py
test/plugins/test_musicbrainz.py
test/test_plugins.py
test/util/test_id_extractors.py

Refactor: Centralize release ID extraction
This change introduces a new utility function `extract_release_id` in `beets.util.id_extractors` to handle the parsing of release IDs (or URLs containing IDs) for various metadata sources (Spotify, Deezer, Beatport, Discogs, MusicBrainz, Bandcamp, Tidal).
Key changes:
- Added `extract_release_id` function and `PATTERN_BY_SOURCE` regex dictionary.
- Converted `MetadataSourcePlugin._get_id` static method to an instance method which uses the `data_source` property to pick the correct id extractor.
- Removed the `id_regex` property and updated `_get_id` calls in all modules.
- Replaced old tests related to ID parsing in individual plugin test files with `test/util/test_id_extractors.py` that tests the `extract_release_id` function.
This refactoring …

Centralize release id extraction

---

beetsplug/web/static/beets.js
docs/changelog.rst

The Media Session API provides a way to customize media notifications. This PR has commits that, in summary, updates the metadata for the media session whenever a new track (item) starts playing.
https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API

feat: plugins/web: use media session api for notifications.

---

beets/plugins.py
beets/test/helper.py
beets/util/__init__.py
beetsplug/beatport.py
beetsplug/chroma.py
beetsplug/discogs.py
beetsplug/musicbrainz.py
docs/changelog.rst
docs/plugins/musicbrainz.rst
test/plugins/test_musicbrainz.py

Fixes #5788
This PR fixes a regression that occurred when the MusicBrainz autotagger was moved from core functionality into a standalone plugin. During this transition, the handling of user-configured `extra_tags` was broken, causing `beets` to die with `AttributeError` when this option was set.
Key changes in `musicbrainz` plugin
- Properly process values from `extra_tags` using the same logic as before the migration.
- Centralize common bits from `candidates` and `item_candidates` implementations under `_search_api` to move this class closer towards `MetadataSourcePlugin` definition.

Fix musicbrainz extra tags dict

---

beets/plugins.py
beetsplug/discogs.py
docs/changelog.rst
docs/plugins/discogs.rst
test/plugins/test_discogs.py

This PR adds two new features to the Discogs plugin:
1. A new `track_for_id` method that allows users to retrieve singleton tracks directly by their Discogs ID
- Builds on top of the existing `album_for_id` method
- Searches through the album tracks to find the matching track ID
2. A configurable `search_limit` option to control the number of results returned by the Discogs metadata search queries
- Default value is set to 5
- Helps improve performance by limiting the number of results processed
- Added proper documentation in the plugin docs
Fixes #4661

Discogs: allow fetching singletons by id, add configurable `search_limit`

---

.github/workflows/ci.yaml
beets/test/helper.py
beetsplug/fetchart.py
docs/changelog.rst
test/plugins/test_art.py
test/plugins/test_embedart.py

Adds typings to fetchart; a revised and modernized version of https://github.com/beetbox/beets/pull/5213.
The former pull request became stale because I did more refactoring there, in order to express properties of the `Candidate` (whether or not it is validated) via the type system (motivated by the type state pattern which is more common in Rust.
The result was a little contentious, since it became a little unclear what the purpose of the `Candidate` class should even be at that point.
I think this was a case of combining too many things into a single PR. Thus, this version does not perform any refactoring of that extent. It does sprinkle in a few `assert`s to make thinks clear for the type checker.

Add fetchart typing v2

---

CONTRIBUTING.rst

Meta: I was looking for possible contribution opportunities, so I noticed this in the docs. I assume that the `bite-size` label is outdated, as there aren't actually any issues with that label. Looks like https://github.com/beetbox/beets/labels/good%20first%20issue is currently used.
Note: Further below there's also mention of a `first timers only` label – that link also yields no results and even gives a message about the label being invalid. I wasn't sure if/how that should be replaced, so I didn't touch it. Maybe the sentence I am changing should actually be moved down and replace the one mentioning `first timers only`?

Replace outdated bitesized label link

---

docs/changelog.rst
poetry.lock
pyproject.toml
test/plugins/test_lyrics.py

Fixes #5797.
Today, local tests (`poe test`) will fail to run if `langdetect` is not installed. This change makes `langdetect` required for test runs.
Although this is easy to resolve with `poetry install --all-extras`, the code intends to work without that; it's a worthwhile fix.
* Added `langdetect` to the required test dependencies.
* Ran `poetry lock` to handle this new requirement.
Ran locally.

[Inner loop] Require `langdetect` when running tests

---

beetsplug/spotify.py

Added some more typehints to the spotify plugin. Also added a method to get the tokenfile and changed to logic for the handle_response to use `requests.request`.
This is done mainly to prepare for https://github.com/beetbox/beets/pull/5787, see also https://github.com/beetbox/beets/pull/5814

Minor improvements to spotify plugin typing.

---

.github/workflows/ci.yaml
.github/workflows/integration_test.yaml
.github/workflows/lint.yml
.github/workflows/make_release.yaml

Replace `BrandonLWhite/pipx-install-action@v1.0.3` with `threeal/pipx-install-action@v1.0.0` in CI workflow due to Windows compatibility issues.
**Changes:**
- Switch to alternative pipx-install-action that works on Windows
- Add explicit package specification for poethepoet and poetry
- Resolves GitHub issue: https://github.com/BrandonLWhite/pipx-install-action/issues/62
**Edit**: received a reply from `pipx-install-action` maintainer with a fix: simply remove the breaking cache from GitHub Actions: this worked fine.
Thus I reverted the commit which introduced another action on Windows. The only change that this PR makes is `pipx-install-action` version upgrade.

Fix pipx install action

---

beetsplug/spotify.py
docs/changelog.rst
docs/plugins/spotify.rst
test/plugins/test_spotify.py
test/rsrc/spotify/japanese_track_request.json

Fixes for Issue #5699 (close #5699)
Have made changes to spotify.py (in lines 399 - 407) to allow Chinese and Japanese characters to be read. Previously these were converted to their ASCII values which led to them not being matched. Made changes to test_spotify.py to check parsing of Chinese and Japanese characters. The changes were tested and passed. 
A file called japanese_track_request.json was made to mimic the Spotify API response since I don't have the credentials. Entries in that will need to be modified with the actual entries.
Let me know if any changes need to be made.

Fix: Spotify plugin unable to recognize Chinese and Japanese albums.

---

beetsplug/duplicates.py
docs/changelog.rst
docs/plugins/duplicates.rst

The duplicates plugin currently only supports deleting files entirely, sometimes it's desired to only fix the library and keep files in place. This PR adds this possibility.

Add --remove option to duplicates plugin

---

.git-blame-ignore-revs
beets/dbcore/query.py
beets/dbcore/types.py
beets/library.py
beets/ui/__init__.py
beets/ui/commands.py
beets/util/__init__.py
beets/util/units.py
beetsplug/deezer.py
beetsplug/metasync/amarok.py
beetsplug/metasync/itunes.py
beetsplug/mpdstats.py
beetsplug/playlist.py
beetsplug/spotify.py
beetsplug/types.py
beetsplug/web/__init__.py
test/test_library.py
test/test_query.py
test/test_types.py
test/test_ui_init.py
test/util/test_units.py

This PR moves query and type definitions away from `library.py` to `dbcore` to improve modularity and organization.
**Key Changes:**
*   **Query and Type Relocation:**
*   `PathQuery` and `SingletonQuery` moved from `beets.library` to `beets.dbcore.query`.
*   `DateType`, `PathType` (and its variants `NullPathType`), `MusicalKey`, and `DurationType` moved from `beets.library` to `beets.dbcore.types`.
*   The `BLOB_TYPE` definition was moved from `beets.library` to `beets.dbcore.query` and then referenced in `beets.dbcore.types`.
*   The `human_seconds_short` utility function was moved from `beets.ui` to `beets.util` due to circular dependency.
*   **Test Modernization:**
*   The `PathQueryTest` class in `test/test_query.py` has been rewritten to use `pytest.mark.parametrize` for more …

Move queries and types to respective modules

---

beets/dbcore/query.py
beets/test/_common.py
test/conftest.py
test/test_query.py

Previously:
```sh
Poe => pytest -p no:cov test/test_query.py --durations=10
=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.9.20, pytest-8.3.5, pluggy-1.5.0
cachedir: /tmp/pytest_cache
rootdir: /home/sarunas/repo/beets
configfile: setup.cfg
plugins: anyio-4.9.0, xdist-3.6.1, requests-mock-1.12.1, flask-1.3.0
collected 133 items                                                                                                                                                               
test/test_query.py ..................................................................................................................................... …
```

Rewrite and speed up query tests

---

beets/plugins.py
beetsplug/deezer.py

Added some more typehints to deezer plugin.
I know, it is properly not used much and we don't even have test for the deezer plugin but I want to make this a bit more maintainable, mainly to prepare for https://github.com/beetbox/beets/pull/5787 and make migration a bit easier.

Minor improvements to deezer plugin typing.

---

beetsplug/mpdstats.py
docs/changelog.rst
docs/plugins/mpdstats.rst

Add new configuration option for mpdstats plugin, `played_ratio_threshold`, to allow configuring the percentage the song must be played for it to be counted as played instead of skipped.

feat: mpdstats: adds config option for remaining time threshold to determine if track was played.

---

beets/dbcore/db.py
beets/library/models.py
beets/plugins.py
beets/test/helper.py
beets/ui/__init__.py
beets/util/__init__.py
beetsplug/advancedrewrite.py
test/plugins/test_types_plugin.py

This PR refactors the plugin system to properly handle dynamic type and query registration by converting static class attributes to cached class properties.
**Problem**: Plugin types and queries were stored as mutable class attributes that were manually updated during plugin loading/unloading. This caused issues where:
- Plugin types weren't properly registered in test environments
- Shared mutable state between test runs caused inconsistent behavior  
- Manual cleanup was error-prone and incomplete
See https://github.com/beetbox/beets/pull/5833 and specifically https://github.com/beetbox/beets/pull/5833#issuecomment-3016635209 for the context.
**Solution**: 
- Convert `_types` and `_queries` from static dictionaries to `@cached_classproperty` decorators
- Types and queries are now …

Register types and queries from plugins on models dynamically

---

.github/workflows/changelog_reminder.yaml
.github/workflows/ci.yaml
.github/workflows/lint.yml
poetry.lock

This PR updates dependencies to address security vulnerabilities
- **GitHub Actions:** Updated `tj-actions/changed-files` from v44/v45 to v46 across all workflows
- **Python package updates:**

Update deps to address security vulnerabilities

---

docs/dev/plugins.rst

Use python3 print in plugins.rst docs

Use python3 print in plugins.rst

---

.github/workflows/ci.yaml
beetsplug/absubmit.py
docs/changelog.rst
test/test_plugins.py

Adds a test that loads all available plugins in the beetsplug namespace. This came up during #5876.

Added a load all plugins test.

---

.github/workflows/lint.yml
docs/changelog.rst
test/test_dbcore.py

Add `py.typed` marker file to support PEP 561 typing
This PR adds a `py.typed` marker file to the package directory to indicate that the package includes inline type hints and is PEP 561 compliant.
* The `py.typed` file signals to type checkers (e.g. `mypy`, `pyright`) that type information is available within the package.
* Without this file, external projects using this package will not be able to consume its type hints.
* This improves developer experience and enables better static analysis for downstream users.

Add py.typed marker file to support PEP 561 typing

---

beetsplug/lastgenre/__init__.py
docs/changelog.rst
docs/plugins/lastgenre.rst
test/plugins/test_lastgenre.py

Fixes #5930.  
- Removed whitelist check immediately after last.fm fetch, which fixes canonicalization - also unwanted genres need to remain at this point to get successfully resolved "up" to parent genres
- Removed the `_filter_valid_genres()` helper method and went back to _inline_ list comprehensions (readability)
- Ensured bug #5649 does not regress (the part were a resolve would kick out everything and no fallback happens) by running a full `_resolve_genre()` in each stage - if no genres remain in a stage the next one is hit.
- Refactored `_get_genre` using a local helper method and returning immediately on a satisfying outcome (Commits https://github.com/beetbox/beets/pull/5946/commits/d28738d92fc966fae198f5655a06d76b08332dc3 and …

Lastgenre fix early whitelist check breaking canonicalization

---

docs/plugins/discogs.rst

In the documentation of the Discogs plugin the ``index_tracks`` configuration option does not include the detail about the default configuration that is applied when the option is not explicitly managed in the configuration file.
If this PR is approved, the documentation will include that default ;)

docs: update discogs.rst - add default of index_tracks configuration option

---

beets/metadata_plugins.py
beetsplug/deezer.py
beetsplug/spotify.py
docs/changelog.rst
docs/plugins/deezer.rst
test/plugins/test_spotify.py

Moved the `_construct_search_query` method that was duplicated in the spotify and deezer plugins into the (new) shared helper baseclass ( `SearchApiMetadataSourcePlugin`).
By default deezer now also does not ascii encode a query when it is send but the legacy behaviour can be restored using the `deezer.search_query_ascii` option.
closes #5860

Avoid Unidecoding Query Strings in Deezer Metadata Plugin

---

.github/CODEOWNERS
CONTRIBUTING.rst

Add CODEOWNERS file assigning all files (*) to [`@beetbox/maintainers`](https://github.com/orgs/beetbox/teams/maintainers) so that team is auto-requested for reviews.

Add CODEOWNERS file

---

beets/plugins.py
docs/changelog.rst
test/test_logging.py

Fixes #6033
This PR addresses a bug where plugin loading failed when plugins imported other `BeetsPlugin` classes, namely `chroma` and `bpsync`.
- Add module path filtering to ensure only classes from the target plugin module are considered, preventing conflicts when plugins import other `BeetsPlugin` classes

Fix plugin loading

---

.github/CODEOWNERS
beets/logging.py
beetsplug/fetchart.py
beetsplug/lyrics.py
docs/changelog.rst
test/test_logging.py

This PR enhances `beets/logging.py` with improved typing and tests:
* `getLogger` now returns the precise logger type (`BeetsLogger` or `RootLogger`).
* Tests use `pytest` and `parametrize` for more concise and readable coverage.

Improved `beets/logging.py` typing

---

beetsplug/spotify.py
docs/changelog.rst

Spotify: Store track attributes even if audio features are missing [small PR]

---

beets/ui/commands.py

Add missing space to "Finding tags for album" prompt
(It was annoying me, and it's a simple enough fix!)

fix spacing for "finding tags for" prompt
